name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - id: install-deps
        name: Install dependencies
        run: |
          bun install

      - id: typecheck
        name: Type checking
        run: bun run typecheck

      - id: lint
        name: Run Biome
        run: biome ci

      - id: test
        name: Run tests and checks
        run: |
          bun test
