name: Checkout repository
description: Checkout full repository history for Nx/release workflows.

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        filter: tree:0
        fetch-depth: 0
