//! Validated span-tree → canonical `01f` `RecordBatch` conversion.

use std::error::Error;
use std::fmt;
use std::sync::{Arc, LazyLock};

use arrow_array::builder::BooleanBufferBuilder;
use arrow_array::{
    ArrayRef, DictionaryArray, RecordBatch, StringArray, TimestampNanosecondArray, UInt8Array,
    UInt32Array, UInt64Array,
};
use arrow_buffer::NullBuffer;
use arrow_schema::{ArrowError, DataType, Field, Schema, TimeUnit};
use lmao_core::{
    EntryType, SYSTEM_COLUMNS, SystemColumnKind, entry_type_from_header, vocabulary_id_from_header,
};

use crate::dict::{
    ColumnDictionary, FinalizedDictionary, FirstSeenDictionary, StableVocabularyCatalog,
    StableVocabularyKind, StableVocabularyLookupError, vocabulary_dictionary,
};
use crate::source::{SpanSource, walk_pre_order};

/// Generated by `lmao-core` from TypeScript's authoritative `ENTRY_TYPE_NAMES` table.
pub const ENTRY_TYPE_NAMES: [&str; EntryType::COUNT + 1] = EntryType::NAMES;

fn dict_type(key: DataType) -> DataType {
    DataType::Dictionary(Box::new(key), Box::new(DataType::Utf8))
}

static TRACE_SCHEMA: LazyLock<Arc<Schema>> = LazyLock::new(|| {
    Arc::new(Schema::new(
        SYSTEM_COLUMNS
            .iter()
            .map(|column| {
                let data_type = match column.kind {
                    SystemColumnKind::TimestampNanosecond => {
                        DataType::Timestamp(TimeUnit::Nanosecond, None)
                    }
                    SystemColumnKind::DictionaryU32 => dict_type(DataType::UInt32),
                    SystemColumnKind::DictionaryU8 => dict_type(DataType::UInt8),
                    SystemColumnKind::U64 => DataType::UInt64,
                    SystemColumnKind::U32 => DataType::UInt32,
                };
                Field::new(column.name, data_type, column.nullable)
            })
            .collect::<Vec<_>>(),
    ))
});

static ENTRY_TYPE_VALUES: LazyLock<ArrayRef> =
    LazyLock::new(|| Arc::new(StringArray::from_iter_values(ENTRY_TYPE_NAMES)) as ArrayRef);

pub fn trace_schema() -> Arc<Schema> {
    Arc::clone(&TRACE_SCHEMA)
}

#[derive(Debug)]
pub enum ConvertError {
    Arrow(ArrowError),
    RowCountOverflow,
    DictionaryOverflow,
    MissingSourceValue {
        row: usize,
        column: &'static str,
    },
    InvalidEntryType {
        row: usize,
        entry_type: u8,
    },
    InvalidVocabularyId {
        row: usize,
        id: u32,
    },
    VocabularyKindMismatch {
        row: usize,
        id: u32,
        expected: StableVocabularyKind,
        actual: StableVocabularyKind,
    },
    MissingDynamicMessage {
        row: usize,
        entry_type: u8,
    },
}

impl fmt::Display for ConvertError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Arrow(error) => error.fmt(f),
            Self::RowCountOverflow => f.write_str("Arrow row count exceeds usize"),
            Self::DictionaryOverflow => f.write_str("Arrow dictionary key exceeds u32"),
            Self::MissingSourceValue { row, column } => {
                write!(f, "span source is missing {column} at row {row}")
            }
            Self::InvalidEntryType { row, entry_type } => {
                write!(f, "invalid packed entry type {entry_type} at row {row}")
            }
            Self::InvalidVocabularyId { row, id } => {
                write!(f, "unknown static vocabulary id {id} at row {row}")
            }
            Self::VocabularyKindMismatch {
                row,
                id,
                expected,
                actual,
            } => write!(
                f,
                "static vocabulary id {id} has kind tag {}, expected {} at row {row}",
                *actual as u8, *expected as u8,
            ),
            Self::MissingDynamicMessage { row, entry_type } => write!(
                f,
                "dynamic entry type {entry_type} is missing its message at row {row}",
            ),
        }
    }
}

impl Error for ConvertError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Arrow(error) => Some(error),
            _ => None,
        }
    }
}

impl From<ArrowError> for ConvertError {
    fn from(value: ArrowError) -> Self {
        Self::Arrow(value)
    }
}

#[inline]
fn required_vocabulary_kind(entry_type: EntryType) -> Option<StableVocabularyKind> {
    match entry_type {
        EntryType::SpanStart => Some(StableVocabularyKind::SpanName),
        EntryType::Trace
        | EntryType::Debug
        | EntryType::Info
        | EntryType::Warn
        | EntryType::Error => Some(StableVocabularyKind::LogTemplate),
        _ => None,
    }
}

fn append_optional_key(keys: &mut Vec<u32>, valid: &mut BooleanBufferBuilder, key: Option<u32>) {
    keys.push(key.unwrap_or(0));
    valid.append(key.is_some());
}

fn optional_dictionary(
    keys: Vec<u32>,
    mut valid: BooleanBufferBuilder,
    dictionary: &FinalizedDictionary<'_>,
) -> Result<ArrayRef, ArrowError> {
    let values: ArrayRef = Arc::new(StringArray::from_iter_values(dictionary.values.iter()));
    Ok(Arc::new(DictionaryArray::try_new(
        UInt32Array::new(keys.into(), Some(NullBuffer::new(valid.finish()))),
        values,
    )?))
}

pub fn convert_span_trees<S: SpanSource>(
    roots: &[S],
    vocabulary: &StableVocabularyCatalog<'_>,
) -> Result<RecordBatch, ConvertError> {
    let mut buffers = Vec::new();
    let mut total_rows = 0usize;
    let mut row_count_overflow = false;
    let mut trace_dict = ColumnDictionary::default();
    let mut package_name_dict = ColumnDictionary::default();
    let mut package_file_dict = ColumnDictionary::default();
    let mut git_sha_dict = ColumnDictionary::default();

    walk_pre_order(roots, &mut |buffer: &S| {
        buffers.push(buffer);
        match total_rows.checked_add(buffer.row_count()) {
            Some(total) => total_rows = total,
            None => row_count_overflow = true,
        }
        trace_dict.observe(buffer.identity().trace_id.as_str());
        if let Some(value) = buffer.package_name() {
            package_name_dict.observe(value);
        }
        if let Some(value) = buffer.package_file() {
            package_file_dict.observe(value);
        }
        if let Some(value) = buffer.git_sha() {
            git_sha_dict.observe(value);
        }
    });
    if row_count_overflow {
        return Err(ConvertError::RowCountOverflow);
    }

    let trace_dict = trace_dict.finalize_indexed();
    let package_name_dict = package_name_dict.finalize_indexed();
    let package_file_dict = package_file_dict.finalize_indexed();
    let git_sha_dict = git_sha_dict.finalize_indexed();
    let mut dynamic_messages = FirstSeenDictionary::default();
    let stable_message_count =
        u32::try_from(vocabulary.len()).map_err(|_| ConvertError::DictionaryOverflow)?;

    let mut timestamps = Vec::with_capacity(total_rows);
    let mut trace_keys = Vec::with_capacity(total_rows);
    let mut thread_ids = Vec::with_capacity(total_rows);
    let mut span_ids = Vec::with_capacity(total_rows);
    let mut parent_thread_ids = Vec::with_capacity(total_rows);
    let mut parent_span_ids = Vec::with_capacity(total_rows);
    let mut parent_valid = BooleanBufferBuilder::new(total_rows);
    let mut entry_keys = Vec::with_capacity(total_rows);
    let mut package_name_keys = Vec::with_capacity(total_rows);
    let mut package_name_valid = BooleanBufferBuilder::new(total_rows);
    let mut package_file_keys = Vec::with_capacity(total_rows);
    let mut package_file_valid = BooleanBufferBuilder::new(total_rows);
    let mut git_sha_keys = Vec::with_capacity(total_rows);
    let mut git_sha_valid = BooleanBufferBuilder::new(total_rows);
    let mut message_keys = Vec::with_capacity(total_rows);
    let mut message_valid = BooleanBufferBuilder::new(total_rows);
    let mut lines = Vec::with_capacity(total_rows);
    let mut absolute_row = 0usize;

    for buffer in buffers {
        let identity = buffer.identity();
        let trace_key = trace_dict
            .index_of(identity.trace_id.as_str())
            .expect("trace ID was observed before dictionary finalization");
        let (parent_thread, parent_span, has_parent) = match &identity.parent {
            Some(parent) => (parent.thread_id, parent.span_id, true),
            None => (0, 0, false),
        };
        let package_name_key = buffer
            .package_name()
            .and_then(|value| package_name_dict.index_of(value));
        let package_file_key = buffer
            .package_file()
            .and_then(|value| package_file_dict.index_of(value));
        let git_sha_key = buffer
            .git_sha()
            .and_then(|value| git_sha_dict.index_of(value));

        for row in 0..buffer.row_count() {
            let timestamp = buffer
                .timestamp(row)
                .ok_or(ConvertError::MissingSourceValue {
                    row: absolute_row,
                    column: "timestamp",
                })?;
            let header = buffer
                .packed_header(row)
                .ok_or(ConvertError::MissingSourceValue {
                    row: absolute_row,
                    column: "packed_header",
                })?;
            let raw_entry_type = header as u8;
            let entry_type =
                entry_type_from_header(header).ok_or(ConvertError::InvalidEntryType {
                    row: absolute_row,
                    entry_type: raw_entry_type,
                })?;
            let vocabulary_id = vocabulary_id_from_header(header).map(|id| id.get());
            let message_key = if let Some(id) = vocabulary_id {
                let kind = required_vocabulary_kind(entry_type).ok_or(
                    ConvertError::InvalidVocabularyId {
                        row: absolute_row,
                        id,
                    },
                )?;
                match vocabulary.key_for_id(id, kind) {
                    Ok(key) => Some(key),
                    Err(StableVocabularyLookupError::UnknownId(id)) => {
                        return Err(ConvertError::InvalidVocabularyId {
                            row: absolute_row,
                            id,
                        });
                    }
                    Err(StableVocabularyLookupError::KindMismatch {
                        id,
                        expected,
                        actual,
                    }) => {
                        return Err(ConvertError::VocabularyKindMismatch {
                            row: absolute_row,
                            id,
                            expected,
                            actual,
                        });
                    }
                }
            } else if let Some(message) = buffer.dynamic_message(row) {
                Some(match vocabulary.key_for_value(message) {
                    Some(key) => key,
                    None => stable_message_count
                        .checked_add(dynamic_messages.observe(message))
                        .ok_or(ConvertError::DictionaryOverflow)?,
                })
            } else if required_vocabulary_kind(entry_type).is_some() {
                return Err(ConvertError::MissingDynamicMessage {
                    row: absolute_row,
                    entry_type: entry_type.as_u8(),
                });
            } else {
                None
            };

            timestamps.push(timestamp);
            trace_keys.push(trace_key);
            thread_ids.push(identity.thread_id);
            span_ids.push(identity.span_id);
            parent_thread_ids.push(parent_thread);
            parent_span_ids.push(parent_span);
            parent_valid.append(has_parent);
            entry_keys.push(entry_type.as_u8());
            append_optional_key(
                &mut package_name_keys,
                &mut package_name_valid,
                package_name_key,
            );
            append_optional_key(
                &mut package_file_keys,
                &mut package_file_valid,
                package_file_key,
            );
            append_optional_key(&mut git_sha_keys, &mut git_sha_valid, git_sha_key);
            append_optional_key(&mut message_keys, &mut message_valid, message_key);
            lines.push(buffer.line_number(row));
            absolute_row += 1;
        }
    }

    let parent_nulls = NullBuffer::new(parent_valid.finish());
    let entry_col =
        DictionaryArray::try_new(UInt8Array::from(entry_keys), Arc::clone(&ENTRY_TYPE_VALUES))?;
    let trace_col = DictionaryArray::try_new(
        UInt32Array::from(trace_keys),
        Arc::new(StringArray::from_iter_values(trace_dict.values.iter())) as ArrayRef,
    )?;
    let message_values: ArrayRef = vocabulary_dictionary(vocabulary, &dynamic_messages.values)?;
    let message_col = DictionaryArray::try_new(
        UInt32Array::new(
            message_keys.into(),
            Some(NullBuffer::new(message_valid.finish())),
        ),
        message_values,
    )?;

    RecordBatch::try_new(
        trace_schema(),
        vec![
            Arc::new(TimestampNanosecondArray::from(timestamps)),
            Arc::new(trace_col),
            Arc::new(UInt64Array::from(thread_ids)),
            Arc::new(UInt32Array::from(span_ids)),
            Arc::new(UInt64Array::new(
                parent_thread_ids.into(),
                Some(parent_nulls.clone()),
            )),
            Arc::new(UInt32Array::new(parent_span_ids.into(), Some(parent_nulls))),
            Arc::new(entry_col),
            optional_dictionary(package_name_keys, package_name_valid, &package_name_dict)?,
            optional_dictionary(package_file_keys, package_file_valid, &package_file_dict)?,
            optional_dictionary(git_sha_keys, git_sha_valid, &git_sha_dict)?,
            Arc::new(message_col),
            Arc::new(UInt32Array::from(lines)),
        ],
    )
    .map_err(ConvertError::Arrow)
}
