//! Inherited span scope attributes, per `specs/lmao/01i_span_scope_attributes.md`.
//!
//! Scope is the "default context for rows without a direct write": set once on a
//! span, inherited by every child span created afterwards, and materialized into
//! attribute columns at Arrow-conversion time where **direct writes always win**.
//!
//! ## Why this is hand-written core and not codegen
//!
//! `01i` decides this explicitly — *"No runtime code generation needed for scope"* —
//! and the TypeScript implementation follows it: `_scopeValues` is a plain object on
//! the buffer, keyed by field NAME, and only the per-column *fill* is generated
//! (`spanLoggerGenerator.ts: generatePrefillScopedAttributesMethod`). The split is
//! principled, not incidental: storage and merge are schema-independent and
//! name-keyed, so codegen would emit N copies of one algorithm; the fill is
//! per-column and typed, so it must be generated. Rust mirrors the same split —
//! [`SpanScope`] here, `fill_scope()` generated by `lmao_macros::define_log_schema!`.
//!
//! ## Why a sorted slice and not a hash map
//!
//! Determinism. `lib.rs` states the constraint: the same `(build, seed, config)` must
//! produce bit-identical trace bytes. `HashMap` iteration order is a function of hash
//! seed and insertion history, so scope-derived column bytes would vary run to run.
//! Entries are therefore held in a slice **sorted by field-name content** — never by
//! pointer address, which would reintroduce the same nondeterminism through
//! `&'static str` layout. Schemas have tens of fields, not thousands, so binary
//! search on the cold path is the right shape and needs no index structure.
//!
//! ## Immutability and inheritance cost
//!
//! [`SpanScope`] is never mutated: [`SpanScope::merge`] returns a NEW value, which is
//! what makes inheritance-by-reference (`Arc` clone — a refcount bump, zero
//! allocation, no copy) safe and gives children snapshot-at-creation semantics. A
//! parent that changes its scope after a child starts cannot perturb that child, so
//! concurrent and async execution read a stable scope. This is the same guarantee
//! `01i` derives for the TypeScript frozen-object model, reached with a stronger
//! mechanism: here immutability is enforced by the type, not by `Object.freeze`.

use crate::columns::SharedStr;
use std::sync::Arc;

/// One scope attribute value. Variants correspond 1:1 to the column kinds a schema
/// field can have ([`crate::columns::FieldStrategy`]); `category` and `text` share
/// [`ScopeValue::Text`] because both are backed by [`crate::columns::StrColumn`] and
/// differ only in flush strategy.
#[derive(Debug, Clone, PartialEq)]
pub enum ScopeValue {
    Number(f64),
    Uint64(u64),
    Boolean(bool),
    /// `category` and `text` columns. A `&'static str` value costs zero allocations;
    /// a dynamic value rides an `Arc` refcount.
    Text(SharedStr),
    /// `enum` columns: index into the schema-time dictionary.
    EnumIndex(u16),
}

/// One entry of a scope update: the field name, and `Some(value)` to set it or
/// `None` to clear it.
///
/// The tri-state of `01i`'s `ScopeUpdate<T>` (set / clear / leave alone) is
/// represented exactly, with no fourth state expressible: *set* and *clear* are the
/// two `Option` cases, and *leave alone* is absence from the update slice. There is
/// no `undefined`-shaped case to mishandle, because a Rust caller cannot pass a field
/// that is simultaneously present and absent. An update is a borrowed slice, so a
/// caller can build one in a stack array and allocate nothing.
pub type ScopeEntry = (&'static str, Option<ScopeValue>);

/// An immutable, name-keyed set of scope attributes, sorted by field name.
///
/// The handle IS the shared value: cloning a `SpanScope` is a refcount bump on ONE
/// heap block, which is what makes child inheritance free. An earlier shape wrapped a
/// `Box<[_]>` in an outer `Arc`, costing two resident blocks and a second pointer hop
/// on every lookup for nothing.
///
/// There is no way to build an EMPTY `SpanScope`: [`SpanScope::merge`] takes and
/// returns `Option<Self>`, so "no scope" is `None` and never an allocated empty
/// value. One representation per logical scope, and the empty case owns no heap.
#[derive(Debug, Clone, PartialEq)]
pub struct SpanScope {
    /// Sorted by name content, so both lookup and iteration are deterministic.
    entries: Arc<[(&'static str, ScopeValue)]>,
}

impl SpanScope {
    /// Number of fields this scope sets.
    ///
    /// Deliberately not `len` + `is_empty`: a `SpanScope` cannot BE empty, because
    /// [`SpanScope::merge`] returns `Option<Self>` and yields `None` for an empty
    /// result. An `is_empty` here would always answer `false` and invite callers to
    /// branch on a constant; `field_count` says exactly what it counts.
    #[inline]
    pub fn field_count(&self) -> usize {
        self.entries.len()
    }

    /// Value for `name`, or `None` when this scope does not set it.
    #[inline]
    pub fn get(&self, name: &str) -> Option<&ScopeValue> {
        self.entries
            .binary_search_by_key(&name, |(field, _)| *field)
            .ok()
            .map(|index| &self.entries[index].1)
    }

    /// Entries in field-name order.
    #[inline]
    pub fn iter(&self) -> impl Iterator<Item = (&'static str, &ScopeValue)> {
        self.entries.iter().map(|(name, value)| (*name, value))
    }

    /// Apply `update` to `current` and return the merged scope, or `None` when the
    /// result holds nothing. `current` is never modified — that is what lets a child
    /// hold its parent's scope indefinitely.
    ///
    /// Semantics are `01i`'s merge, matched to the TypeScript `_setScope`:
    /// - `Some(value)` sets the field, replacing any existing value;
    /// - `None` clears the field, and clearing an absent field is a no-op;
    /// - a field absent from `update` keeps its current value.
    ///
    /// When `update` names the same field more than once the LAST occurrence wins,
    /// matching the JavaScript object-literal semantics the TS API is built on.
    ///
    /// Cost is `O(existing * update)` plus the sort. Deliberately unoptimized: `01i`
    /// puts scope wholly off the hot path (user code, span creation, Arrow
    /// conversion), updates carry a handful of fields, and a linear scan over a
    /// handful beats any index that must first be built.
    pub fn merge(current: Option<&Self>, update: &[ScopeEntry]) -> Option<Self> {
        let existing: &[(&'static str, ScopeValue)] =
            current.map(|scope| &*scope.entries).unwrap_or(&[]);
        let mut next: Vec<(&'static str, ScopeValue)> =
            Vec::with_capacity(existing.len() + update.len());

        // Existing entries survive unless the update names them (to set or to clear).
        for (name, value) in existing {
            if !update.iter().any(|(field, _)| field == name) {
                next.push((*name, value.clone()));
            }
        }
        for (index, (name, value)) in update.iter().enumerate() {
            // Only the last occurrence of a repeated field takes effect.
            if update[index + 1..].iter().any(|(field, _)| field == name) {
                continue;
            }
            // A clear contributes nothing: absence IS the cleared state, so there is
            // no tombstone to represent and no way to observe a "present but unset"
            // field.
            if let Some(value) = value {
                next.push((*name, value.clone()));
            }
        }
        if next.is_empty() {
            return None;
        }

        next.sort_unstable_by_key(|(name, _)| *name);
        Some(Self {
            entries: Arc::from(next),
        })
    }
}

/// Report a scope value whose variant does not match the schema column naming it.
/// Called by the generated `fill_scope`, which then leaves the cell untouched.
///
/// Ignoring the value in release is deliberate parity: the TypeScript readers
/// (`getStringScopeValue`, `getNumberScopeValue`, `getBooleanScopeValue`) return
/// `undefined` for a type-mismatched scope value rather than coercing it, so a
/// mismatch produces a null cell in both implementations.
///
/// But a silently dropped attribute is a trace lying about what it contains, and a
/// mismatch can only arise from naming a real schema column with the wrong
/// [`ScopeValue`] variant — a programmer error the schema already knows about, not
/// an operational failure. So debug builds panic instead of shrugging.
#[cold]
#[inline(never)]
pub fn report_scope_mismatch(field: &'static str, expected: &'static str, found: &ScopeValue) {
    if cfg!(debug_assertions) {
        panic!("scope field `{field}` expects {expected} but holds {found:?}");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn text(value: &'static str) -> Option<ScopeValue> {
        Some(ScopeValue::Text(SharedStr::Static(value)))
    }

    fn merged(current: Option<&SpanScope>, update: &[ScopeEntry]) -> SpanScope {
        SpanScope::merge(current, update).expect("this update leaves the scope non-empty")
    }

    /// The worked example from `01i`'s "setScope API - Immutable Merge Semantics".
    #[test]
    fn spec_merge_example() {
        let a = merged(None, &[("order_id", text("x"))]);
        assert_eq!(a.field_count(), 1);

        let b = merged(Some(&a), &[("user_id", text("u1"))]);
        assert_eq!(b.get("order_id"), text("x").as_ref());
        assert_eq!(b.get("user_id"), text("u1").as_ref());

        let c = merged(Some(&b), &[("user_id", text("u2"))]);
        assert_eq!(c.get("user_id"), text("u2").as_ref());
        assert_eq!(c.field_count(), 2, "overwrite replaces, it does not append");

        let d = merged(Some(&c), &[("user_id", None)]);
        assert_eq!(d.get("user_id"), None);
        assert_eq!(d.get("order_id"), text("x").as_ref());
        assert_eq!(d.field_count(), 1, "clearing removes exactly one field");

        // Every earlier value is still intact: merge never mutated in place.
        assert_eq!(a.field_count(), 1);
        assert_eq!(b.get("user_id"), text("u1").as_ref());
        assert_eq!(c.get("user_id"), text("u2").as_ref());
    }

    #[test]
    fn clearing_an_absent_field_is_a_no_op() {
        let scope = merged(None, &[("a", text("1"))]);
        assert_eq!(merged(Some(&scope), &[("missing", None)]), scope);
    }

    #[test]
    fn entries_are_sorted_by_name_regardless_of_update_order() {
        let scope = merged(
            None,
            &[("z", text("1")), ("a", text("2")), ("m", text("3"))],
        );
        let names: Vec<_> = scope.iter().map(|(name, _)| name).collect();
        assert_eq!(names, ["a", "m", "z"]);
    }

    #[test]
    fn last_occurrence_of_a_repeated_field_wins() {
        let scope = merged(None, &[("a", text("first")), ("a", text("last"))]);
        assert_eq!(scope.field_count(), 1);
        assert_eq!(scope.get("a"), text("last").as_ref());

        // A trailing clear beats an earlier set, mirroring `{ a: 'x', a: null }`.
        assert_eq!(
            SpanScope::merge(None, &[("a", text("x")), ("a", None)]),
            None,
        );
    }

    /// An empty result is `None`, never an allocated empty scope — the canonical
    /// representation the buffer relies on.
    #[test]
    fn an_emptied_scope_is_none() {
        assert_eq!(SpanScope::merge(None, &[]), None);
        let scope = merged(None, &[("a", text("1"))]);
        assert_eq!(SpanScope::merge(Some(&scope), &[("a", None)]), None);
    }
}
