//! Canonical scalar ABI for [`crate::ThreadSpanBuffer`].
//!
//! Bindings (JSC and Wasm) only re-export these symbols. Strings cross the ABI
//! as UTF-8 pointer/length pairs on cold dynamic entrypoints; warmed writers use
//! an intern ordinal and a single scalar value. Packed-u64 row endpoints return
//! zero on failure; u8 status endpoints return zero on success and nonzero on
//! failure.

use crate::arena::TextInput;
use crate::columns::FieldMeta;
use crate::entry_type::EntryType;
use crate::identity::TraceId;
use crate::packed_header::VocabularyId;
use crate::thread_buffer::{ColumnValue, ThreadSpanBuffer};
use std::sync::Arc;

/// Opaque pointer type used by native and Wasm callers.
#[repr(C)]
pub struct ThreadSpanBufferHandle {
    _private: [u8; 0],
}

fn as_buffer<'a>(handle: *mut ThreadSpanBufferHandle) -> Option<&'a mut ThreadSpanBuffer> {
    if handle.is_null() {
        return None;
    }
    // SAFETY: handles are returned by `thread_span_buffer_new*` and remain
    // uniquely owned by the caller until `thread_span_buffer_free`.
    Some(unsafe { &mut *(handle.cast::<ThreadSpanBuffer>()) })
}

fn parse_trace(ptr: *const u8, len: usize) -> Option<TraceId> {
    if len > 0 && ptr.is_null() {
        return None;
    }
    // SAFETY: callers promise `ptr..ptr+len` is readable UTF-8 storage for the
    // duration of this call; a zero-length null pointer is accepted.
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    let value = std::str::from_utf8(bytes).ok()?;
    TraceId::new(Arc::<str>::from(value)).ok()
}

/// Borrow the caller's UTF-8 for the duration of one ABI call.
///
/// The borrow is unbounded, which is sound only because every caller hands the
/// result straight to a row store that copies it into its arena before
/// returning. The bytes belong to the caller and are not retained: that is the
/// same discipline the reverse ABI runs in `containium-realm-spans`.
///
/// # Safety
/// `ptr..ptr + len` must be readable until the returned borrow is dropped.
unsafe fn parse_text<'a>(ptr: *const u8, len: usize) -> Option<&'a str> {
    if len > 0 && ptr.is_null() {
        return None;
    }
    // SAFETY: callers promise `ptr..ptr+len` is readable storage for this call.
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    ThreadSpanBuffer::utf8(bytes).ok()
}

fn packed_row(span_id: u32, row: u32) -> u64 {
    (u64::from(span_id) << 32) | u64::from(row)
}

fn valid_capacity(capacity: usize) -> bool {
    capacity.is_power_of_two() && (crate::MIN_CAPACITY..=crate::MAX_CAPACITY).contains(&capacity)
}

/// Allocate a schema-less handle. Use `thread_span_buffer_new_with_fields` for
/// typed schema attributes; both constructors share the exact same row store.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub extern "C" fn thread_span_buffer_new(
    thread_id: u64,
    capacity: usize,
) -> *mut ThreadSpanBufferHandle {
    if !valid_capacity(capacity) {
        return std::ptr::null_mut();
    }
    Box::into_raw(Box::new(ThreadSpanBuffer::new(thread_id, capacity, &[])))
        .cast::<ThreadSpanBufferHandle>()
}

/// Allocate a handle with schema metadata generated by the host build.
///
/// # Safety
/// `fields` must either be null when `field_count == 0`, or point to a
/// `'static` contiguous `FieldMeta` table. The table remains borrowed by every
/// overflow block for the handle's lifetime.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_new_with_fields(
    thread_id: u64,
    capacity: usize,
    fields: *const FieldMeta,
    field_count: usize,
) -> *mut ThreadSpanBufferHandle {
    if !valid_capacity(capacity) || (field_count > 0 && fields.is_null()) {
        return std::ptr::null_mut();
    }
    // SAFETY: required by this function's contract; zero count may use a null
    // pointer and is represented by the static empty slice.
    let fields: &'static [FieldMeta] = if field_count == 0 {
        &[]
    } else {
        unsafe { std::slice::from_raw_parts(fields, field_count) }
    };
    Box::into_raw(Box::new(ThreadSpanBuffer::new(thread_id, capacity, fields)))
        .cast::<ThreadSpanBufferHandle>()
}

/// Release a handle. Null is accepted so teardown paths can be idempotent.
/// # Safety
/// `handle` must be null or a live handle returned by a constructor and not
/// previously freed.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_free(handle: *mut ThreadSpanBufferHandle) {
    if !handle.is_null() {
        // SAFETY: the pointer was allocated by one of the constructors and is
        // consumed exactly once here.
        drop(unsafe { Box::from_raw(handle.cast::<ThreadSpanBuffer>()) });
    }
}

/// Intern one dynamic UTF-8 value. The ordinal is stable across overflow
/// blocks and valid until the handle is freed; zero denotes failure.
/// # Safety
/// `handle` must be a live uniquely owned handle. When `len > 0`, `ptr` must
/// point to readable storage for `len` bytes for the duration of this call.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_intern(
    handle: *mut ThreadSpanBufferHandle,
    ptr: *const u8,
    len: usize,
) -> u32 {
    let Some(buffer) = as_buffer(handle) else {
        return 0;
    };
    if len > 0 && ptr.is_null() {
        return 0;
    }
    // SAFETY: caller owns readable bytes for this call; null is valid for len 0.
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    buffer.intern_utf8(bytes).unwrap_or(0)
}

/// Open a span whose name is an intern ordinal. The return packs
/// `(span_id << 32) | start_row`; zero denotes failure.
/// # Safety
/// `handle` must be a live uniquely owned handle. `trace_ptr` must point to
/// readable storage for `trace_len` bytes, unless the length is zero.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_open_span(
    handle: *mut ThreadSpanBufferHandle,
    trace_ptr: *const u8,
    trace_len: usize,
    parent_thread_id: u64,
    parent_span_id: u32,
    name_ordinal: u32,
    timestamp: i64,
    line: u32,
) -> u64 {
    let Some(buffer) = as_buffer(handle) else {
        return 0;
    };
    let Some(trace_id) = parse_trace(trace_ptr, trace_len) else {
        return 0;
    };
    let Ok(span_id) = buffer.open_span_interned(
        trace_id,
        parent_thread_id,
        parent_span_id,
        name_ordinal,
        timestamp,
        line,
    ) else {
        return 0;
    };
    let Some(row) = buffer.start_row(span_id) else {
        return 0;
    };
    let row = u32::try_from(row).expect("thread buffer rows fit u32");
    packed_row(span_id, row)
}

/// Open a span with a manifest-global static vocabulary ID. This is useful for
/// engine-owned names; authored names should use the interned endpoint above.
/// # Safety
/// `handle` must be a live uniquely owned handle. `trace_ptr` must point to
/// readable storage for `trace_len` bytes, unless the length is zero.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_open_span_static(
    handle: *mut ThreadSpanBufferHandle,
    trace_ptr: *const u8,
    trace_len: usize,
    parent_thread_id: u64,
    parent_span_id: u32,
    name_id: u32,
    timestamp: i64,
    line: u32,
) -> u64 {
    let Some(buffer) = as_buffer(handle) else {
        return 0;
    };
    let Some(trace_id) = parse_trace(trace_ptr, trace_len) else {
        return 0;
    };
    let Ok(name_id) = VocabularyId::try_from(name_id) else {
        return 0;
    };
    let Ok(span_id) = buffer.open_span_static(
        trace_id,
        parent_thread_id,
        parent_span_id,
        name_id,
        timestamp,
        line,
    ) else {
        return 0;
    };
    let Some(row) = buffer.start_row(span_id) else {
        return 0;
    };
    let row = u32::try_from(row).expect("thread buffer rows fit u32");
    packed_row(span_id, row)
}

/// Cold dynamic-name variant. The UTF-8 name is copied once into `SharedStr`.
/// # Safety
/// `handle` must be a live uniquely owned handle. Both byte ranges must be
/// readable for the duration of this call; null pointers are valid only with
/// zero lengths.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_open_span_dynamic(
    handle: *mut ThreadSpanBufferHandle,
    trace_ptr: *const u8,
    trace_len: usize,
    parent_thread_id: u64,
    parent_span_id: u32,
    name_ptr: *const u8,
    name_len: usize,
    timestamp: i64,
    line: u32,
) -> u64 {
    let Some(buffer) = as_buffer(handle) else {
        return 0;
    };
    let Some(trace_id) = parse_trace(trace_ptr, trace_len) else {
        return 0;
    };
    let Some(name) = (unsafe { parse_text(name_ptr, name_len) }) else {
        return 0;
    };
    let Ok(span_id) = buffer.open_span(
        trace_id,
        parent_thread_id,
        parent_span_id,
        TextInput::Dynamic(name),
        timestamp,
        line,
    ) else {
        return 0;
    };
    let Some(row) = buffer.start_row(span_id) else {
        return 0;
    };
    let row = u32::try_from(row).expect("thread buffer rows fit u32");
    packed_row(span_id, row)
}

/// # Safety
/// `handle` must be a live uniquely owned handle.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_end_ok(
    handle: *mut ThreadSpanBufferHandle,
    span_id: u32,
    timestamp: i64,
) -> u8 {
    let Some(buffer) = as_buffer(handle) else {
        return 1;
    };
    buffer.end_ok(span_id, timestamp).is_err() as u8
}

/// # Safety
/// `handle` must be a live uniquely owned handle.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_end_err(
    handle: *mut ThreadSpanBufferHandle,
    span_id: u32,
    timestamp: i64,
) -> u8 {
    let Some(buffer) = as_buffer(handle) else {
        return 1;
    };
    buffer.end_err(span_id, timestamp).is_err() as u8
}

/// Warmed log path: `message_ordinal` is from `thread_span_buffer_intern`.
/// # Safety
/// `handle` must be a live uniquely owned handle.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_append_log(
    handle: *mut ThreadSpanBufferHandle,
    span_id: u32,
    entry_type: u8,
    message_ordinal: u32,
    timestamp: i64,
    line: u32,
) -> u64 {
    let Some(buffer) = as_buffer(handle) else {
        return 0;
    };
    let Some(entry_type) = EntryType::from_u8(entry_type) else {
        return 0;
    };
    let Ok(row) = buffer.append_log_interned(span_id, entry_type, message_ordinal, line, timestamp)
    else {
        return 0;
    };
    packed_row(span_id, row)
}

/// # Safety
/// `handle` must be a live uniquely owned handle.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_append_log_static(
    handle: *mut ThreadSpanBufferHandle,
    span_id: u32,
    entry_type: u8,
    message_id: u32,
    timestamp: i64,
    line: u32,
) -> u64 {
    let Some(buffer) = as_buffer(handle) else {
        return 0;
    };
    let Some(entry_type) = EntryType::from_u8(entry_type) else {
        return 0;
    };
    let Ok(message_id) = VocabularyId::try_from(message_id) else {
        return 0;
    };
    let Ok(row) = buffer.append_log_static(span_id, entry_type, message_id, line, timestamp) else {
        return 0;
    };
    packed_row(span_id, row)
}

/// # Safety
/// `handle` must be a live uniquely owned handle.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_append_log_dynamic(
    handle: *mut ThreadSpanBufferHandle,
    span_id: u32,
    entry_type: u8,
    message_ptr: *const u8,
    message_len: usize,
    timestamp: i64,
    line: u32,
) -> u64 {
    let Some(buffer) = as_buffer(handle) else {
        return 0;
    };
    let Some(entry_type) = EntryType::from_u8(entry_type) else {
        return 0;
    };
    let Some(message) = (unsafe { parse_text(message_ptr, message_len) }) else {
        return 0;
    };
    let Ok(row) = buffer.append_log(
        span_id,
        entry_type,
        Some(TextInput::Dynamic(message)),
        line,
        timestamp,
    ) else {
        return 0;
    };
    packed_row(span_id, row)
}

fn write_value(buffer: &mut ThreadSpanBuffer, row: u32, ordinal: u16, kind: u8, value: u64) -> u8 {
    let Some(value) = buffer.decode_abi_value(kind, value) else {
        return 1;
    };
    buffer.write_attr(row, ordinal, value).is_err() as u8
}

/// # Safety
/// `handle` must be a live uniquely owned handle.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_write_attr(
    handle: *mut ThreadSpanBufferHandle,
    row: u32,
    ordinal: u16,
    kind: u8,
    value: u64,
) -> u8 {
    let Some(buffer) = as_buffer(handle) else {
        return 1;
    };
    write_value(buffer, row, ordinal, kind, value)
}

/// # Safety
/// `handle` must be a live uniquely owned handle.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_write_tag(
    handle: *mut ThreadSpanBufferHandle,
    span_id: u32,
    ordinal: u16,
    kind: u8,
    value: u64,
) -> u8 {
    let Some(buffer) = as_buffer(handle) else {
        return 1;
    };
    let Some(row) = buffer
        .start_row(span_id)
        .and_then(|row| u32::try_from(row).ok())
    else {
        return 1;
    };
    write_value(buffer, row, ordinal, kind, value)
}

/// # Safety
/// `handle` must be a live uniquely owned handle.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_set_scope(
    handle: *mut ThreadSpanBufferHandle,
    span_id: u32,
    ordinal: u16,
    kind: u8,
    value: u64,
) -> u8 {
    let Some(buffer) = as_buffer(handle) else {
        return 1;
    };
    let Some(index) = usize::from(ordinal).checked_sub(crate::SYSTEM_COLUMN_COUNT) else {
        return 1;
    };
    let Some(field) = buffer.schema_fields().get(index) else {
        return 1;
    };
    let Some(value) = buffer.decode_abi_value(kind, value) else {
        return 1;
    };
    let scope_value = match value {
        ColumnValue::Number(value) => crate::ScopeValue::Number(value),
        ColumnValue::Uint64(value) => crate::ScopeValue::Uint64(value),
        ColumnValue::Boolean(value) => crate::ScopeValue::Boolean(value),
        ColumnValue::Enum(value) => crate::ScopeValue::EnumIndex(value),
        // A scope is shared between spans by refcount, so it cannot carry an
        // arena handle. The cold path takes one owned copy; rows re-intern it
        // into their own arena at materialization, which is a hash hit.
        ColumnValue::Text(ordinal) => {
            let Some(text) = buffer.interned(ordinal) else {
                return 1;
            };
            crate::ScopeValue::Text(std::borrow::Cow::Owned(text.to_owned()))
        }
    };
    let update = [(field.name, Some(scope_value))];
    buffer.set_scope(span_id, &update).is_err() as u8
}

/// Release every row and span on a handle, keeping its interned vocabulary.
///
/// Returns zero on success and nonzero when the handle is null.
///
/// # Safety
/// `handle` must be null or a live handle returned by a constructor and not
/// previously freed.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_reset(handle: *mut ThreadSpanBufferHandle) -> u8 {
    let Some(buffer) = as_buffer(handle) else {
        return 1;
    };
    buffer.reset();
    0
}

/// Complete a span with the caller's entry type.
///
/// The generic endpoint preserves the distinction between handled errors and
/// thrown exceptions that the end_ok/end_err pair cannot carry.
///
/// # Safety
/// `handle` must be a live uniquely owned handle.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_end(
    handle: *mut ThreadSpanBufferHandle,
    span_id: u32,
    entry_type: u8,
    timestamp: i64,
) -> u8 {
    let Some(buffer) = as_buffer(handle) else {
        return 1;
    };
    let Some(entry_type) = EntryType::from_u8(entry_type) else {
        return 1;
    };
    buffer.end(span_id, entry_type, timestamp).is_err() as u8
}

/// Store a span's terminal message on its reserved completion row.
/// # Safety
/// `handle` must be a live uniquely owned handle. The byte range must be
/// readable for the duration of this call; a null pointer is valid only with
/// zero length.
#[cfg_attr(not(target_family = "wasm"), unsafe(no_mangle))]
pub unsafe extern "C" fn thread_span_buffer_set_completion_message(
    handle: *mut ThreadSpanBufferHandle,
    span_id: u32,
    message_ptr: *const u8,
    message_len: usize,
) -> u8 {
    let Some(buffer) = as_buffer(handle) else {
        return 1;
    };
    let Some(message) = (unsafe { parse_text(message_ptr, message_len) }) else {
        return 1;
    };
    match buffer.set_completion_message(span_id, TextInput::Dynamic(message)) {
        Ok(()) => 0,
        Err(_) => 1,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ATTRIBUTE_KIND_NUMBER;
    use crate::columns::{FieldMeta, FieldStrategy};

    static FIELDS: &[FieldMeta] = &[FieldMeta::new("answer", FieldStrategy::Number)];

    fn bytes(value: &str) -> (*const u8, usize) {
        (value.as_ptr(), value.len())
    }

    #[test]
    fn scalar_abi_round_trip_and_parentage() {
        let handle =
            unsafe { thread_span_buffer_new_with_fields(7, 8, FIELDS.as_ptr(), FIELDS.len()) };
        assert!(!handle.is_null());
        let (trace, trace_len) = bytes("trace");
        let (name, name_len) = bytes("root");
        let name_id = unsafe { thread_span_buffer_intern(handle, name, name_len) };
        let parent =
            unsafe { thread_span_buffer_open_span(handle, trace, trace_len, 0, 0, name_id, 10, 1) };
        assert_ne!(parent, 0);
        let parent_id = (parent >> 32) as u32;
        assert_eq!(
            unsafe { thread_span_buffer_end_ok(handle, parent_id, 11) },
            0
        );
        let child = unsafe {
            thread_span_buffer_open_span(handle, trace, trace_len, 7, parent_id, name_id, 12, 2)
        };
        assert_ne!(child, 0);
        let child_id = (child >> 32) as u32;
        assert_eq!(
            unsafe {
                thread_span_buffer_write_tag(
                    handle,
                    child_id,
                    12,
                    ATTRIBUTE_KIND_NUMBER,
                    42.0f64.to_bits(),
                )
            },
            0
        );
        assert_eq!(
            unsafe { thread_span_buffer_end_ok(handle, child_id, 13) },
            0
        );
        unsafe { thread_span_buffer_free(handle) };
    }
}
