// Generated by cowshed-api-gen from cowshed-core declarations. Do not edit.
import type { tags } from 'typia';

/**
 * The commits a `--abandon` removal destroyed, and where their bundle went.
 *
 * Every field is what a reader needs to *undo* the abandonment: the tip that is gone, the branch
 * it never reached and where that branch stood, how much history went with it, and the bundle to
 * fetch from.
 */
export type AbandonedWork = {
  readonly head: GitOid;
  readonly targetBranch: string;
  readonly targetHead?: GitOid;
  readonly unlandedCommits: number & tags.Type<'uint64'>;
  readonly bundle: string;
};

export type AdmissionCommitment = {
  readonly version: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly order: number & tags.Type<'uint64'>;
  readonly repoId: RepoId;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly jobId: JobId;
  readonly grantRevision: number & tags.Type<'uint64'>;
};

export type AdoptOptions = {
  readonly path?: string;
  readonly repoId?: RepoId;
  readonly capacity?: string;
  readonly quarantine?: boolean;
};

export type AdoptRequest = {
  readonly repoId: RepoId;
  readonly options: AdoptOptions;
};

export type Adoption =
  | ({ readonly kind: 'adopted' } & {
      readonly elapsedMs: number & tags.Type<'uint64'>;
      readonly carried: NxCarry;
      readonly check: AdoptionCheck;
    })
  | ({ readonly kind: 'skipped' } & {
      readonly reason: AdoptionSkip;
    });

/**
 * Step 7: the landed check re-run in the target on the adopted volume. Every Nx task should hit.
 */
export type AdoptionCheck = {
  readonly hits: number & tags.Type<'uint64'>;
  /**
   * Each Nx task that missed: a defect in the project's build configuration.
   */
  readonly misses: ReadonlyArray<CacheMiss>;
  /**
   * Checks whose run summary was not theirs (Land step 7): counted neither as hits nor as
   * misses.
   */
  readonly unattributed: ReadonlyArray<UnattributedCheck>;
  /**
   * Checks that exited nonzero in the target.
   */
  readonly failed: ReadonlyArray<FailedCheck>;
};

export type AdoptionSkip =
  | { readonly kind: 'noLandingVolume' }
  | { readonly kind: 'noTargetVolume' }
  | ({ readonly kind: 'landingHeld' } & {
      readonly database: string;
      readonly holders: ReadonlyArray<DatabaseHolder>;
    })
  | ({ readonly kind: 'landingDaemonStayed' } & {
      readonly daemon: DatabaseHolder;
    })
  | ({ readonly kind: 'targetHeld' } & {
      readonly database: string;
      readonly holders: ReadonlyArray<DatabaseHolder>;
    })
  | ({ readonly kind: 'targetOpening' } & {
      readonly database: string;
      readonly holders: ReadonlyArray<DatabaseHolder>;
    })
  | ({ readonly kind: 'targetDaemonStayed' } & {
      readonly daemon: DatabaseHolder;
    })
  | ({ readonly kind: 'landingVolumeBusy' } & {
      readonly reason: string;
    });

export type AttachOptions = {
  readonly browse?: boolean;
  readonly observedPath?: string;
};

export type AuditDecision = 'allowed' | 'denied';

export type AuditEvent = {
  readonly timestamp: UtcTimestamp;
  readonly repoId: RepoId;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly workspace: WorkspaceName;
  readonly action: string;
  readonly decision: AuditDecision;
  readonly reason?: string;
  readonly trace: TraceContext;
};

/**
 * Exact, bounded bytes for control-oriented JSON.
 *
 * Valid UTF-8 is emitted as tagged UTF-8. Every other byte sequence is emitted as tagged
 * base64. The tag makes the wire representation unambiguous and deserialization never performs
 * lossy conversion.
 */
export type BinaryData = TaggedBytesRef;

export type BoundIdentity = {
  readonly repoId: RepoId;
  readonly remoteName: string | null;
  readonly remoteUrl: string | null;
  readonly primary: boolean;
};

export type BranchName = string;

/**
 * The identity of a cowshed build: the Mach-O `LC_UUID` the linker derives from the image's
 * contents on macOS, the SHA-256 of the executable elsewhere. Two binaries share one only when
 * they are the same build, so a supervisor started by another build — whatever changed, and
 * whether or not anybody remembered to say so — is refused by name at `hello` and drained by the
 * manager of a newly started daemon (11_shell.md "Draining a supervisor of another build").
 */
export type BuildId = string;

/**
 * The build volume a job would be granted, or `None` when the checkout links none. Always an
 * object: an RPC envelope carries no result for a bare `null`.
 */
export type BuildVolume = {
  readonly volume: string | null;
};

/**
 * One Nx task that missed the cache in the target after adoption, with the inputs Nx hashes
 * for it (`nx show target inputs`) and their digest.
 */
export type CacheMiss = {
  readonly task: string;
  readonly hash: string;
  /**
   * Each input category Nx reports (`files`, `environment`, `external`, …) and its entries;
   * empty when Nx could not name them, with `inputs_error` saying why.
   */
  readonly inputs: Readonly<Record<string, ReadonlyArray<string>>>;
  readonly inputsDigest: Sha256Digest;
  readonly inputsError?: string;
};

/**
 * One of the two volumes a rebase carry reads or writes.
 */
export type CarrySide = 'workspace' | 'target';

export type ChangeRepoIdRequest = {
  readonly repoId: RepoId;
  readonly newRepoId: RepoId;
};

export type CheckpointCommitment = {
  readonly version: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly order: number & tags.Type<'uint64'>;
  readonly repoId: RepoId;
  readonly originIncarnation: WorkspaceIncarnation;
  readonly checkpointId: string;
  readonly barrierId: number & tags.Type<'uint64'>;
  readonly manifestBatchSha256: Sha256Digest;
};

export type CheckpointInfo = {
  readonly label: string;
  readonly revision: number & tags.Type<'uint64'>;
  readonly pinned: boolean;
};

export type CheckpointOptions = {
  readonly label?: string;
  readonly keep?: boolean;
};

export type CheckpointQuota = {
  readonly maxCount: number & tags.Type<'uint32'>;
  readonly maxBytes: number & tags.Type<'uint64'>;
};

export type CheckpointRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly options: CheckpointOptions;
};

export type CheckpointResult = {
  readonly label: string;
};

/**
 * One immutable, byte-exact operating-system command argument.
 *
 * On Unix, serde preserves the bytes returned by `OsStrExt::as_bytes`: valid UTF-8 uses the
 * `utf8` tag and every other sequence uses canonical standard base64. No conversion is lossy.
 */
export type CommandArg = TaggedBytesRef;

/**
 * Versioned controller-owned existence, lifecycle, order, and lineage evidence.
 *
 * Protected payload bytes and artifact paths deliberately do not appear in any variant.
 */
export type ControllerCommitment = ControllerCommitmentRef;

export type ControllerCommitmentRef =
  | ({ readonly kind: 'workspaceIntroduced' } & WorkspaceIntroducedCommitment)
  | ({ readonly kind: 'workspaceRetired' } & WorkspaceRetiredCommitment)
  | ({ readonly kind: 'admission' } & AdmissionCommitment)
  | ({ readonly kind: 'terminal' } & TerminalCommitment)
  | ({ readonly kind: 'checkpoint' } & CheckpointCommitment)
  | ({ readonly kind: 'fork' } & ForkCommitment)
  | ({ readonly kind: 'restore' } & RestoreCommitment)
  | ({ readonly kind: 'landAdoption' } & LandAdoptionCommitment);

/**
 * An operational error with a concrete recovery command.
 */
export type CowshedError = {
  readonly code: ErrorCode;
  readonly message: string;
  readonly hint: string;
  /**
   * Present only on the daemon's refusal of another build's request. Absent from the wire
   * otherwise, and ignored by a build that predates it, so every other error reads as it did.
   * Boxed: every `Result` in cowshed carries this type, and the cause is rare.
   */
  readonly otherBuild?: OtherBuild;
  /**
   * Present only on the daemon's refusal of a workspace whose supervisor from before it
   * started it is still recovering; absent from the wire otherwise.
   */
  readonly recovering?: SupervisorRecovery;
  /**
   * Present only on the daemon's refusal of a request that depends on the mounts and sessions
   * its startup pass has not finished restoring; absent from the wire otherwise.
   */
  readonly healing?: StartupHeal;
  /**
   * Present only on a rebase or land refused at one of its fences, carrying the value the
   * fence observed, so a caller types the outcome without reading the repositories again.
   * Absent from the wire otherwise, like `otherBuild`.
   */
  readonly fence?: FenceRefusal;
  /**
   * Present only on a refusal that is safe to retry unchanged, naming why. Absent from the
   * wire otherwise, like `otherBuild`.
   */
  readonly retry?: Retry;
};

/**
 * CPU time in microseconds, cumulative from the start of whatever it counts: one process's own
 * user or system time, or a job's total from its accounting source.
 */
export type CpuMicros = number & tags.Type<'uint64'> & tags.Maximum<9007199254740991>;

export type CreateOptions = {
  readonly revision?: RevisionTarget;
  readonly fromWorkspace?: WorkspaceName;
  readonly browse?: boolean;
  readonly slot?: number & tags.Type<'uint32'>;
  /**
   * Also register this workspace as a remote in main's repository. Off by default: it is
   * host-side state that accumulates one entry per workspace and outlives an interrupted retire.
   */
  readonly register?: boolean;
  /**
   * Mint a registered linked worktree of main's repository instead of a standalone clone: one
   * object store and one ref namespace, at the cost of requiring main mounted and giving up
   * checkpoint and restore.
   */
  readonly gitWorktree?: boolean;
};

export type CreateRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly options: CreateOptions;
};

export type CredentialReport = {
  readonly routes: ReadonlyArray<CredentialRoute>;
};

/**
 * One approved gateway-backed registry route, as reported to an operator.
 *
 * Non-secret by construction: the origin and its scope, which environment variable names the
 * route was enrolled from and are therefore withheld from every child, and whether a usable
 * credential is installed. The secret is never read into this shape, not even to be discarded —
 * `installed` is the whole answer a report needs.
 */
export type CredentialRoute = {
  readonly repoId: RepoId;
  readonly origin: string;
  readonly pathPrefixes?: ReadonlyArray<string>;
  readonly withheldEnvNames?: ReadonlyArray<string>;
  readonly installed: boolean;
};

export type DatabaseHolder = {
  readonly pid: number & tags.Type<'int32'>;
  readonly command: string;
};

/**
 * What `cowshed defrag` changed: the image's extents before and after its data was rewritten
 * contiguously, and the data bytes the rewrite copied.
 */
export type DefragmentResult = {
  readonly workspace: WorkspaceName;
  readonly previousExtents: number & tags.Type<'uint64'>;
  readonly extents: number & tags.Type<'uint64'>;
  readonly bytes: number & tags.Type<'uint64'>;
};

export type DestroyRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly options: RemoveOptions;
};

export type DoctorReport = {
  readonly healthy: boolean;
  readonly findings: ReadonlyArray<Finding>;
};

export type EgressMode = 'intercept' | 'opaque';

export type EgressRule = {
  readonly host: string;
  readonly ports?: ReadonlyArray<number & tags.Type<'uint32'> & tags.Maximum<65535>>;
  readonly mode?: EgressMode;
};

export type EmptyResult = Readonly<Record<string, never>>;

/**
 * Stable cowshed outcome taxonomy shared by the core API and CLI.
 */
export type ErrorCode =
  | 'internal'
  | 'usage'
  | 'not-found'
  | 'conflict'
  | 'environment-missing'
  | 'sandbox-denied'
  | 'integrity';

/**
 * What a job runs.
 */
export type ExecCommand = { readonly argv: ReadonlyArray<CommandArg> } | { readonly script: ScriptCommand };

/**
 * One job admission: the worker fence, the session it runs in, exactly one of `argv` and
 * `script`, and the job's environment.
 */
export type ExecParams = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly session: string | null;
  readonly argv?: ReadonlyArray<CommandArg>;
  readonly script?: ScriptCommand;
  readonly cwd: WorkspacePath | null;
  readonly mode: RunSandboxMode;
  readonly env: Readonly<Record<string, string>>;
  readonly trace: TraceContext | null;
  readonly stdin: ExecStdin;
  readonly stdoutCopy: OutputPublication | null;
  readonly stderrCopy: OutputPublication | null;
};

export type ExecRecord = ExecRecordRef;

export type ExecRecordRef = {
  readonly repoId: RepoId;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly jobId: JobId;
  readonly state: JobState;
  readonly argv: ReadonlyArray<CommandArg>;
  readonly cwd: WorkspacePath;
  readonly envHash: number & tags.Type<'uint64'>;
  readonly grantRevision: number & tags.Type<'uint64'>;
  readonly trace: TraceContext;
  readonly started: UtcTimestamp;
  readonly durationMs: number & tags.Type<'uint64'>;
  readonly exit?: ExitStatus;
  readonly stdout: StreamInfo;
  readonly stderr: StreamInfo;
  readonly stdin: StdinInfo;
  readonly outputLimit?: OutputLimitInfo;
};

/**
 * Where an admitted job's stdin comes from. Inline bytes travel as the call's upload frame; a
 * stream's chunks follow admission as `worker.stdinChunk` calls.
 */
export type ExecStdin =
  | { readonly kind: 'empty' }
  | { readonly kind: 'inline' }
  | { readonly kind: 'stream' }
  | ({ readonly kind: 'workspaceFile' } & {
      readonly workspacePath: WorkspacePath;
    });

export type ExitStatus =
  | ({ readonly kind: 'exited' } & {
      readonly code: number & tags.Type<'int32'>;
    })
  | ({ readonly kind: 'signaled' } & {
      readonly signal: number & tags.Type<'int32'>;
      readonly coreDumped: boolean;
    });

export type ExpectedRefHead = { readonly missing: true } | { readonly oid: GitOid };

export type FailedCheck = {
  readonly check: string;
  readonly exit?: number & tags.Type<'int32'>;
};

/**
 * Why a rebase or land refused at one of its fences (02_workspaces.md), with what the fence
 * observed. Every variant is a `Conflict` that left the source workspace and the target as they
 * were; the observed value is what a caller would otherwise read back to decide its next move.
 * `IncarnationMoved` also types every other exact-incarnation refusal, and `SourceMoved` push's
 * source-head refusal: the same fence, wherever it stands.
 *
 * Fields are additive like [`OtherBuild`]'s; a reason a later build added decodes as no fence
 * (`CowshedError::fence_source` answers `None`) rather than losing the whole error.
 */
export type FenceRefusal =
  | ({ readonly reason: 'incarnationMoved' } & {
      readonly workspace: WorkspaceName;
      readonly observed: WorkspaceIncarnation;
    })
  | ({ readonly reason: 'sourceMoved' } & {
      readonly observed: GitOid;
    })
  | ({ readonly reason: 'ontoMoved' } & {
      readonly observed: GitOid;
    })
  | ({ readonly reason: 'targetMoved' } & {
      readonly observed: GitOid | null;
    })
  | ({ readonly reason: 'notFastForward' } & {
      readonly targetHead: GitOid;
    })
  | ({ readonly reason: 'targetNotCheckedOut' } & {
      readonly checkedOut: string | null;
    })
  | ({ readonly reason: 'sourceDirty' } & {
      readonly paths: ReadonlyArray<WorkspacePath>;
      readonly total: number & tags.Type<'uint64'>;
    })
  | ({ readonly reason: 'targetDirty' } & {
      readonly paths: ReadonlyArray<WorkspacePath>;
      readonly total: number & tags.Type<'uint64'>;
    })
  | ({ readonly reason: 'replayConflicted' } & {
      readonly rolledBackTo: GitOid;
    });

export type Finding = {
  readonly code: string;
  readonly severity: FindingSeverity;
  readonly message: string;
  readonly hint: string;
  readonly path?: string;
};

export type FindingSeverity = 'info' | 'warning' | 'error';

export type ForkCommitment = {
  readonly version: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly order: number & tags.Type<'uint64'>;
  readonly repoId: RepoId;
  readonly sourceIncarnation: WorkspaceIncarnation;
  readonly destinationIncarnation: WorkspaceIncarnation;
};

export type GatewayStatus = {
  /**
   * Whether launchd has the gateway agent loaded.
   */
  readonly installed: boolean;
  /**
   * Whether the control socket answered a status request.
   */
  readonly running: boolean;
  readonly socket: string;
  readonly cliVersion: string;
  readonly daemonVersion?: string;
  readonly activeWorkspaces: number & tags.Type<'uint64'>;
  /**
   * Why the answering daemon is draining. A draining daemon refuses every new session, so the
   * gateway is not healthy while this is present, however promptly its socket answers.
   */
  readonly drainCause?: string;
  /**
   * How far the answering daemon's startup pass has got while it still mounts projects and
   * restores their sessions. Its socket answers, but every command that needs a workspace is
   * refused until this is gone, so the gateway is not healthy yet.
   */
  readonly healing?: StartupHeal;
  /**
   * The workspace supervisors from before the answering daemon started that it is still
   * recovering. It serves meanwhile; only a command for one of their workspaces is refused.
   */
  readonly recovering?: SupervisorRecovery;
  /**
   * Present when the answering daemon runs other bytes than this CLI. Both report version
   * 0.1.0 across every build, so only the executables' contents can tell them apart.
   */
  readonly staleDaemon?: StaleDaemonBinary;
};

export type GcCandidate = {
  readonly identity: Sha256Digest;
  readonly path: string;
  readonly bytes: number & tags.Type<'uint64'>;
  readonly reason: GcReason;
};

/**
 * One candidate left for a later sweep, with the exact reason this run could not reclaim it.
 */
export type GcDeferred = {
  readonly path: string;
  readonly diagnostic: string;
};

export type GcOptions = {
  readonly dryRun?: boolean;
};

export type GcReason =
  | 'retiredWorkspace'
  | 'orphanStagingImage'
  | 'orphanStagingMetadata'
  | 'orphanStagingMount'
  | 'orphanSessionImage'
  | 'orphanMountpoint'
  | 'expiredCheckpoint'
  | 'unlinkedBuildVolume'
  | 'supersededSeed'
  | 'unrecordedBuildVolume';

export type GcReport = {
  readonly examined: number & tags.Type<'uint64'>;
  readonly reclaimed: number & tags.Type<'uint64'>;
  readonly retainedPinned: number & tags.Type<'uint64'>;
  /**
   * Staging entries an operation still holds the lifecycle lock for: not garbage yet.
   */
  readonly retainedActive: number & tags.Type<'uint64'>;
  readonly freedBytes: number & tags.Type<'uint64'>;
  readonly dryRun: boolean;
  readonly candidates: ReadonlyArray<GcCandidate>;
  readonly deferred: ReadonlyArray<GcDeferred>;
};

export type GcRequest = {
  readonly repoId: RepoId;
  readonly options: GcOptions;
};

export type GitOid = string & tags.Pattern<'^([0-9a-f]{40}|[0-9a-f]{64})$'>;

export type GitRef = string;

export type GrantDelta = {
  readonly read?: ReadonlyArray<string>;
  readonly write?: ReadonlyArray<string>;
  readonly denyWrite?: ReadonlyArray<string>;
  readonly deny?: ReadonlyArray<string>;
  readonly egress?: ReadonlyArray<EgressRule>;
  readonly repos?: ReadonlyArray<RepoRule>;
  readonly sim?: ReadonlyArray<SimVerb>;
  /**
   * macOS only: the minimum number of service ports the workspace's port block must hold,
   * excluding the gateway listener at its base. Growth is monotone: a count the block already
   * holds is a no-op on its own, and `revoke` refuses the field. The block grows into a
   * larger aligned block containing it when one is free; otherwise the workspace moves to a
   * larger disjoint block and keeps the old one reserved (`GrantSet::retained_port_blocks`)
   * until it retires, unless a later block contains it. Either
   * way growth needs an idle workspace: it is refused at once, never queued, while any job is
   * active, and the next exec starts under the new block's profile and environment. Linux has
   * no port block — each workspace's private loopback already holds the whole port space — so
   * it refuses the field rather than record a block.
   */
  readonly servicePorts?: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly expectedRevision?: number & tags.Type<'uint64'>;
};

export type GrantRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly delta: GrantDelta;
};

export type GrantSet = {
  readonly revision: number & tags.Type<'uint64'>;
  readonly portBlock?: PortBlock;
  /**
   * A relocated sandbox may have left services alive after its job concluded. Its
   * previous disjoint blocks remain this workspace's authority, never a sibling's.
   */
  readonly retainedPortBlocks?: ReadonlyArray<PortBlock>;
  readonly read: ReadonlyArray<string>;
  readonly write: ReadonlyArray<string>;
  /**
   * Paths within this workspace that no job may write, even when its mount is writable.
   */
  readonly denyWrite?: ReadonlyArray<string>;
  /**
   * Paths within this workspace that no job may read or write.
   */
  readonly deny?: ReadonlyArray<string>;
  readonly egress: ReadonlyArray<EgressRule>;
  readonly repos?: ReadonlyArray<RepoRule>;
  readonly sim: ReadonlyArray<SimVerb>;
};

/**
 * Online host cores, independent of the current process's affinity mask.
 */
export type HostCores = number & tags.Type<'uint32'> & tags.Minimum<1> & tags.Maximum<65535>;

/**
 * The host's one-minute run-queue load, never a missing observation filled with zero.
 */
export type HostLoad1 = number & tags.Minimum<0>;

export type HostLoadSample = {
  readonly load1: HostLoad1;
  readonly cores: HostCores;
};

/**
 * A project's repository identities after `cowshed identity add`: the project, whether the named
 * remote was newly bound, the identity it names, and every identity the binding now holds — each
 * one a URL workspaces fetch from the local clone.
 */
export type IdentityReport = {
  readonly repoId: RepoId;
  readonly added: boolean;
  readonly identity: BoundIdentity;
  readonly identities: ReadonlyArray<BoundIdentity>;
};

/**
 * Why a job failed when no command's own status explains it.
 */
export type JobFailure = 'scriptSyntax' | 'supervisorLost';

export type JobId = number & tags.Type<'uint64'> & tags.Minimum<1> & tags.Maximum<9007199254740991>;

export type JobInfo = JobInfoRef;

export type JobInfoRef = {
  readonly repoId: RepoId;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly jobId: JobId;
  readonly state: JobState;
  readonly pid?: number & tags.Type<'uint32'>;
  readonly grantRevision: number & tags.Type<'uint64'>;
  readonly cwd: WorkspacePath | null;
  readonly started: UtcTimestamp;
  readonly durationMs?: number & tags.Type<'uint64'>;
  readonly resources?: JobResourceSample;
  readonly exit?: ExitStatus;
  readonly stdout: StreamInfo;
  readonly stderr: StreamInfo;
  readonly trace: TraceContext;
  readonly outputLimit?: OutputLimitInfo;
  readonly stdin: StdinInfo;
  readonly failure?: JobFailure;
} & (
  | { readonly argv: ReadonlyArray<CommandArg>; readonly script?: never }
  | { readonly script: ScriptCommand; readonly argv?: never }
);

/**
 * A position in a job's two output journals: how many admitted bytes of each stream precede it.
 * A stream's admitted byte count is the cursor just past its end.
 */
export type JobJournalCursor = {
  readonly stdout: number & tags.Type<'uint64'>;
  readonly stderr: number & tags.Type<'uint64'>;
};

/**
 * One life of one process: the image it runs now (or ran last), its parent, and how it ended.
 */
export type JobProcessSample = {
  readonly pid: number & tags.Type<'uint32'>;
  /**
   * The parent's pid when this process was born: within the tree, the retained parent record;
   * for a root, the process outside the job that started it.
   */
  readonly ppid: number & tags.Type<'uint32'>;
  /**
   * The executable of the last observed exec; a child that has not exec'd runs its parent's.
   */
  readonly program: string;
  /**
   * The byte-exact argv of that exec.
   */
  readonly argv: ReadonlyArray<CommandArg>;
  readonly bornAt: UtcTimestamp;
  /**
   * Absent until the exit is observed.
   */
  readonly exit?: ProcessExit;
};

/**
 * Every process a job owned that its observer saw, the exited ones included, and whether the
 * observer saw all of them.
 */
export type JobProcessTree = {
  readonly jobId: JobId;
  readonly sampledAt: UtcTimestamp;
  /**
   * In the order their births were observed.
   */
  readonly processes: ReadonlyArray<JobProcessSample>;
  readonly coverage: ProcessCoverage;
};

export type JobRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly jobId: JobId;
};

/**
 * What a job's processes cost, observed at `sampled_at`. A sample exists only once the job owns
 * a process: its shell activation on a cold host, otherwise its command.
 */
export type JobResourceSample = {
  /**
   * The job sampled, retained so a standalone progress event or receipt keeps its identity.
   */
  readonly jobId: JobId;
  readonly sampledAt: UtcTimestamp;
  /**
   * `wall_us` in whole milliseconds.
   */
  readonly wallMs: WallMillis;
  /**
   * Elapsed since the first owned process spawned.
   */
  readonly wallUs: WallMicros;
  /**
   * The job's observed leader: the activation's while a cold host activates, then the
   * command's. Retained after it exits.
   */
  readonly leaderPid: number & tags.Type<'uint32'>;
  /**
   * The pid of every running process in the job's group, the leader's among them while it
   * runs: the complete membership, never a truncated one. Empty once nothing of the group runs.
   */
  readonly members: ReadonlyArray<number & tags.Type<'uint32'>>;
};

export type JobState = 'queued' | 'running' | 'exited' | 'signaled' | 'killed' | 'outputLimit' | 'failed';

/**
 * Which captured stream a log read walks.
 */
export type JobStream = 'stdout' | 'stderr';

/**
 * A bounded raw slice of each stream and the cursor that continues after it. A slice after a
 * cursor is the start of what follows it; the latest tail is the end of what was admitted.
 * `*Truncated` says admitted bytes of the window the request named lie outside the slice:
 * after it when a cursor named the start, before it for the latest tail.
 */
export type JobTail = {
  readonly stdout: BinaryData;
  readonly stderr: BinaryData;
  readonly next: JobJournalCursor;
  readonly stdoutTruncated: boolean;
  readonly stderrTruncated: boolean;
};

/**
 * How many bytes a tail returns per stream: at least one, at most 64 KiB.
 */
export type JobTailBytes = number & tags.Type<'uint32'> & tags.Minimum<1> & tags.Maximum<65536>;

/**
 * The bounds of one tail, applied to each stream on its own.
 */
export type JobTailLimits = {
  readonly bytesPerStream: JobTailBytes;
  readonly linesPerStream: number & tags.Type<'uint32'> & tags.Minimum<1>;
};

/**
 * One Nx task that missed the cache when a land re-ran its check in the target on the adopted
 * build volume (16_build_volumes.md, Land step 7): a defect in the project's build
 * configuration, recorded once per miss so a coordinator can turn each into fix work.
 */
export type LandAdoptionCommitment = {
  readonly version: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly order: number & tags.Type<'uint64'>;
  readonly repoId: RepoId;
  /**
   * The workspace that landed; its build volume is now the target's.
   */
  readonly landingIncarnation: WorkspaceIncarnation;
  readonly targetIncarnation: WorkspaceIncarnation;
  readonly landedHead: GitOid;
  /**
   * The Nx task id (`project:target`, or `project:target:configuration`).
   */
  readonly task: string;
  /**
   * The task hash Nx computed in the target.
   */
  readonly taskHash: string;
  /**
   * The digest of the task's hash inputs as `nx show target inputs` named them; the land
   * report carries the inputs themselves.
   */
  readonly inputsDigest: Sha256Digest;
};

/**
 * A land's build-volume steps: the landing workspace quiesced, the target's seed frozen from
 * its volume, the target adopting it, and the adoption checked (2b).
 */
export type LandBuildVolume = {
  /**
   * Whether the target's seed was frozen from the landing volume (step 5).
   */
  readonly seeded: boolean;
  readonly adoption: Adoption;
};

export type LandOptions = {
  readonly targetBranch?: string;
  readonly check?: ReadonlyArray<string>;
  readonly retire?: boolean;
  readonly pushOnly?: boolean;
  readonly expectedWorkspaceIncarnation?: WorkspaceIncarnation;
  readonly expectedSourceHead?: GitOid;
  readonly expectedTargetHead?: ExpectedRefHead;
};

export type LandReport = {
  readonly landedHead: GitOid;
  readonly targetBranch: string;
  readonly previousTargetHead?: GitOid;
  readonly targetWasCheckedOut: boolean;
  readonly retired: boolean;
  /**
   * What the land did with build volumes (16_build_volumes.md, Land steps 4–7).
   */
  readonly buildVolume: LandBuildVolume;
};

/**
 * A unit's land: the unit, what it lands into (main when absent), and its options.
 */
export type LandRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly into?: WorkspaceTarget;
  readonly options: LandOptions;
};

/**
 * Where a workspace's commits stand relative to the branch that outlives it.
 *
 * A sum rather than a struct of optionals so that "measured" and "could not measure" cannot be
 * confused by a reader or a script: there is no shape in which a count is absent but a verdict is
 * still available, and none in which the absence of a count reads as zero.
 */
export type LandingCommits =
  | ({ readonly state: 'measured' } & {
      readonly targetBranch: string;
      readonly targetHead: GitOid;
      /**
       * Commits whose content the target does not hold, by ancestry or by patch equivalence.
       * Zero is the only value that authorizes removing the workspace without `--abandon`.
       */
      readonly unlanded: number & tags.Type<'uint64'>;
      /**
       * Commits the target already holds the patch of, including ones that reached it by
       * squash-merge, cherry-pick, or a history rewrite rather than by ancestry.
       */
      readonly landed: number & tags.Type<'uint64'>;
      /**
       * Commits the target has that the workspace does not.
       */
      readonly behind: number & tags.Type<'uint64'>;
    })
  | ({ readonly state: 'indeterminate' } & {
      readonly reason: string;
    });

/**
 * The JSON half of a `job.logs` answer; the bytes follow as its raw-byte frame.
 */
export type LogsChunk = {
  readonly eof: boolean;
  readonly nextOffset: number & tags.Type<'uint64'>;
};

export type LogsRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly jobId: JobId;
  readonly stream: JobStream;
  readonly follow: boolean;
  readonly offset: number & tags.Type<'uint64'>;
};

export type MirrorInfo = {
  readonly url: string;
  readonly mirror: string;
};

export type MirrorRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly url: string;
};

export type MountResult = {
  readonly workspace: WorkspaceName;
  readonly mount: string;
  readonly baseCommit?: GitOid;
};

export type MoveCheckoutRequest = {
  readonly repoId: RepoId;
  readonly destination: string;
};

/**
 * Step 5: the Nx cache entries the target's previous volume indexed and the landing volume did
 * not, carried into the landing volume before the target adopted it (16_build_volumes.md,
 * "Carry"). Nx's entries are content-addressed, so another land's work stays a hit.
 */
export type NxCarry = {
  readonly entries: number & tags.Type<'uint64'>;
  /**
   * The bytes Nx recorded for those entries.
   */
  readonly bytes: number & tags.Type<'uint64'>;
  readonly elapsedMs: number & tags.Type<'uint64'>;
  /**
   * Why the carry stopped before every missing entry was carried. Each entry carried until
   * then is whole and indexed; the rest are misses the target rebuilds.
   */
  readonly stopped?: string;
};

/**
 * The daemon serves only its own build, and refused a request from another (11_shell.md
 * "hello"). A controller of the refused build can start nothing in a workspace from then on; a
 * controller of the daemon's build — the host's current `cowshed` once an install has started
 * its daemon — can. Unknown fields are ignored, so a later build may say more here without an
 * earlier one losing the error.
 */
export type OtherBuild = {
  /**
   * The build the daemon runs.
   */
  readonly daemon: BuildId;
  /**
   * The build the request named; `None` for a request that named none.
   */
  readonly caller?: BuildId;
};

export type OutputLimitInfo = {
  readonly limitBytes: number & tags.Type<'uint64'>;
  readonly crossingBytes: number & tags.Type<'uint64'>;
};

export type OutputPublication = {
  readonly path: WorkspacePath;
  readonly policy: PublicationPolicy;
};

export type OutputStorage =
  | ({ readonly kind: 'captured' } & {
      readonly artifact: ProtectedOutput;
    })
  | ({ readonly kind: 'redirect' } & {
      readonly source: WorkspacePath;
      readonly artifact: ProtectedOutput;
    });

export type OutputSummary = {
  readonly version: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly text: string;
  readonly truncated: boolean;
};

export type PortBlock = {
  readonly base: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly size: number & tags.Type<'uint32'> & tags.Maximum<65535>;
};

/**
 * Whether the tree holds every process the job owned. A gap is absorbing: once an observation
 * was missed, no later one makes the tree complete again.
 */
export type ProcessCoverage =
  | { readonly kind: 'complete' }
  | ({ readonly kind: 'gap' } & {
      readonly reason: ProcessCoverageGap;
    });

/**
 * The first observation the tree is known to lack.
 */
export type ProcessCoverageGap =
  | { readonly kind: 'eventsLost' }
  | ({ readonly kind: 'unobservedBirth' } & {
      readonly pid: number & tags.Type<'uint32'>;
    })
  | ({ readonly kind: 'unobservedExit' } & {
      readonly pid: number & tags.Type<'uint32'>;
    })
  | ({ readonly kind: 'uncountedFork' } & {
      readonly pid: number & tags.Type<'uint32'>;
    })
  | ({ readonly kind: 'unreadImage' } & {
      readonly pid: number & tags.Type<'uint32'>;
    })
  | ({ readonly kind: 'unreadFinalUsage' } & {
      readonly pid: number & tags.Type<'uint32'>;
    });

/**
 * How and when a process ended: the two are observed together, so neither exists alone.
 */
export type ProcessExit = {
  readonly status: ExitStatus;
  readonly exitedAt: UtcTimestamp;
};

/**
 * Why a process's storage I/O could not be read.
 */
export type ProcessIoUnavailable = 'notPermitted' | 'notAccounted';

/**
 * What one process has moved to and from storage, as its kernel's per-process source counts
 * it: macOS `ri_diskio_bytesread`/`ri_diskio_byteswritten`, the I/O the process issued to disk;
 * Linux `/proc/<pid>/io` `read_bytes`/`write_bytes`, reads it caused to be fetched from storage
 * and writes it dirtied for storage (at the time it dirtied them, not at writeback). Reads its
 * cache served count on neither.
 */
export type ProcessStorageIo =
  | ({ readonly kind: 'read' } & {
      readonly readBytes: StorageIoBytes;
      readonly writeBytes: StorageIoBytes;
    })
  | ({ readonly kind: 'unavailable' } & {
      readonly reason: ProcessIoUnavailable;
    });

/**
 * What one process has cost itself, as last read: never the usage of the children it waited
 * for, which the job's accounting source counts. Absent from a process whose counters were
 * never read, rather than zero.
 */
export type ProcessUsage = {
  readonly cpuUserUs: CpuMicros;
  readonly cpuSysUs: CpuMicros;
  /**
   * Whether its own CPU over the supervisor's last sample window was at least 1 % of one
   * core.
   */
  readonly busy: boolean;
  /**
   * What it holds resident now; zero once it has exited.
   */
  readonly rssBytes: ResidentBytes;
  /**
   * The most it was read holding: never another process's, nor the group's sum.
   */
  readonly rssPeakBytes: ResidentBytes;
  readonly io: ProcessStorageIo;
};

/**
 * A change to the project's standing policy: read grants, egress grants and
 * workspace-relative denies. A write allow stays per-workspace (`GrantDelta`).
 */
export type ProjectGrantDelta = {
  readonly read?: ReadonlyArray<string>;
  readonly denyWrite?: ReadonlyArray<string>;
  readonly deny?: ReadonlyArray<string>;
  readonly egress?: ReadonlyArray<EgressRule>;
  readonly expectedRevision?: number & tags.Type<'uint64'>;
};

export type ProjectGrantRequest = {
  readonly repoId: RepoId;
  readonly delta: ProjectGrantDelta;
};

/**
 * Policy every workspace of the project holds from its first supervisor launch.
 *
 * Reads, egress and workspace-relative denies are standing decisions. A standing write allow
 * would hand every workspace a shared writable tree outside its image; that stays per-workspace.
 */
export type ProjectGrants = {
  /**
   * Advanced by every change, never reset. A workspace's effective revision is its own plus
   * this one, so a project change reaches the gateway's strictly increasing session revision
   * and relaunches every supervisor exactly as a workspace grant change does.
   */
  readonly revision: number & tags.Type<'uint64'>;
  readonly read: ReadonlyArray<string>;
  readonly egress: ReadonlyArray<EgressRule>;
  /**
   * Workspace-relative paths forbidden to every job, including main's.
   */
  readonly denyWrite?: ReadonlyArray<string>;
  /**
   * Workspace-relative paths no job may read or write, including main's.
   */
  readonly deny?: ReadonlyArray<string>;
};

export type ProjectOpenRequest = {
  /**
   * Absolute, lexically normalized path inside the project.
   */
  readonly path: string;
};

/**
 * The bound project's identity. Its fields are the controller's own shared values, so answering
 * an open copies them once, into the wire form.
 */
export type ProjectOpened = {
  readonly repoId: RepoId;
  readonly binding: RepositoryBinding;
  readonly gitRoot: string;
  readonly storeRoot: string;
};

export type ProjectWorkspaces = {
  readonly repoId: RepoId;
  readonly workspaces: ReadonlyArray<WorkspaceInfo>;
};

export type ProtectedOutput =
  | ({ readonly kind: 'inline' } & {
      readonly data: BinaryData;
    })
  | ({ readonly kind: 'file' } & {
      readonly path: WorkspacePath;
    });

export type PublicationPolicy = 'createNew' | 'replace';

export type PushOptions = {
  /**
   * The workspace's local branch to preserve; `cowshed/<ws>` when absent.
   */
  readonly branch?: BranchName;
  readonly expectedWorkspaceIncarnation?: WorkspaceIncarnation;
  readonly expectedSourceHead?: GitOid;
  readonly expectedDestinationHead?: ExpectedRefHead;
};

export type PushReport = {
  readonly sourceHead: GitOid;
  readonly destinationRef: string;
  readonly previousDestinationHead?: GitOid;
};

export type PushRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly options: PushOptions;
};

export type QuotaRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly quota: CheckpointQuota;
};

/**
 * The rebase carry's outcome. The rebase itself has succeeded either way; a skip only leaves
 * the workspace to rebuild what its target already ran at the rebased tree.
 */
export type RebaseBuildVolume =
  | ({ readonly kind: 'carried' } & {
      readonly carried: NxCarry;
    })
  | ({ readonly kind: 'skipped' } & {
      readonly reason: RebaseCarrySkip;
    });

/**
 * Why a rebase carried nothing (16_build_volumes.md, "Rebase carry"): a side's Nx task
 * database had a writer other than the carry, or a side has no volume.
 */
export type RebaseCarrySkip =
  | { readonly kind: 'noWorkspaceVolume' }
  | { readonly kind: 'noTargetVolume' }
  | ({ readonly kind: 'held' } & {
      readonly side: CarrySide;
      readonly database: string;
      readonly holders: ReadonlyArray<DatabaseHolder>;
    })
  | ({ readonly kind: 'opening' } & {
      readonly side: CarrySide;
      readonly database: string;
      readonly holders: ReadonlyArray<DatabaseHolder>;
    })
  | ({ readonly kind: 'daemonStayed' } & {
      readonly side: CarrySide;
      readonly daemon: DatabaseHolder;
    })
  | ({ readonly kind: 'taskHashes' } & {
      /**
       * The root's Nx state directory (`<root>/.nx`), relative to the workspace.
       */
      readonly state: string;
      readonly reason: string;
    });

export type RebaseOptions = {
  readonly onto?: RevisionTarget;
  readonly expectedWorkspaceIncarnation?: WorkspaceIncarnation;
  readonly expectedSourceHead?: GitOid;
  readonly expectedOntoHead?: GitOid;
};

/**
 * What `cowshed rebase` did: the workspace's new head, and the Nx cache entries its target's
 * volume held that the workspace's volume took (16_build_volumes.md, "Rebase carry").
 */
export type RebaseReport = {
  readonly oid: GitOid;
  readonly buildVolume: RebaseBuildVolume;
};

/**
 * A unit's rebase: the unit, what it lands into (main when absent), and its options.
 */
export type RebaseRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly into?: WorkspaceTarget;
  readonly options: RebaseOptions;
};

/**
 * The answer to `cowshed rekey <ws>`: the rotated workspace identity.
 */
export type RekeyResult = {
  readonly workspace: string;
  readonly workspaceIncarnation: string;
  readonly revision: number & tags.Type<'uint64'>;
  /**
   * The consumed quarantine entry, when the quarantine path ran.
   */
  readonly tombstoneRemoved?: string;
};

/**
 * What `cowshed rm` is allowed to override.
 *
 * The two overrides are deliberately separate, because they authorize losses of different kinds.
 * `force` covers *transient* state — a dirty tree, an in-progress merge, a busy mount — none of
 * which is unrecoverable content. `abandon` is the only thing that authorizes destroying commits
 * the project's main branch does not contain, and it is spelled out in full for exactly that
 * reason: a script that reaches for `force` to get past a stuck workspace must not thereby
 * acquire the power to delete work that has no other home.
 */
export type RemoveOptions = {
  readonly force?: boolean;
  readonly restore?: boolean;
  readonly abandon?: boolean;
};

/**
 * Authorization for removing a whole adopted project (`Coordinator::remove_project`). `force` and
 * `abandon` mean for every session workspace what they mean for one (`RemoveOptions`); `abandon`
 * also authorizes deleting the abandon bundles in the project's trash, which are then the only
 * copy of those commits, and bundling main's unpreserved commits into the restored checkout.
 */
export type RemoveProjectOptions = {
  readonly force?: boolean;
  readonly abandon?: boolean;
};

/**
 * What removing a project did, in order: the session workspaces it retired, the collection
 * that reclaimed their images, the abandon bundles it deleted, and main's restore.
 */
export type RemoveProjectReport = {
  readonly removed: ReadonlyArray<RemovedWorkspace>;
  readonly collected: GcReport;
  readonly deletedBundles: ReadonlyArray<string>;
  readonly restored: RemoveReport;
};

export type RemoveProjectRequest = {
  readonly repoId: RepoId;
  readonly options: RemoveProjectOptions;
};

/**
 * What `cowshed rm` destroyed beyond the workspace image itself.
 *
 * `abandoned` is `None` for every removal whose commits the target branch already contained —
 * the ordinary case, where the image is the only thing that dies.
 */
export type RemoveReport = {
  readonly abandoned?: AbandonedWork;
};

/**
 * One session workspace a project removal retired, with what its removal destroyed.
 */
export type RemovedWorkspace = {
  readonly workspace: WorkspaceName;
  readonly report: RemoveReport;
};

/**
 * A canonical, machine-independent repository identity in `owner/repo` form. Shared, immutable
 * text: every controller request carries it, so a clone is a reference count, not a copy.
 */
export type RepoId = string;

export type RepoRequest = {
  readonly repoId: RepoId;
};

export type RepoRule = string;

export type RepositoryBinding = {
  readonly version: number & tags.Type<'uint32'>;
  readonly identities: ReadonlyArray<BoundIdentity>;
  readonly formerIdentities?: ReadonlyArray<RepoId>;
};

export type Reseed =
  | { readonly kind: 'noBuildVolume' }
  | { readonly kind: 'fresh' }
  | ({ readonly kind: 'reseeded' } & {
      readonly behindMs?: number & tags.Type<'uint64'>;
      readonly elapsedMs: number & tags.Type<'uint64'>;
    })
  | ({ readonly kind: 'skipped' } & {
      readonly behindMs?: number & tags.Type<'uint64'>;
      readonly reason: ReseedSkip;
    });

/**
 * What `cowshed reseed` did with a target's seed (16_build_volumes.md, "Targets and seeds").
 * Every fork of the target does the same before it clones the seed.
 */
export type ReseedResult = {
  readonly workspace: WorkspaceName;
  readonly outcome: Reseed;
};

export type ReseedSkip =
  | ({ readonly kind: 'held' } & {
      readonly database: string;
      readonly holders: ReadonlyArray<DatabaseHolder>;
    })
  | ({ readonly kind: 'daemonStayed' } & {
      readonly daemon: DatabaseHolder;
    })
  | ({ readonly kind: 'building' } & {
      readonly lock: string;
      readonly holders: ReadonlyArray<DatabaseHolder>;
    });

/**
 * Bytes of memory resident in RAM: what processes hold now, never memory charged to them
 * elsewhere (a cgroup's `memory.current` counts page cache and kernel charges too).
 */
export type ResidentBytes = number & tags.Type<'uint64'> & tags.Maximum<9007199254740991>;

export type ResizeRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly capacity: string;
  readonly volume: ResizeVolume;
};

/**
 * What `cowshed resize` changed, with both capacities as the image itself reports them.
 */
export type ResizeResult = {
  readonly workspace: WorkspaceName;
  readonly volume: ResizeVolume;
  readonly previousCapacity: string;
  readonly capacity: string;
};

/**
 * Which of a workspace's volumes `cowshed resize` grows: its image, or its build volume and the
 * workspace's seed with it (16_build_volumes.md, "Substrate").
 */
export type ResizeVolume = 'workspace' | 'build';

export type RestoreCommitment = {
  readonly version: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly order: number & tags.Type<'uint64'>;
  readonly repoId: RepoId;
  readonly sourceCheckpoint: string;
  readonly sourceIncarnation: WorkspaceIncarnation;
  readonly replacedIncarnation: WorkspaceIncarnation;
  readonly destinationIncarnation: WorkspaceIncarnation;
};

export type RestoreRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly label: string;
};

/**
 * Why a `Conflict` is safe to retry unchanged: the call planned against state a concurrent
 * operation changed before it acted, and changed nothing itself. Retrying is the remedy; no
 * other repair is needed.
 */
export type Retry = { readonly reason: 'gcPlanStale' };

export type RevisionTarget = { readonly branch: BranchName } | { readonly ref: GitRef } | { readonly oid: GitOid };

export type RunSandboxMode = 'readWrite' | 'readOnly';

/**
 * What the running sccache daemon reports about itself.
 *
 * Hits and misses are per language rather than summed: cross-workspace C and C++ reuse works
 * without any slot, so a healthy aggregate hit rate routinely hides a Rust hit rate of zero, which
 * is the number a slot host is actually managing. `base_directories` is reported because it is the
 * only observable proof that the server took `SCCACHE_BASEDIRS` — sccache 0.16 ignores the
 * singular `SCCACHE_BASEDIR` entirely, and silently.
 */
export type SccacheStats = {
  readonly maxCacheSize: number & tags.Type<'uint64'>;
  readonly baseDirectories: ReadonlyArray<string>;
  readonly compileRequests: number & tags.Type<'uint64'>;
  readonly requestsExecuted: number & tags.Type<'uint64'>;
  readonly hits: Readonly<Record<string, number & tags.Type<'uint64'>>>;
  readonly misses: Readonly<Record<string, number & tags.Type<'uint64'>>>;
};

/**
 * Health of the host-owned sccache LaunchAgent.
 *
 * `installed` is launchd's verdict (the job is loaded); `running` is the
 * socket's (a connect on the server unix socket was accepted). Both are
 * reported because the interesting failures are exactly the disagreements:
 * installed-but-unresponsive (crash-looping agent) and answering-but-
 * uninstalled (foreign server bound on the path).
 */
export type SccacheStatus = {
  readonly installed: boolean;
  readonly running: boolean;
  readonly socket: string;
  /**
   * The daemon's own counters, absent unless it answered a stats request.
   */
  readonly stats?: SccacheStats;
};

/**
 * A script as a template: literal shell text `parts` interleaved with `values`, exactly one
 * more part than values. Values never become shell text; each is substituted where it stands
 * as a whole word or as part of one (`crate::script`).
 */
export type ScriptCommand = {
  readonly parts: ReadonlyArray<string>;
  readonly values: ReadonlyArray<ScriptValue>;
};

/**
 * One value substituted into a script.
 */
export type ScriptValue = { readonly word: string } | { readonly words: ReadonlyArray<string> };

/**
 * A job's terminal record as the workspace's durable records hold it: what any supervisor of the
 * workspace incarnation answers for a job, including one an earlier supervisor ran and sealed —
 * which [`JobInfo`], whose start, cwd, trace and stdin only the running supervisor knew, cannot
 * describe once that supervisor is gone.
 */
export type SealedJob = {
  readonly jobId: JobId;
  readonly state: JobState;
  readonly exit: ExitStatus | null;
  readonly failure: JobFailure | null;
  readonly durationMs: (number & tags.Type<'uint64'>) | null;
  /**
   * The job's terminal resource sample, exactly as its last [`JobInfo::resources`]; absent
   * for a job that never owned a process.
   */
  readonly resources?: JobResourceSample;
  readonly outputLimit: OutputLimitInfo | null;
  readonly stdout: StreamInfo;
  readonly stderr: StreamInfo;
};

export type SessionRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly session: string | null;
};

/**
 * A fixed-width SHA-256 digest, serialized as 64 lowercase hexadecimal characters.
 */
export type Sha256Digest = string & tags.Pattern<'^[0-9a-f]{64}$'>;

export type SimVerb = 'openurl' | 'install';

export type SkillInstall = {
  readonly harness: string;
  readonly path: string;
  readonly status: SkillInstallStatus;
};

export type SkillInstallReport = {
  readonly skill: string;
  readonly installs: ReadonlyArray<SkillInstall>;
};

/**
 * Whether one skill install target was rewritten or already held the shipped bytes.
 *
 * The distinction is the idempotence proof: a second install of an unchanged skill
 * reports `Unchanged` for every target and touches no file.
 */
export type SkillInstallStatus = 'written' | 'unchanged';

export type SlotRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly slot: number & tags.Type<'uint32'>;
};

export type SlotResult = {
  readonly slot: number & tags.Type<'uint32'>;
};

export type SourceDestinationRequest = {
  readonly repoId: RepoId;
  readonly source: WorkspaceName;
  readonly destination: WorkspaceName;
};

export type SpanId = string & tags.Pattern<'^(?!0{16}$)[0-9a-f]{16}$'>;

/**
 * The daemon and CLI executables, when their contents differ.
 */
export type StaleDaemonBinary = {
  /**
   * SHA-256 of the daemon's executable, or `None` for a daemon too old to report it.
   */
  readonly daemonSha256?: string;
  /**
   * SHA-256 of the executable of the CLI that asked.
   */
  readonly cliSha256: string;
};

/**
 * Where the daemon's startup pass is (05_gateway.md "Startup contract"): mounting the recorded
 * projects, then restoring the attached workspaces' sessions from what it mounted.
 */
export type StartupHeal =
  | {
      readonly mounting: {
        readonly projects: number & tags.Type<'uint64'> & tags.Minimum<1>;
      };
    }
  | 'restoringSessions';

export type StdinInfo = {
  readonly kind: StdinKind;
  readonly bytes: number & tags.Type<'uint64'>;
  readonly workspacePath?: WorkspacePath;
  readonly complete: boolean;
};

export type StdinKind = 'empty' | 'inline' | 'stream' | 'workspaceFile';

/**
 * One lifecycle step of a controller call that asked for its steps, reported when the step starts
 * and again when it ends (`crate::timing`). Step ids are unique within the call. A step's
 * `parent` is the step it runs inside, absent at the call's top level, and is always reported
 * started before any step inside it; a step ends before its parent does.
 */
export type StepReport =
  | ({ readonly event: 'started' } & {
      readonly step: number & tags.Type<'uint32'>;
      readonly parent?: number & tags.Type<'uint32'>;
      /**
       * The verb or layer the step belongs to: `new`, `apfs`.
       */
      readonly scope: string;
      /**
       * The step within its scope: `links`, `canonical/mount`.
       */
      readonly name: string;
    })
  | ({ readonly event: 'ended' } & {
      readonly step: number & tags.Type<'uint32'>;
      /**
       * Why the step failed; absent when it succeeded.
       */
      readonly error?: string;
    });

/**
 * Bytes a kernel counted as moved to or from storage: never logical reads its cache served,
 * volume-allocation deltas, or operation counts converted into bytes.
 */
export type StorageIoBytes = number & tags.Type<'uint64'> & tags.Maximum<9007199254740991>;

export type StreamInfo = StreamInfoRef;

export type StreamInfoRef = {
  readonly storage: OutputStorage;
  readonly bytes: number & tags.Type<'uint64'>;
  readonly sha256: Sha256Digest;
  readonly summary: OutputSummary;
};

/**
 * The workspace supervisors that served before the daemon started and that it has not finished
 * recovering: not yet asked who they are, or, of another cowshed build, not yet answered `drain`.
 * Never zero — a daemon with nothing left to recover reports no recovery at all.
 */
export type SupervisorRecovery = {
  readonly supervisors: number & tags.Type<'uint64'> & tags.Minimum<1>;
};

export type TaggedBytesEncoding = 'utf8' | 'base64';

export type TaggedBytesRef = {
  readonly encoding: TaggedBytesEncoding;
  readonly data: string;
};

/**
 * A bounded tail of one job: after `cursor` when it is named, else the latest one.
 */
export type TailRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly jobId: JobId;
  /**
   * Absent for the latest tail; omitted from the wire, never `null`.
   */
  readonly cursor?: JobJournalCursor;
  readonly limits: JobTailLimits;
};

export type TerminalCommitment = {
  readonly version: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly order: number & tags.Type<'uint64'>;
  readonly repoId: RepoId;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly jobId: JobId;
  readonly state: JobState;
  readonly grantRevision: number & tags.Type<'uint64'>;
  readonly stdoutBytes: number & tags.Type<'uint64'>;
  readonly stdoutSha256: Sha256Digest;
  readonly stderrBytes: number & tags.Type<'uint64'>;
  readonly stderrSha256: Sha256Digest;
  readonly batchSha256: Sha256Digest;
  readonly outputLimit?: OutputLimitInfo;
};

export type TraceContext = {
  readonly traceId: TraceId;
  readonly spanId: SpanId;
};

export type TraceId = string & tags.Pattern<'^(?!0{32}$)[0-9a-f]{32}$'>;

/**
 * A landed check whose Nx run summary in one of the target's caches was not its own.
 */
export type UnattributedCheck = {
  readonly check: string;
  /**
   * The cache, as the checkout spells it (`.nx/cache`).
   */
  readonly cache: string;
  readonly reason: UnattributedRun;
};

/**
 * Why a run summary is not the check's own (16_build_volumes.md, Land step 7).
 */
export type UnattributedRun =
  | { readonly kind: 'noSummary' }
  | ({ readonly kind: 'unreadable' } & {
      readonly error: string;
    })
  | ({ readonly kind: 'beganBeforeCheck' } & {
      readonly start: string;
    })
  | ({ readonly kind: 'endedAfterCheck' } & {
      readonly end: string;
    })
  | ({ readonly kind: 'foreignCommand' } & {
      readonly command: string;
    })
  | ({ readonly kind: 'uncovered' } & {
      readonly targets: ReadonlyArray<string>;
    });

export type UtcTimestamp = string;

/**
 * Elapsed wall time since the job's first owned process spawned, in microseconds.
 */
export type WallMicros = number & tags.Type<'uint64'> & tags.Maximum<9007199254740991>;

/**
 * Elapsed wall time in whole milliseconds; only [`WallMicros::millis`] makes one.
 */
export type WallMillis = number & tags.Type<'uint64'> & tags.Maximum<9007199254740991>;

/**
 * One workspace incarnation: the fence every worker request carries.
 */
export type WorkerScope = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly workspaceIncarnation: WorkspaceIncarnation;
};

/**
 * The workspace a worker capability was minted for. The wire form is the [`WorkspaceView`]; the
 * type is what lets only the call that mints a worker capability yield one.
 */
export type WorkerView = WorkspaceView;

export type WorkspaceAtRequest = {
  readonly repoId: RepoId;
  readonly path: string;
};

export type WorkspaceAttachRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly options: AttachOptions;
};

/**
 * A workspace's grants: a coordinator names the workspace, a worker also proves the
 * incarnation its connection is fenced to.
 */
export type WorkspaceGrantsRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly workspaceIncarnation?: WorkspaceIncarnation;
};

/**
 * Shared, immutable text, cloned into every request a worker handle sends.
 */
export type WorkspaceIncarnation = string;

export type WorkspaceInfo = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
  readonly workspaceIncarnation: WorkspaceIncarnation;
  readonly role: WorkspaceRole;
  readonly mount: string;
  readonly state: WorkspaceState;
  readonly branch?: string;
  readonly baseCommit?: GitOid;
  readonly createdAt?: UtcTimestamp;
  readonly checkpoints: ReadonlyArray<CheckpointInfo>;
  readonly snapshotStale: boolean;
  /**
   * Filled in only for a caller that asked to pay for the measurement; absent everywhere else,
   * including in every controller response, so `default` is what keeps decoding those honest.
   */
  readonly landing?: WorkspaceLanding;
};

export type WorkspaceIntroducedCommitment = {
  readonly version: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly order: number & tags.Type<'uint64'>;
  readonly repoId: RepoId;
  readonly workspaceIncarnation: WorkspaceIncarnation;
};

/**
 * What a landing measurement found for one workspace.
 *
 * Present only when a caller asked for it: reading it costs one process per workspace, which a
 * default listing must not pay.
 */
export type WorkspaceLanding = {
  /**
   * Paths the working tree reports as added, changed, deleted, or untracked.
   *
   * `None` means the tree could not be read, which is a different fact from a clean tree and is
   * reported as a different fact. Measured independently of the target, because an uncommitted
   * tree is worth knowing about even when the target cannot be resolved.
   */
  readonly dirtyFiles?: number & tags.Type<'uint64'>;
  readonly commits: LandingCommits;
};

/**
 * Shared, immutable text: every request a handle sends carries its workspace, so a clone is a
 * reference count, not a copy.
 */
export type WorkspaceName = string;

export type WorkspacePath = string;

export type WorkspaceRequest = {
  readonly repoId: RepoId;
  readonly workspace: WorkspaceName;
};

export type WorkspaceRetiredCommitment = {
  readonly version: number & tags.Type<'uint32'> & tags.Maximum<65535>;
  readonly order: number & tags.Type<'uint64'>;
  readonly repoId: RepoId;
  readonly workspaceIncarnation: WorkspaceIncarnation;
};

export type WorkspaceRole = 'main' | 'workspace';

export type WorkspaceState = 'attached' | 'detached';

/**
 * The workspace a unit lands into, or rebases onto, with the incarnation it had when it was
 * resolved: a lane base, or main.
 *
 * Built only from a [`crate::WorkspaceRef`] ([`crate::WorkspaceRef::target`]), never from a name,
 * so a caller cannot aim a land at a workspace it did not resolve. The incarnation is what makes
 * that stick: a lane base removed and recreated under the same name is a different workspace,
 * and land and rebase refuse it rather than deliver into it.
 */
export type WorkspaceTarget = {
  readonly workspace: WorkspaceName;
  readonly incarnation: WorkspaceIncarnation;
};

/**
 * One workspace's information and grants, as one call resolved them.
 */
export type WorkspaceView = {
  readonly info: WorkspaceInfo;
  readonly grants: GrantSet;
};
