// Generated by cowshed-api-gen from cowshed-core's operation table. Do not edit.
/// <reference types="node" />

import type * as Api from './api.generated.js';
import {
  type EventIterator,
  eventIterator,
  type NativeJobHandle,
  type NativeWorkspaceHandle,
  type NativeWorkspaceRefHandle,
} from './native.js';
import * as V from './validators.generated.js';

/** A download's answer: its chunk's metadata as JSON, and the bytes it describes. */
export interface NativeDownload {
  readonly json: string;
  readonly bytes: Buffer;
}

/**
 * A stream-lane call's events: `next` sends one demand and resolves to the event that answers it,
 * as JSON, or to `null` once the call has ended; `close` ends the call, never what it observes, even
 * while a `next` waits, which then resolves to `null`.
 */
export interface NativeEvents {
  next(): Promise<string | null>;
  close(): Promise<void>;
}

/** The operations a `Project` serves: exactly those its authority admits. */
export interface NativeProjectOperations extends NativeProjectWorkspace, NativeProjectWorkspaceAt, NativeProjectList {}

/** The operations a `WorkspaceRef` serves: exactly those its authority admits. */
export interface NativeWorkspaceRefOperations
  extends NativeWorkspaceInfo,
    NativeWorkspaceAttach,
    NativeWorkspaceGrants,
    NativeWorkspaceBuildVolume {}

/** The operations a `Coordinator` serves: exactly those its authority admits. */
export interface NativeCoordinatorOperations
  extends NativeCoordinatorRename,
    NativeCoordinatorAdopt,
    NativeCoordinatorCreate,
    NativeCoordinatorFork,
    NativeCoordinatorMoveCheckout,
    NativeCoordinatorChangeRepoId,
    NativeCoordinatorGrant,
    NativeCoordinatorRevoke,
    NativeCoordinatorProjectGrants,
    NativeCoordinatorGrantProject,
    NativeCoordinatorRevokeProject,
    NativeCoordinatorRebase,
    NativeCoordinatorLand,
    NativeCoordinatorRestore,
    NativeCoordinatorResize,
    NativeCoordinatorDefragment,
    NativeCoordinatorReseed,
    NativeCoordinatorDetach,
    NativeCoordinatorAssignSlot,
    NativeCoordinatorDestroy,
    NativeCoordinatorGc,
    NativeCoordinatorRemoveProject,
    NativeCoordinatorRepoMirror,
    NativeCoordinatorSetCheckpointQuota,
    NativeCoordinatorDoctor,
    NativeCoordinatorWorker {}

/** The operations a `WorkspaceHandle` serves: exactly those its authority admits. */
export interface NativeWorkspaceHandleOperations
  extends NativeWorkspaceGrants,
    NativeWorkerExec,
    NativeWorkerStdinChunk,
    NativeWorkerStdinClose,
    NativeWorkerShell,
    NativeWorkerListJobs,
    NativeWorkerJob,
    NativeWorkerJobByKey,
    NativeWorkerCheckpoint,
    NativeWorkerPush,
    NativeSessionClose {}

/** The operations a `JobHandle` serves: exactly those its authority admits. */
export interface NativeJobHandleOperations
  extends NativeJobStatus,
    NativeJobSealed,
    NativeJobLogs,
    NativeJobTail,
    NativeJobListeningPorts,
    NativeJobProgress,
    NativeJobAttachWrite,
    NativeJobDetach,
    NativeJobWait,
    NativeJobKill {}

/** A handle that serves `coordinator.adopt`. */
export interface NativeCoordinatorAdopt {
  adopt(argumentsJson: string): Promise<NativeWorkspaceRefHandle>;
}

/** The request fields a `coordinator.adopt` caller names; its handle binds the rest. */
export type CoordinatorAdoptArguments = Pick<Api.AdoptRequest, 'options'>;

/**
 * Adopts the project's checkout as main.
 */
export async function coordinatorAdopt(
  handle: NativeCoordinatorAdopt,
  args: CoordinatorAdoptArguments,
): Promise<NativeWorkspaceRefHandle> {
  return handle.adopt(JSON.stringify(args));
}

/** A handle that serves `coordinator.assignSlot`. */
export interface NativeCoordinatorAssignSlot {
  assignSlot(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.assignSlot` caller names; its handle binds the rest. */
export type CoordinatorAssignSlotArguments = Pick<Api.SlotRequest, 'workspace' | 'slot'>;

/**
 * Assigns a workspace's gateway port slot.
 */
export async function coordinatorAssignSlot(
  handle: NativeCoordinatorAssignSlot,
  args: CoordinatorAssignSlotArguments,
): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(await handle.assignSlot(JSON.stringify(args)));
}

/** A handle that serves `coordinator.changeRepoId`. */
export interface NativeCoordinatorChangeRepoId {
  changeRepoId(argumentsJson: string): Promise<NativeWorkspaceRefHandle>;
}

/** The request fields a `coordinator.changeRepoId` caller names; its handle binds the rest. */
export type CoordinatorChangeRepoIdArguments = Pick<Api.ChangeRepoIdRequest, 'newRepoId'>;

/**
 * Changes the adopted project's repository identity.
 */
export async function coordinatorChangeRepoId(
  handle: NativeCoordinatorChangeRepoId,
  args: CoordinatorChangeRepoIdArguments,
): Promise<NativeWorkspaceRefHandle> {
  return handle.changeRepoId(JSON.stringify(args));
}

/** A handle that serves `coordinator.create`. */
export interface NativeCoordinatorCreate {
  create(argumentsJson: string): Promise<NativeWorkspaceRefHandle>;
}

/** The request fields a `coordinator.create` caller names; its handle binds the rest. */
export type CoordinatorCreateArguments = Pick<Api.CreateRequest, 'workspace' | 'options'>;

/**
 * Creates a session workspace from main.
 */
export async function coordinatorCreate(
  handle: NativeCoordinatorCreate,
  args: CoordinatorCreateArguments,
): Promise<NativeWorkspaceRefHandle> {
  return handle.create(JSON.stringify(args));
}

/** A handle that serves `coordinator.defragment`. */
export interface NativeCoordinatorDefragment {
  defragment(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.defragment` caller names; its handle binds the rest. */
export type CoordinatorDefragmentArguments = Pick<Api.WorkspaceRequest, 'workspace'>;

/**
 * Rewrites a workspace's image contiguously.
 */
export async function coordinatorDefragment(
  handle: NativeCoordinatorDefragment,
  args: CoordinatorDefragmentArguments,
): Promise<Api.DefragmentResult> {
  return V.parseDefragmentResult(await handle.defragment(JSON.stringify(args)));
}

/** A handle that serves `coordinator.destroy`. */
export interface NativeCoordinatorDestroy {
  destroy(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.destroy` caller names; its handle binds the rest. */
export type CoordinatorDestroyArguments = Pick<Api.DestroyRequest, 'workspace' | 'options'>;

/**
 * Destroys a session workspace.
 */
export async function coordinatorDestroy(
  handle: NativeCoordinatorDestroy,
  args: CoordinatorDestroyArguments,
): Promise<Api.RemoveReport> {
  return V.parseRemoveReport(await handle.destroy(JSON.stringify(args)));
}

/** A handle that serves `coordinator.detach`. */
export interface NativeCoordinatorDetach {
  detach(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.detach` caller names; its handle binds the rest. */
export type CoordinatorDetachArguments = Pick<Api.WorkspaceRequest, 'workspace'>;

/**
 * Detaches a workspace.
 */
export async function coordinatorDetach(
  handle: NativeCoordinatorDetach,
  args: CoordinatorDetachArguments,
): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(await handle.detach(JSON.stringify(args)));
}

/** A handle that serves `coordinator.doctor`. */
export interface NativeCoordinatorDoctor {
  doctor(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.doctor` caller names; its handle binds the rest. */
export type CoordinatorDoctorArguments = Readonly<Record<string, never>>;

/**
 * Reports the project's health findings.
 */
export async function coordinatorDoctor(
  handle: NativeCoordinatorDoctor,
  args: CoordinatorDoctorArguments,
): Promise<Api.DoctorReport> {
  return V.parseDoctorReport(await handle.doctor(JSON.stringify(args)));
}

/** A handle that serves `coordinator.fork`. */
export interface NativeCoordinatorFork {
  fork(argumentsJson: string): Promise<NativeWorkspaceRefHandle>;
}

/** The request fields a `coordinator.fork` caller names; its handle binds the rest. */
export type CoordinatorForkArguments = Pick<Api.SourceDestinationRequest, 'source' | 'destination'>;

/**
 * Forks a workspace into a new session workspace.
 */
export async function coordinatorFork(
  handle: NativeCoordinatorFork,
  args: CoordinatorForkArguments,
): Promise<NativeWorkspaceRefHandle> {
  return handle.fork(JSON.stringify(args));
}

/** A handle that serves `coordinator.gc`. */
export interface NativeCoordinatorGc {
  gc(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.gc` caller names; its handle binds the rest. */
export type CoordinatorGcArguments = Pick<Api.GcRequest, 'options'>;

/**
 * Collects unreferenced storage.
 */
export async function coordinatorGc(handle: NativeCoordinatorGc, args: CoordinatorGcArguments): Promise<Api.GcReport> {
  return V.parseGcReport(await handle.gc(JSON.stringify(args)));
}

/** A handle that serves `coordinator.grant`. */
export interface NativeCoordinatorGrant {
  grant(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.grant` caller names; its handle binds the rest. */
export type CoordinatorGrantArguments = Pick<Api.GrantRequest, 'workspace' | 'delta'>;

/**
 * Adds grants to one workspace.
 */
export async function coordinatorGrant(
  handle: NativeCoordinatorGrant,
  args: CoordinatorGrantArguments,
): Promise<Api.GrantSet> {
  return V.parseGrantSet(await handle.grant(JSON.stringify(args)));
}

/** A handle that serves `coordinator.grantProject`. */
export interface NativeCoordinatorGrantProject {
  grantProject(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.grantProject` caller names; its handle binds the rest. */
export type CoordinatorGrantProjectArguments = Pick<Api.ProjectGrantRequest, 'delta'>;

/**
 * Adds project-wide grants.
 */
export async function coordinatorGrantProject(
  handle: NativeCoordinatorGrantProject,
  args: CoordinatorGrantProjectArguments,
): Promise<Api.ProjectGrants> {
  return V.parseProjectGrants(await handle.grantProject(JSON.stringify(args)));
}

/** A handle that serves `coordinator.land`. */
export interface NativeCoordinatorLand {
  land(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.land` caller names; its handle binds the rest. */
export type CoordinatorLandArguments = Pick<Api.LandRequest, 'workspace' | 'into' | 'options'>;

/**
 * Lands a workspace into its target.
 */
export async function coordinatorLand(
  handle: NativeCoordinatorLand,
  args: CoordinatorLandArguments,
): Promise<Api.LandReport> {
  return V.parseLandReport(await handle.land(JSON.stringify(args)));
}

/** A handle that serves `coordinator.moveCheckout`. */
export interface NativeCoordinatorMoveCheckout {
  moveCheckout(argumentsJson: string): Promise<NativeWorkspaceRefHandle>;
}

/** The request fields a `coordinator.moveCheckout` caller names; its handle binds the rest. */
export type CoordinatorMoveCheckoutArguments = Pick<Api.MoveCheckoutRequest, 'destination'>;

/**
 * Moves the project's checkout.
 */
export async function coordinatorMoveCheckout(
  handle: NativeCoordinatorMoveCheckout,
  args: CoordinatorMoveCheckoutArguments,
): Promise<NativeWorkspaceRefHandle> {
  return handle.moveCheckout(JSON.stringify(args));
}

/** A handle that serves `coordinator.projectGrants`. */
export interface NativeCoordinatorProjectGrants {
  projectGrants(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.projectGrants` caller names; its handle binds the rest. */
export type CoordinatorProjectGrantsArguments = Readonly<Record<string, never>>;

/**
 * Reads the project's standing grants.
 */
export async function coordinatorProjectGrants(
  handle: NativeCoordinatorProjectGrants,
  args: CoordinatorProjectGrantsArguments,
): Promise<Api.ProjectGrants> {
  return V.parseProjectGrants(await handle.projectGrants(JSON.stringify(args)));
}

/** A handle that serves `coordinator.rebase`. */
export interface NativeCoordinatorRebase {
  rebase(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.rebase` caller names; its handle binds the rest. */
export type CoordinatorRebaseArguments = Pick<Api.RebaseRequest, 'workspace' | 'into' | 'options'>;

/**
 * Rebases a workspace onto what it lands into.
 */
export async function coordinatorRebase(
  handle: NativeCoordinatorRebase,
  args: CoordinatorRebaseArguments,
): Promise<Api.RebaseReport> {
  return V.parseRebaseReport(await handle.rebase(JSON.stringify(args)));
}

/** A handle that serves `coordinator.removeProject`. */
export interface NativeCoordinatorRemoveProject {
  removeProject(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.removeProject` caller names; its handle binds the rest. */
export type CoordinatorRemoveProjectArguments = Pick<Api.RemoveProjectRequest, 'options'>;

/**
 * Removes the adopted project end to end.
 */
export async function coordinatorRemoveProject(
  handle: NativeCoordinatorRemoveProject,
  args: CoordinatorRemoveProjectArguments,
): Promise<Api.RemoveProjectReport> {
  return V.parseRemoveProjectReport(await handle.removeProject(JSON.stringify(args)));
}

/** A handle that serves `coordinator.rename`. */
export interface NativeCoordinatorRename {
  rename(argumentsJson: string): Promise<NativeWorkspaceRefHandle>;
}

/** The request fields a `coordinator.rename` caller names; its handle binds the rest. */
export type CoordinatorRenameArguments = Pick<Api.SourceDestinationRequest, 'source' | 'destination'>;

/**
 * Renames a session workspace.
 */
export async function coordinatorRename(
  handle: NativeCoordinatorRename,
  args: CoordinatorRenameArguments,
): Promise<NativeWorkspaceRefHandle> {
  return handle.rename(JSON.stringify(args));
}

/** A handle that serves `coordinator.repoMirror`. */
export interface NativeCoordinatorRepoMirror {
  repoMirror(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.repoMirror` caller names; its handle binds the rest. */
export type CoordinatorRepoMirrorArguments = Pick<Api.MirrorRequest, 'workspace' | 'url'>;

/**
 * Points a workspace's repository mirror at a URL.
 */
export async function coordinatorRepoMirror(
  handle: NativeCoordinatorRepoMirror,
  args: CoordinatorRepoMirrorArguments,
): Promise<Api.MirrorInfo> {
  return V.parseMirrorInfo(await handle.repoMirror(JSON.stringify(args)));
}

/** A handle that serves `coordinator.reseed`. */
export interface NativeCoordinatorReseed {
  reseed(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.reseed` caller names; its handle binds the rest. */
export type CoordinatorReseedArguments = Pick<Api.WorkspaceRequest, 'workspace'>;

/**
 * Refreezes a target's seed from its live build volume.
 */
export async function coordinatorReseed(
  handle: NativeCoordinatorReseed,
  args: CoordinatorReseedArguments,
): Promise<Api.ReseedResult> {
  return V.parseReseedResult(await handle.reseed(JSON.stringify(args)));
}

/** A handle that serves `coordinator.resize`. */
export interface NativeCoordinatorResize {
  resize(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.resize` caller names; its handle binds the rest. */
export type CoordinatorResizeArguments = Pick<Api.ResizeRequest, 'workspace' | 'capacity' | 'volume'>;

/**
 * Grows a workspace's image or build volume.
 */
export async function coordinatorResize(
  handle: NativeCoordinatorResize,
  args: CoordinatorResizeArguments,
): Promise<Api.ResizeResult> {
  return V.parseResizeResult(await handle.resize(JSON.stringify(args)));
}

/** A handle that serves `coordinator.restore`. */
export interface NativeCoordinatorRestore {
  restore(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.restore` caller names; its handle binds the rest. */
export type CoordinatorRestoreArguments = Pick<Api.RestoreRequest, 'workspace' | 'label'>;

/**
 * Restores a workspace to a checkpoint.
 */
export async function coordinatorRestore(
  handle: NativeCoordinatorRestore,
  args: CoordinatorRestoreArguments,
): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(await handle.restore(JSON.stringify(args)));
}

/** A handle that serves `coordinator.revoke`. */
export interface NativeCoordinatorRevoke {
  revoke(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.revoke` caller names; its handle binds the rest. */
export type CoordinatorRevokeArguments = Pick<Api.GrantRequest, 'workspace' | 'delta'>;

/**
 * Removes grants from one workspace.
 */
export async function coordinatorRevoke(
  handle: NativeCoordinatorRevoke,
  args: CoordinatorRevokeArguments,
): Promise<Api.GrantSet> {
  return V.parseGrantSet(await handle.revoke(JSON.stringify(args)));
}

/** A handle that serves `coordinator.revokeProject`. */
export interface NativeCoordinatorRevokeProject {
  revokeProject(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.revokeProject` caller names; its handle binds the rest. */
export type CoordinatorRevokeProjectArguments = Pick<Api.ProjectGrantRequest, 'delta'>;

/**
 * Removes project-wide grants.
 */
export async function coordinatorRevokeProject(
  handle: NativeCoordinatorRevokeProject,
  args: CoordinatorRevokeProjectArguments,
): Promise<Api.ProjectGrants> {
  return V.parseProjectGrants(await handle.revokeProject(JSON.stringify(args)));
}

/** A handle that serves `coordinator.setCheckpointQuota`. */
export interface NativeCoordinatorSetCheckpointQuota {
  setCheckpointQuota(argumentsJson: string): Promise<string>;
}

/** The request fields a `coordinator.setCheckpointQuota` caller names; its handle binds the rest. */
export type CoordinatorSetCheckpointQuotaArguments = Pick<Api.QuotaRequest, 'workspace' | 'quota'>;

/**
 * Sets a workspace's checkpoint quota.
 */
export async function coordinatorSetCheckpointQuota(
  handle: NativeCoordinatorSetCheckpointQuota,
  args: CoordinatorSetCheckpointQuotaArguments,
): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(await handle.setCheckpointQuota(JSON.stringify(args)));
}

/** A handle that serves `coordinator.worker`. */
export interface NativeCoordinatorWorker {
  worker(argumentsJson: string): Promise<NativeWorkspaceHandle>;
}

/** The request fields a `coordinator.worker` caller names; its handle binds the rest. */
export type CoordinatorWorkerArguments = Pick<Api.WorkspaceRequest, 'workspace'>;

/**
 * Mints a worker capability for one workspace.
 */
export async function coordinatorWorker(
  handle: NativeCoordinatorWorker,
  args: CoordinatorWorkerArguments,
): Promise<NativeWorkspaceHandle> {
  return handle.worker(JSON.stringify(args));
}

/** A handle that serves `job.attachWrite`. */
export interface NativeJobAttachWrite {
  attachWrite(argumentsJson: string, bytes?: Buffer): Promise<string>;
}

/** The request fields a `job.attachWrite` caller names; its handle binds the rest. */
export type JobAttachWriteArguments = Readonly<Record<string, never>>;

/**
 * Writes to an attached job's stdin.
 */
export async function jobAttachWrite(
  handle: NativeJobAttachWrite,
  args: JobAttachWriteArguments,
  bytes?: Uint8Array,
): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(
    await handle.attachWrite(
      JSON.stringify(args),
      bytes === undefined ? undefined : Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength),
    ),
  );
}

/** A handle that serves `job.detach`. */
export interface NativeJobDetach {
  detach(argumentsJson: string): Promise<string>;
}

/** The request fields a `job.detach` caller names; its handle binds the rest. */
export type JobDetachArguments = Readonly<Record<string, never>>;

/**
 * Detaches from a job.
 */
export async function jobDetach(handle: NativeJobDetach, args: JobDetachArguments): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(await handle.detach(JSON.stringify(args)));
}

/** A handle that serves `job.kill`. */
export interface NativeJobKill {
  kill(argumentsJson: string): Promise<string>;
}

/** The request fields a `job.kill` caller names; its handle binds the rest. */
export type JobKillArguments = Readonly<Record<string, never>>;

/**
 * Kills a job's complete process group.
 */
export async function jobKill(handle: NativeJobKill, args: JobKillArguments): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(await handle.kill(JSON.stringify(args)));
}

/** A handle that serves `job.listeningPorts`. */
export interface NativeJobListeningPorts {
  listeningPorts(argumentsJson: string): Promise<string>;
}

/** The request fields a `job.listeningPorts` caller names; its handle binds the rest. */
export type JobListeningPortsArguments = Readonly<Record<string, never>>;

/**
 * Reads the TCP ports the job's process group listens on, from the kernel.
 */
export async function jobListeningPorts(
  handle: NativeJobListeningPorts,
  args: JobListeningPortsArguments,
): Promise<Api.JobListeningPorts> {
  return V.parseJobListeningPorts(await handle.listeningPorts(JSON.stringify(args)));
}

/** A handle that serves `job.logs`. */
export interface NativeJobLogs {
  logs(argumentsJson: string): Promise<NativeDownload>;
}

/** The request fields a `job.logs` caller names; its handle binds the rest. */
export type JobLogsArguments = Pick<Api.LogsRequest, 'stream' | 'follow' | 'offset'>;

/**
 * Reads one bounded raw chunk from an offset. Without follow, an empty chunk is the current
 * written end even when eof is false; follow waits on supervisor output notifications.
 */
export async function jobLogs(
  handle: NativeJobLogs,
  args: JobLogsArguments,
): Promise<Api.LogsChunk & { readonly bytes: Uint8Array }> {
  const answer = await handle.logs(JSON.stringify(args));
  return { ...V.parseLogsChunk(answer.json), bytes: answer.bytes };
}

/** A handle that serves `job.progress`. */
export interface NativeJobProgress {
  progress(argumentsJson: string): Promise<NativeEvents>;
}

/** The request fields a `job.progress` caller names; its handle binds the rest. */
export type JobProgressArguments = Pick<Api.ProgressRequest, 'everyMs'>;

/**
 * Streams one job's resource samples: the latest at once, one every interval while it runs,
 * then its terminal sample once.
 */
export function jobProgress(
  handle: NativeJobProgress,
  args: JobProgressArguments,
): EventIterator<Api.JobResourceSample> {
  return eventIterator(() => handle.progress(JSON.stringify(args)), V.parseJobResourceSample);
}

/** A handle that serves `job.sealed`. */
export interface NativeJobSealed {
  sealed(argumentsJson: string): Promise<string>;
}

/** The request fields a `job.sealed` caller names; its handle binds the rest. */
export type JobSealedArguments = Readonly<Record<string, never>>;

/**
 * Reads one ended job's sealed record.
 */
export async function jobSealed(handle: NativeJobSealed, args: JobSealedArguments): Promise<Api.SealedJob> {
  return V.parseSealedJob(await handle.sealed(JSON.stringify(args)));
}

/** A handle that serves `job.status`. */
export interface NativeJobStatus {
  status(argumentsJson: string): Promise<string>;
}

/** The request fields a `job.status` caller names; its handle binds the rest. */
export type JobStatusArguments = Readonly<Record<string, never>>;

/**
 * Reads one job's status.
 */
export async function jobStatus(handle: NativeJobStatus, args: JobStatusArguments): Promise<Api.JobInfo> {
  return V.parseJobInfo(await handle.status(JSON.stringify(args)));
}

/** A handle that serves `job.tail`. */
export interface NativeJobTail {
  tail(argumentsJson: string): Promise<string>;
}

/** The request fields a `job.tail` caller names; its handle binds the rest. */
export type JobTailArguments = Pick<Api.TailRequest, 'cursor' | 'limits'>;

/**
 * Reads a bounded slice of both streams after a cursor, or their latest bounded tail.
 */
export async function jobTail(handle: NativeJobTail, args: JobTailArguments): Promise<Api.JobTail> {
  return V.parseJobTail(await handle.tail(JSON.stringify(args)));
}

/** A handle that serves `job.wait`. */
export interface NativeJobWait {
  wait(argumentsJson: string): Promise<string>;
}

/** The request fields a `job.wait` caller names; its handle binds the rest. */
export type JobWaitArguments = Readonly<Record<string, never>>;

/**
 * Waits for a job to end.
 */
export async function jobWait(handle: NativeJobWait, args: JobWaitArguments): Promise<Api.JobInfo> {
  return V.parseJobInfo(await handle.wait(JSON.stringify(args)));
}

/** A handle that serves `project.list`. */
export interface NativeProjectList {
  list(argumentsJson: string): Promise<string>;
}

/** The request fields a `project.list` caller names; its handle binds the rest. */
export type ProjectListArguments = Readonly<Record<string, never>>;

/**
 * Lists every published workspace.
 */
export async function projectList(
  handle: NativeProjectList,
  args: ProjectListArguments,
): Promise<readonly Api.WorkspaceView[]> {
  return V.parseWorkspaceViewList(await handle.list(JSON.stringify(args)));
}

/** A handle that serves `project.workspace`. */
export interface NativeProjectWorkspace {
  workspace(argumentsJson: string): Promise<NativeWorkspaceRefHandle>;
}

/** The request fields a `project.workspace` caller names; its handle binds the rest. */
export type ProjectWorkspaceArguments = Pick<Api.WorkspaceRequest, 'workspace'>;

/**
 * Resolves one workspace by name.
 */
export async function projectWorkspace(
  handle: NativeProjectWorkspace,
  args: ProjectWorkspaceArguments,
): Promise<NativeWorkspaceRefHandle> {
  return handle.workspace(JSON.stringify(args));
}

/** A handle that serves `project.workspaceAt`. */
export interface NativeProjectWorkspaceAt {
  workspaceAt(argumentsJson: string): Promise<NativeWorkspaceRefHandle>;
}

/** The request fields a `project.workspaceAt` caller names; its handle binds the rest. */
export type ProjectWorkspaceAtArguments = Pick<Api.WorkspaceAtRequest, 'path'>;

/**
 * Resolves the workspace an existing path belongs to.
 */
export async function projectWorkspaceAt(
  handle: NativeProjectWorkspaceAt,
  args: ProjectWorkspaceAtArguments,
): Promise<NativeWorkspaceRefHandle> {
  return handle.workspaceAt(JSON.stringify(args));
}

/** A handle that serves `session.close`. */
export interface NativeSessionClose {
  close(argumentsJson: string): Promise<string>;
}

/** The request fields a `session.close` caller names; its handle binds the rest. */
export type SessionCloseArguments = Pick<Api.SessionRequest, 'session'>;

/**
 * Closes a shell session.
 */
export async function sessionClose(handle: NativeSessionClose, args: SessionCloseArguments): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(await handle.close(JSON.stringify(args)));
}

/** A handle that serves `worker.checkpoint`. */
export interface NativeWorkerCheckpoint {
  checkpoint(argumentsJson: string): Promise<string>;
}

/** The request fields a `worker.checkpoint` caller names; its handle binds the rest. */
export type WorkerCheckpointArguments = Pick<Api.CheckpointRequest, 'options'>;

/**
 * Takes a checkpoint.
 */
export async function workerCheckpoint(
  handle: NativeWorkerCheckpoint,
  args: WorkerCheckpointArguments,
): Promise<Api.CheckpointResult> {
  return V.parseCheckpointResult(await handle.checkpoint(JSON.stringify(args)));
}

/** A handle that serves `worker.exec`. */
export interface NativeWorkerExec {
  exec(argumentsJson: string, bytes?: Buffer): Promise<NativeJobHandle>;
}

/** The request fields a `worker.exec` caller names; its handle binds the rest. */
export type WorkerExecArguments = Pick<
  Api.ExecParams,
  | 'session'
  | 'argv'
  | 'script'
  | 'cwd'
  | 'mode'
  | 'env'
  | 'trace'
  | 'stdin'
  | 'stdoutCopy'
  | 'stderrCopy'
  | 'admissionKey'
>;

/**
 * Admits one job; inline stdin travels as the upload frame.
 */
export async function workerExec(
  handle: NativeWorkerExec,
  args: WorkerExecArguments,
  bytes?: Uint8Array,
): Promise<NativeJobHandle> {
  return handle.exec(
    JSON.stringify(args),
    bytes === undefined ? undefined : Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength),
  );
}

/** A handle that serves `worker.job`. */
export interface NativeWorkerJob {
  job(argumentsJson: string): Promise<NativeJobHandle>;
}

/** The request fields a `worker.job` caller names; its handle binds the rest. */
export type WorkerJobArguments = Pick<Api.JobRequest, 'jobId'>;

/**
 * Resolves one job.
 */
export async function workerJob(handle: NativeWorkerJob, args: WorkerJobArguments): Promise<NativeJobHandle> {
  return handle.job(JSON.stringify(args));
}

/** A handle that serves `worker.jobByKey`. */
export interface NativeWorkerJobByKey {
  jobByKey(argumentsJson: string): Promise<NativeJobHandle>;
}

/** The request fields a `worker.jobByKey` caller names; its handle binds the rest. */
export type WorkerJobByKeyArguments = Pick<Api.AdmissionKeyRequest, 'admissionKey'>;

/**
 * Names the job an admission key admitted in the workspace incarnation: the job whose exec
 * reply was lost.
 */
export async function workerJobByKey(
  handle: NativeWorkerJobByKey,
  args: WorkerJobByKeyArguments,
): Promise<NativeJobHandle> {
  return handle.jobByKey(JSON.stringify(args));
}

/** A handle that serves `worker.listJobs`. */
export interface NativeWorkerListJobs {
  listJobs(argumentsJson: string): Promise<string>;
}

/** The request fields a `worker.listJobs` caller names; its handle binds the rest. */
export type WorkerListJobsArguments = Readonly<Record<string, never>>;

/**
 * Lists the workspace incarnation's jobs.
 */
export async function workerListJobs(
  handle: NativeWorkerListJobs,
  args: WorkerListJobsArguments,
): Promise<readonly Api.JobInfo[]> {
  return V.parseJobInfoList(await handle.listJobs(JSON.stringify(args)));
}

/** A handle that serves `worker.push`. */
export interface NativeWorkerPush {
  push(argumentsJson: string): Promise<string>;
}

/** The request fields a `worker.push` caller names; its handle binds the rest. */
export type WorkerPushArguments = Pick<Api.PushRequest, 'options'>;

/**
 * Pushes the workspace's branch.
 */
export async function workerPush(handle: NativeWorkerPush, args: WorkerPushArguments): Promise<Api.PushReport> {
  return V.parsePushReport(await handle.push(JSON.stringify(args)));
}

/** A handle that serves `worker.shell`. */
export interface NativeWorkerShell {
  shell(argumentsJson: string): Promise<string>;
}

/** The request fields a `worker.shell` caller names; its handle binds the rest. */
export type WorkerShellArguments = Pick<Api.SessionRequest, 'session'>;

/**
 * Opens a shell session.
 */
export async function workerShell(handle: NativeWorkerShell, args: WorkerShellArguments): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(await handle.shell(JSON.stringify(args)));
}

/** A handle that serves `worker.stdinChunk`. */
export interface NativeWorkerStdinChunk {
  stdinChunk(argumentsJson: string, bytes?: Buffer): Promise<string>;
}

/** The request fields a `worker.stdinChunk` caller names; its handle binds the rest. */
export type WorkerStdinChunkArguments = Pick<Api.JobRequest, 'jobId'>;

/**
 * Writes one chunk of a streamed stdin.
 */
export async function workerStdinChunk(
  handle: NativeWorkerStdinChunk,
  args: WorkerStdinChunkArguments,
  bytes?: Uint8Array,
): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(
    await handle.stdinChunk(
      JSON.stringify(args),
      bytes === undefined ? undefined : Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength),
    ),
  );
}

/** A handle that serves `worker.stdinClose`. */
export interface NativeWorkerStdinClose {
  stdinClose(argumentsJson: string): Promise<string>;
}

/** The request fields a `worker.stdinClose` caller names; its handle binds the rest. */
export type WorkerStdinCloseArguments = Pick<Api.JobRequest, 'jobId'>;

/**
 * Ends a streamed stdin.
 */
export async function workerStdinClose(
  handle: NativeWorkerStdinClose,
  args: WorkerStdinCloseArguments,
): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(await handle.stdinClose(JSON.stringify(args)));
}

/** A handle that serves `workspace.attach`. */
export interface NativeWorkspaceAttach {
  attach(argumentsJson: string): Promise<string>;
}

/** The request fields a `workspace.attach` caller names; its handle binds the rest. */
export type WorkspaceAttachArguments = Pick<Api.WorkspaceAttachRequest, 'options'>;

/**
 * Attaches a detached workspace.
 */
export async function workspaceAttach(
  handle: NativeWorkspaceAttach,
  args: WorkspaceAttachArguments,
): Promise<Api.EmptyResult> {
  return V.parseEmptyResult(await handle.attach(JSON.stringify(args)));
}

/** A handle that serves `workspace.buildVolume`. */
export interface NativeWorkspaceBuildVolume {
  buildVolume(argumentsJson: string): Promise<string>;
}

/** The request fields a `workspace.buildVolume` caller names; its handle binds the rest. */
export type WorkspaceBuildVolumeArguments = Readonly<Record<string, never>>;

/**
 * The build volume a job of the workspace incarnation would be granted now.
 */
export async function workspaceBuildVolume(
  handle: NativeWorkspaceBuildVolume,
  args: WorkspaceBuildVolumeArguments,
): Promise<Api.BuildVolume> {
  return V.parseBuildVolume(await handle.buildVolume(JSON.stringify(args)));
}

/** A handle that serves `workspace.grants`. */
export interface NativeWorkspaceGrants {
  grants(argumentsJson: string): Promise<string>;
}

/** The request fields a `workspace.grants` caller names; its handle binds the rest. */
export type WorkspaceGrantsArguments = Readonly<Record<string, never>>;

/**
 * Reads one workspace's grants; a worker reads its own, fenced on its incarnation.
 */
export async function workspaceGrants(
  handle: NativeWorkspaceGrants,
  args: WorkspaceGrantsArguments,
): Promise<Api.GrantSet> {
  return V.parseGrantSet(await handle.grants(JSON.stringify(args)));
}

/** A handle that serves `workspace.info`. */
export interface NativeWorkspaceInfo {
  info(argumentsJson: string): Promise<string>;
}

/** The request fields a `workspace.info` caller names; its handle binds the rest. */
export type WorkspaceInfoArguments = Readonly<Record<string, never>>;

/**
 * Refreshes one workspace's information.
 */
export async function workspaceInfo(
  handle: NativeWorkspaceInfo,
  args: WorkspaceInfoArguments,
): Promise<Api.WorkspaceInfo> {
  return V.parseWorkspaceInfo(await handle.info(JSON.stringify(args)));
}
