// Generated by cowshed-api-gen from cowshed-core declarations. Do not edit.
import typia from 'typia';
import type * as Api from './api.generated.js';

export const assertAbandonedWork = typia.createAssertEquals<Api.AbandonedWork>();
export const parseAbandonedWork = (json: string): Api.AbandonedWork => assertAbandonedWork(JSON.parse(json));
export const assertAbandonedWorkList = typia.createAssertEquals<readonly Api.AbandonedWork[]>();
export const parseAbandonedWorkList = (json: string): readonly Api.AbandonedWork[] =>
  assertAbandonedWorkList(JSON.parse(json));

export const assertAdmissionCommitment = typia.createAssertEquals<Api.AdmissionCommitment>();
export const parseAdmissionCommitment = (json: string): Api.AdmissionCommitment =>
  assertAdmissionCommitment(JSON.parse(json));
export const assertAdmissionCommitmentList = typia.createAssertEquals<readonly Api.AdmissionCommitment[]>();
export const parseAdmissionCommitmentList = (json: string): readonly Api.AdmissionCommitment[] =>
  assertAdmissionCommitmentList(JSON.parse(json));

export const assertAdoptOptions = typia.createAssertEquals<Api.AdoptOptions>();
export const parseAdoptOptions = (json: string): Api.AdoptOptions => assertAdoptOptions(JSON.parse(json));
export const assertAdoptOptionsList = typia.createAssertEquals<readonly Api.AdoptOptions[]>();
export const parseAdoptOptionsList = (json: string): readonly Api.AdoptOptions[] =>
  assertAdoptOptionsList(JSON.parse(json));

export const assertAdoptRequest = typia.createAssertEquals<Api.AdoptRequest>();
export const parseAdoptRequest = (json: string): Api.AdoptRequest => assertAdoptRequest(JSON.parse(json));
export const assertAdoptRequestList = typia.createAssertEquals<readonly Api.AdoptRequest[]>();
export const parseAdoptRequestList = (json: string): readonly Api.AdoptRequest[] =>
  assertAdoptRequestList(JSON.parse(json));

export const assertAdoption = typia.createAssertEquals<Api.Adoption>();
export const parseAdoption = (json: string): Api.Adoption => assertAdoption(JSON.parse(json));
export const assertAdoptionList = typia.createAssertEquals<readonly Api.Adoption[]>();
export const parseAdoptionList = (json: string): readonly Api.Adoption[] => assertAdoptionList(JSON.parse(json));

export const assertAdoptionCheck = typia.createAssertEquals<Api.AdoptionCheck>();
export const parseAdoptionCheck = (json: string): Api.AdoptionCheck => assertAdoptionCheck(JSON.parse(json));
export const assertAdoptionCheckList = typia.createAssertEquals<readonly Api.AdoptionCheck[]>();
export const parseAdoptionCheckList = (json: string): readonly Api.AdoptionCheck[] =>
  assertAdoptionCheckList(JSON.parse(json));

export const assertAdoptionSkip = typia.createAssertEquals<Api.AdoptionSkip>();
export const parseAdoptionSkip = (json: string): Api.AdoptionSkip => assertAdoptionSkip(JSON.parse(json));
export const assertAdoptionSkipList = typia.createAssertEquals<readonly Api.AdoptionSkip[]>();
export const parseAdoptionSkipList = (json: string): readonly Api.AdoptionSkip[] =>
  assertAdoptionSkipList(JSON.parse(json));

export const assertAttachOptions = typia.createAssertEquals<Api.AttachOptions>();
export const parseAttachOptions = (json: string): Api.AttachOptions => assertAttachOptions(JSON.parse(json));
export const assertAttachOptionsList = typia.createAssertEquals<readonly Api.AttachOptions[]>();
export const parseAttachOptionsList = (json: string): readonly Api.AttachOptions[] =>
  assertAttachOptionsList(JSON.parse(json));

export const assertAuditDecision = typia.createAssertEquals<Api.AuditDecision>();
export const parseAuditDecision = (json: string): Api.AuditDecision => assertAuditDecision(JSON.parse(json));
export const assertAuditDecisionList = typia.createAssertEquals<readonly Api.AuditDecision[]>();
export const parseAuditDecisionList = (json: string): readonly Api.AuditDecision[] =>
  assertAuditDecisionList(JSON.parse(json));

export const assertAuditEvent = typia.createAssertEquals<Api.AuditEvent>();
export const parseAuditEvent = (json: string): Api.AuditEvent => assertAuditEvent(JSON.parse(json));
export const assertAuditEventList = typia.createAssertEquals<readonly Api.AuditEvent[]>();
export const parseAuditEventList = (json: string): readonly Api.AuditEvent[] => assertAuditEventList(JSON.parse(json));

export const assertBinaryData = typia.createAssertEquals<Api.BinaryData>();
export const parseBinaryData = (json: string): Api.BinaryData => assertBinaryData(JSON.parse(json));
export const assertBinaryDataList = typia.createAssertEquals<readonly Api.BinaryData[]>();
export const parseBinaryDataList = (json: string): readonly Api.BinaryData[] => assertBinaryDataList(JSON.parse(json));

export const assertBoundIdentity = typia.createAssertEquals<Api.BoundIdentity>();
export const parseBoundIdentity = (json: string): Api.BoundIdentity => assertBoundIdentity(JSON.parse(json));
export const assertBoundIdentityList = typia.createAssertEquals<readonly Api.BoundIdentity[]>();
export const parseBoundIdentityList = (json: string): readonly Api.BoundIdentity[] =>
  assertBoundIdentityList(JSON.parse(json));

export const assertBranchName = typia.createAssertEquals<Api.BranchName>();
export const parseBranchName = (json: string): Api.BranchName => assertBranchName(JSON.parse(json));
export const assertBranchNameList = typia.createAssertEquals<readonly Api.BranchName[]>();
export const parseBranchNameList = (json: string): readonly Api.BranchName[] => assertBranchNameList(JSON.parse(json));

export const assertBuildId = typia.createAssertEquals<Api.BuildId>();
export const parseBuildId = (json: string): Api.BuildId => assertBuildId(JSON.parse(json));
export const assertBuildIdList = typia.createAssertEquals<readonly Api.BuildId[]>();
export const parseBuildIdList = (json: string): readonly Api.BuildId[] => assertBuildIdList(JSON.parse(json));

export const assertBuildVolume = typia.createAssertEquals<Api.BuildVolume>();
export const parseBuildVolume = (json: string): Api.BuildVolume => assertBuildVolume(JSON.parse(json));
export const assertBuildVolumeList = typia.createAssertEquals<readonly Api.BuildVolume[]>();
export const parseBuildVolumeList = (json: string): readonly Api.BuildVolume[] =>
  assertBuildVolumeList(JSON.parse(json));

export const assertCacheMiss = typia.createAssertEquals<Api.CacheMiss>();
export const parseCacheMiss = (json: string): Api.CacheMiss => assertCacheMiss(JSON.parse(json));
export const assertCacheMissList = typia.createAssertEquals<readonly Api.CacheMiss[]>();
export const parseCacheMissList = (json: string): readonly Api.CacheMiss[] => assertCacheMissList(JSON.parse(json));

export const assertCarrySide = typia.createAssertEquals<Api.CarrySide>();
export const parseCarrySide = (json: string): Api.CarrySide => assertCarrySide(JSON.parse(json));
export const assertCarrySideList = typia.createAssertEquals<readonly Api.CarrySide[]>();
export const parseCarrySideList = (json: string): readonly Api.CarrySide[] => assertCarrySideList(JSON.parse(json));

export const assertChangeRepoIdRequest = typia.createAssertEquals<Api.ChangeRepoIdRequest>();
export const parseChangeRepoIdRequest = (json: string): Api.ChangeRepoIdRequest =>
  assertChangeRepoIdRequest(JSON.parse(json));
export const assertChangeRepoIdRequestList = typia.createAssertEquals<readonly Api.ChangeRepoIdRequest[]>();
export const parseChangeRepoIdRequestList = (json: string): readonly Api.ChangeRepoIdRequest[] =>
  assertChangeRepoIdRequestList(JSON.parse(json));

export const assertCheckpointCommitment = typia.createAssertEquals<Api.CheckpointCommitment>();
export const parseCheckpointCommitment = (json: string): Api.CheckpointCommitment =>
  assertCheckpointCommitment(JSON.parse(json));
export const assertCheckpointCommitmentList = typia.createAssertEquals<readonly Api.CheckpointCommitment[]>();
export const parseCheckpointCommitmentList = (json: string): readonly Api.CheckpointCommitment[] =>
  assertCheckpointCommitmentList(JSON.parse(json));

export const assertCheckpointInfo = typia.createAssertEquals<Api.CheckpointInfo>();
export const parseCheckpointInfo = (json: string): Api.CheckpointInfo => assertCheckpointInfo(JSON.parse(json));
export const assertCheckpointInfoList = typia.createAssertEquals<readonly Api.CheckpointInfo[]>();
export const parseCheckpointInfoList = (json: string): readonly Api.CheckpointInfo[] =>
  assertCheckpointInfoList(JSON.parse(json));

export const assertCheckpointOptions = typia.createAssertEquals<Api.CheckpointOptions>();
export const parseCheckpointOptions = (json: string): Api.CheckpointOptions =>
  assertCheckpointOptions(JSON.parse(json));
export const assertCheckpointOptionsList = typia.createAssertEquals<readonly Api.CheckpointOptions[]>();
export const parseCheckpointOptionsList = (json: string): readonly Api.CheckpointOptions[] =>
  assertCheckpointOptionsList(JSON.parse(json));

export const assertCheckpointQuota = typia.createAssertEquals<Api.CheckpointQuota>();
export const parseCheckpointQuota = (json: string): Api.CheckpointQuota => assertCheckpointQuota(JSON.parse(json));
export const assertCheckpointQuotaList = typia.createAssertEquals<readonly Api.CheckpointQuota[]>();
export const parseCheckpointQuotaList = (json: string): readonly Api.CheckpointQuota[] =>
  assertCheckpointQuotaList(JSON.parse(json));

export const assertCheckpointRequest = typia.createAssertEquals<Api.CheckpointRequest>();
export const parseCheckpointRequest = (json: string): Api.CheckpointRequest =>
  assertCheckpointRequest(JSON.parse(json));
export const assertCheckpointRequestList = typia.createAssertEquals<readonly Api.CheckpointRequest[]>();
export const parseCheckpointRequestList = (json: string): readonly Api.CheckpointRequest[] =>
  assertCheckpointRequestList(JSON.parse(json));

export const assertCheckpointResult = typia.createAssertEquals<Api.CheckpointResult>();
export const parseCheckpointResult = (json: string): Api.CheckpointResult => assertCheckpointResult(JSON.parse(json));
export const assertCheckpointResultList = typia.createAssertEquals<readonly Api.CheckpointResult[]>();
export const parseCheckpointResultList = (json: string): readonly Api.CheckpointResult[] =>
  assertCheckpointResultList(JSON.parse(json));

export const assertCommandArg = typia.createAssertEquals<Api.CommandArg>();
export const parseCommandArg = (json: string): Api.CommandArg => assertCommandArg(JSON.parse(json));
export const assertCommandArgList = typia.createAssertEquals<readonly Api.CommandArg[]>();
export const parseCommandArgList = (json: string): readonly Api.CommandArg[] => assertCommandArgList(JSON.parse(json));

export const assertControllerCommitment = typia.createAssertEquals<Api.ControllerCommitment>();
export const parseControllerCommitment = (json: string): Api.ControllerCommitment =>
  assertControllerCommitment(JSON.parse(json));
export const assertControllerCommitmentList = typia.createAssertEquals<readonly Api.ControllerCommitment[]>();
export const parseControllerCommitmentList = (json: string): readonly Api.ControllerCommitment[] =>
  assertControllerCommitmentList(JSON.parse(json));

export const assertControllerCommitmentRef = typia.createAssertEquals<Api.ControllerCommitmentRef>();
export const parseControllerCommitmentRef = (json: string): Api.ControllerCommitmentRef =>
  assertControllerCommitmentRef(JSON.parse(json));
export const assertControllerCommitmentRefList = typia.createAssertEquals<readonly Api.ControllerCommitmentRef[]>();
export const parseControllerCommitmentRefList = (json: string): readonly Api.ControllerCommitmentRef[] =>
  assertControllerCommitmentRefList(JSON.parse(json));

export const assertCowshedError = typia.createAssertEquals<Api.CowshedError>();
export const parseCowshedError = (json: string): Api.CowshedError => assertCowshedError(JSON.parse(json));
export const assertCowshedErrorList = typia.createAssertEquals<readonly Api.CowshedError[]>();
export const parseCowshedErrorList = (json: string): readonly Api.CowshedError[] =>
  assertCowshedErrorList(JSON.parse(json));

export const assertCpuMicros = typia.createAssertEquals<Api.CpuMicros>();
export const parseCpuMicros = (json: string): Api.CpuMicros => assertCpuMicros(JSON.parse(json));
export const assertCpuMicrosList = typia.createAssertEquals<readonly Api.CpuMicros[]>();
export const parseCpuMicrosList = (json: string): readonly Api.CpuMicros[] => assertCpuMicrosList(JSON.parse(json));

export const assertCreateOptions = typia.createAssertEquals<Api.CreateOptions>();
export const parseCreateOptions = (json: string): Api.CreateOptions => assertCreateOptions(JSON.parse(json));
export const assertCreateOptionsList = typia.createAssertEquals<readonly Api.CreateOptions[]>();
export const parseCreateOptionsList = (json: string): readonly Api.CreateOptions[] =>
  assertCreateOptionsList(JSON.parse(json));

export const assertCreateRequest = typia.createAssertEquals<Api.CreateRequest>();
export const parseCreateRequest = (json: string): Api.CreateRequest => assertCreateRequest(JSON.parse(json));
export const assertCreateRequestList = typia.createAssertEquals<readonly Api.CreateRequest[]>();
export const parseCreateRequestList = (json: string): readonly Api.CreateRequest[] =>
  assertCreateRequestList(JSON.parse(json));

export const assertCredentialReport = typia.createAssertEquals<Api.CredentialReport>();
export const parseCredentialReport = (json: string): Api.CredentialReport => assertCredentialReport(JSON.parse(json));
export const assertCredentialReportList = typia.createAssertEquals<readonly Api.CredentialReport[]>();
export const parseCredentialReportList = (json: string): readonly Api.CredentialReport[] =>
  assertCredentialReportList(JSON.parse(json));

export const assertCredentialRoute = typia.createAssertEquals<Api.CredentialRoute>();
export const parseCredentialRoute = (json: string): Api.CredentialRoute => assertCredentialRoute(JSON.parse(json));
export const assertCredentialRouteList = typia.createAssertEquals<readonly Api.CredentialRoute[]>();
export const parseCredentialRouteList = (json: string): readonly Api.CredentialRoute[] =>
  assertCredentialRouteList(JSON.parse(json));

export const assertDatabaseHolder = typia.createAssertEquals<Api.DatabaseHolder>();
export const parseDatabaseHolder = (json: string): Api.DatabaseHolder => assertDatabaseHolder(JSON.parse(json));
export const assertDatabaseHolderList = typia.createAssertEquals<readonly Api.DatabaseHolder[]>();
export const parseDatabaseHolderList = (json: string): readonly Api.DatabaseHolder[] =>
  assertDatabaseHolderList(JSON.parse(json));

export const assertDefragmentResult = typia.createAssertEquals<Api.DefragmentResult>();
export const parseDefragmentResult = (json: string): Api.DefragmentResult => assertDefragmentResult(JSON.parse(json));
export const assertDefragmentResultList = typia.createAssertEquals<readonly Api.DefragmentResult[]>();
export const parseDefragmentResultList = (json: string): readonly Api.DefragmentResult[] =>
  assertDefragmentResultList(JSON.parse(json));

export const assertDestroyRequest = typia.createAssertEquals<Api.DestroyRequest>();
export const parseDestroyRequest = (json: string): Api.DestroyRequest => assertDestroyRequest(JSON.parse(json));
export const assertDestroyRequestList = typia.createAssertEquals<readonly Api.DestroyRequest[]>();
export const parseDestroyRequestList = (json: string): readonly Api.DestroyRequest[] =>
  assertDestroyRequestList(JSON.parse(json));

export const assertDoctorReport = typia.createAssertEquals<Api.DoctorReport>();
export const parseDoctorReport = (json: string): Api.DoctorReport => assertDoctorReport(JSON.parse(json));
export const assertDoctorReportList = typia.createAssertEquals<readonly Api.DoctorReport[]>();
export const parseDoctorReportList = (json: string): readonly Api.DoctorReport[] =>
  assertDoctorReportList(JSON.parse(json));

export const assertEgressMode = typia.createAssertEquals<Api.EgressMode>();
export const parseEgressMode = (json: string): Api.EgressMode => assertEgressMode(JSON.parse(json));
export const assertEgressModeList = typia.createAssertEquals<readonly Api.EgressMode[]>();
export const parseEgressModeList = (json: string): readonly Api.EgressMode[] => assertEgressModeList(JSON.parse(json));

export const assertEgressRule = typia.createAssertEquals<Api.EgressRule>();
export const parseEgressRule = (json: string): Api.EgressRule => assertEgressRule(JSON.parse(json));
export const assertEgressRuleList = typia.createAssertEquals<readonly Api.EgressRule[]>();
export const parseEgressRuleList = (json: string): readonly Api.EgressRule[] => assertEgressRuleList(JSON.parse(json));

export const assertEmptyResult = typia.createAssertEquals<Api.EmptyResult>();
export const parseEmptyResult = (json: string): Api.EmptyResult => assertEmptyResult(JSON.parse(json));
export const assertEmptyResultList = typia.createAssertEquals<readonly Api.EmptyResult[]>();
export const parseEmptyResultList = (json: string): readonly Api.EmptyResult[] =>
  assertEmptyResultList(JSON.parse(json));

export const assertErrorCode = typia.createAssertEquals<Api.ErrorCode>();
export const parseErrorCode = (json: string): Api.ErrorCode => assertErrorCode(JSON.parse(json));
export const assertErrorCodeList = typia.createAssertEquals<readonly Api.ErrorCode[]>();
export const parseErrorCodeList = (json: string): readonly Api.ErrorCode[] => assertErrorCodeList(JSON.parse(json));

export const assertExecCommand = typia.createAssertEquals<Api.ExecCommand>();
export const parseExecCommand = (json: string): Api.ExecCommand => assertExecCommand(JSON.parse(json));
export const assertExecCommandList = typia.createAssertEquals<readonly Api.ExecCommand[]>();
export const parseExecCommandList = (json: string): readonly Api.ExecCommand[] =>
  assertExecCommandList(JSON.parse(json));

export const assertExecParams = typia.createAssertEquals<Api.ExecParams>();
export const parseExecParams = (json: string): Api.ExecParams => assertExecParams(JSON.parse(json));
export const assertExecParamsList = typia.createAssertEquals<readonly Api.ExecParams[]>();
export const parseExecParamsList = (json: string): readonly Api.ExecParams[] => assertExecParamsList(JSON.parse(json));

export const assertExecRecord = typia.createAssertEquals<Api.ExecRecord>();
export const parseExecRecord = (json: string): Api.ExecRecord => assertExecRecord(JSON.parse(json));
export const assertExecRecordList = typia.createAssertEquals<readonly Api.ExecRecord[]>();
export const parseExecRecordList = (json: string): readonly Api.ExecRecord[] => assertExecRecordList(JSON.parse(json));

export const assertExecRecordRef = typia.createAssertEquals<Api.ExecRecordRef>();
export const parseExecRecordRef = (json: string): Api.ExecRecordRef => assertExecRecordRef(JSON.parse(json));
export const assertExecRecordRefList = typia.createAssertEquals<readonly Api.ExecRecordRef[]>();
export const parseExecRecordRefList = (json: string): readonly Api.ExecRecordRef[] =>
  assertExecRecordRefList(JSON.parse(json));

export const assertExecStdin = typia.createAssertEquals<Api.ExecStdin>();
export const parseExecStdin = (json: string): Api.ExecStdin => assertExecStdin(JSON.parse(json));
export const assertExecStdinList = typia.createAssertEquals<readonly Api.ExecStdin[]>();
export const parseExecStdinList = (json: string): readonly Api.ExecStdin[] => assertExecStdinList(JSON.parse(json));

export const assertExitStatus = typia.createAssertEquals<Api.ExitStatus>();
export const parseExitStatus = (json: string): Api.ExitStatus => assertExitStatus(JSON.parse(json));
export const assertExitStatusList = typia.createAssertEquals<readonly Api.ExitStatus[]>();
export const parseExitStatusList = (json: string): readonly Api.ExitStatus[] => assertExitStatusList(JSON.parse(json));

export const assertExpectedRefHead = typia.createAssertEquals<Api.ExpectedRefHead>();
export const parseExpectedRefHead = (json: string): Api.ExpectedRefHead => assertExpectedRefHead(JSON.parse(json));
export const assertExpectedRefHeadList = typia.createAssertEquals<readonly Api.ExpectedRefHead[]>();
export const parseExpectedRefHeadList = (json: string): readonly Api.ExpectedRefHead[] =>
  assertExpectedRefHeadList(JSON.parse(json));

export const assertFailedCheck = typia.createAssertEquals<Api.FailedCheck>();
export const parseFailedCheck = (json: string): Api.FailedCheck => assertFailedCheck(JSON.parse(json));
export const assertFailedCheckList = typia.createAssertEquals<readonly Api.FailedCheck[]>();
export const parseFailedCheckList = (json: string): readonly Api.FailedCheck[] =>
  assertFailedCheckList(JSON.parse(json));

export const assertFenceRefusal = typia.createAssertEquals<Api.FenceRefusal>();
export const parseFenceRefusal = (json: string): Api.FenceRefusal => assertFenceRefusal(JSON.parse(json));
export const assertFenceRefusalList = typia.createAssertEquals<readonly Api.FenceRefusal[]>();
export const parseFenceRefusalList = (json: string): readonly Api.FenceRefusal[] =>
  assertFenceRefusalList(JSON.parse(json));

export const assertFinding = typia.createAssertEquals<Api.Finding>();
export const parseFinding = (json: string): Api.Finding => assertFinding(JSON.parse(json));
export const assertFindingList = typia.createAssertEquals<readonly Api.Finding[]>();
export const parseFindingList = (json: string): readonly Api.Finding[] => assertFindingList(JSON.parse(json));

export const assertFindingSeverity = typia.createAssertEquals<Api.FindingSeverity>();
export const parseFindingSeverity = (json: string): Api.FindingSeverity => assertFindingSeverity(JSON.parse(json));
export const assertFindingSeverityList = typia.createAssertEquals<readonly Api.FindingSeverity[]>();
export const parseFindingSeverityList = (json: string): readonly Api.FindingSeverity[] =>
  assertFindingSeverityList(JSON.parse(json));

export const assertForkCommitment = typia.createAssertEquals<Api.ForkCommitment>();
export const parseForkCommitment = (json: string): Api.ForkCommitment => assertForkCommitment(JSON.parse(json));
export const assertForkCommitmentList = typia.createAssertEquals<readonly Api.ForkCommitment[]>();
export const parseForkCommitmentList = (json: string): readonly Api.ForkCommitment[] =>
  assertForkCommitmentList(JSON.parse(json));

export const assertGatewayStatus = typia.createAssertEquals<Api.GatewayStatus>();
export const parseGatewayStatus = (json: string): Api.GatewayStatus => assertGatewayStatus(JSON.parse(json));
export const assertGatewayStatusList = typia.createAssertEquals<readonly Api.GatewayStatus[]>();
export const parseGatewayStatusList = (json: string): readonly Api.GatewayStatus[] =>
  assertGatewayStatusList(JSON.parse(json));

export const assertGcCandidate = typia.createAssertEquals<Api.GcCandidate>();
export const parseGcCandidate = (json: string): Api.GcCandidate => assertGcCandidate(JSON.parse(json));
export const assertGcCandidateList = typia.createAssertEquals<readonly Api.GcCandidate[]>();
export const parseGcCandidateList = (json: string): readonly Api.GcCandidate[] =>
  assertGcCandidateList(JSON.parse(json));

export const assertGcDeferred = typia.createAssertEquals<Api.GcDeferred>();
export const parseGcDeferred = (json: string): Api.GcDeferred => assertGcDeferred(JSON.parse(json));
export const assertGcDeferredList = typia.createAssertEquals<readonly Api.GcDeferred[]>();
export const parseGcDeferredList = (json: string): readonly Api.GcDeferred[] => assertGcDeferredList(JSON.parse(json));

export const assertGcOptions = typia.createAssertEquals<Api.GcOptions>();
export const parseGcOptions = (json: string): Api.GcOptions => assertGcOptions(JSON.parse(json));
export const assertGcOptionsList = typia.createAssertEquals<readonly Api.GcOptions[]>();
export const parseGcOptionsList = (json: string): readonly Api.GcOptions[] => assertGcOptionsList(JSON.parse(json));

export const assertGcReason = typia.createAssertEquals<Api.GcReason>();
export const parseGcReason = (json: string): Api.GcReason => assertGcReason(JSON.parse(json));
export const assertGcReasonList = typia.createAssertEquals<readonly Api.GcReason[]>();
export const parseGcReasonList = (json: string): readonly Api.GcReason[] => assertGcReasonList(JSON.parse(json));

export const assertGcReport = typia.createAssertEquals<Api.GcReport>();
export const parseGcReport = (json: string): Api.GcReport => assertGcReport(JSON.parse(json));
export const assertGcReportList = typia.createAssertEquals<readonly Api.GcReport[]>();
export const parseGcReportList = (json: string): readonly Api.GcReport[] => assertGcReportList(JSON.parse(json));

export const assertGcRequest = typia.createAssertEquals<Api.GcRequest>();
export const parseGcRequest = (json: string): Api.GcRequest => assertGcRequest(JSON.parse(json));
export const assertGcRequestList = typia.createAssertEquals<readonly Api.GcRequest[]>();
export const parseGcRequestList = (json: string): readonly Api.GcRequest[] => assertGcRequestList(JSON.parse(json));

export const assertGitOid = typia.createAssertEquals<Api.GitOid>();
export const parseGitOid = (json: string): Api.GitOid => assertGitOid(JSON.parse(json));
export const assertGitOidList = typia.createAssertEquals<readonly Api.GitOid[]>();
export const parseGitOidList = (json: string): readonly Api.GitOid[] => assertGitOidList(JSON.parse(json));

export const assertGitRef = typia.createAssertEquals<Api.GitRef>();
export const parseGitRef = (json: string): Api.GitRef => assertGitRef(JSON.parse(json));
export const assertGitRefList = typia.createAssertEquals<readonly Api.GitRef[]>();
export const parseGitRefList = (json: string): readonly Api.GitRef[] => assertGitRefList(JSON.parse(json));

export const assertGrantDelta = typia.createAssertEquals<Api.GrantDelta>();
export const parseGrantDelta = (json: string): Api.GrantDelta => assertGrantDelta(JSON.parse(json));
export const assertGrantDeltaList = typia.createAssertEquals<readonly Api.GrantDelta[]>();
export const parseGrantDeltaList = (json: string): readonly Api.GrantDelta[] => assertGrantDeltaList(JSON.parse(json));

export const assertGrantRequest = typia.createAssertEquals<Api.GrantRequest>();
export const parseGrantRequest = (json: string): Api.GrantRequest => assertGrantRequest(JSON.parse(json));
export const assertGrantRequestList = typia.createAssertEquals<readonly Api.GrantRequest[]>();
export const parseGrantRequestList = (json: string): readonly Api.GrantRequest[] =>
  assertGrantRequestList(JSON.parse(json));

export const assertGrantSet = typia.createAssertEquals<Api.GrantSet>();
export const parseGrantSet = (json: string): Api.GrantSet => assertGrantSet(JSON.parse(json));
export const assertGrantSetList = typia.createAssertEquals<readonly Api.GrantSet[]>();
export const parseGrantSetList = (json: string): readonly Api.GrantSet[] => assertGrantSetList(JSON.parse(json));

export const assertIdentityReport = typia.createAssertEquals<Api.IdentityReport>();
export const parseIdentityReport = (json: string): Api.IdentityReport => assertIdentityReport(JSON.parse(json));
export const assertIdentityReportList = typia.createAssertEquals<readonly Api.IdentityReport[]>();
export const parseIdentityReportList = (json: string): readonly Api.IdentityReport[] =>
  assertIdentityReportList(JSON.parse(json));

export const assertJobFailure = typia.createAssertEquals<Api.JobFailure>();
export const parseJobFailure = (json: string): Api.JobFailure => assertJobFailure(JSON.parse(json));
export const assertJobFailureList = typia.createAssertEquals<readonly Api.JobFailure[]>();
export const parseJobFailureList = (json: string): readonly Api.JobFailure[] => assertJobFailureList(JSON.parse(json));

export const assertJobId = typia.createAssertEquals<Api.JobId>();
export const parseJobId = (json: string): Api.JobId => assertJobId(JSON.parse(json));
export const assertJobIdList = typia.createAssertEquals<readonly Api.JobId[]>();
export const parseJobIdList = (json: string): readonly Api.JobId[] => assertJobIdList(JSON.parse(json));

export const assertJobInfo = typia.createAssertEquals<Api.JobInfo>();
export const parseJobInfo = (json: string): Api.JobInfo => assertJobInfo(JSON.parse(json));
export const assertJobInfoList = typia.createAssertEquals<readonly Api.JobInfo[]>();
export const parseJobInfoList = (json: string): readonly Api.JobInfo[] => assertJobInfoList(JSON.parse(json));

export const assertJobInfoRef = typia.createAssertEquals<Api.JobInfoRef>();
export const parseJobInfoRef = (json: string): Api.JobInfoRef => assertJobInfoRef(JSON.parse(json));
export const assertJobInfoRefList = typia.createAssertEquals<readonly Api.JobInfoRef[]>();
export const parseJobInfoRefList = (json: string): readonly Api.JobInfoRef[] => assertJobInfoRefList(JSON.parse(json));

export const assertJobJournalCursor = typia.createAssertEquals<Api.JobJournalCursor>();
export const parseJobJournalCursor = (json: string): Api.JobJournalCursor => assertJobJournalCursor(JSON.parse(json));
export const assertJobJournalCursorList = typia.createAssertEquals<readonly Api.JobJournalCursor[]>();
export const parseJobJournalCursorList = (json: string): readonly Api.JobJournalCursor[] =>
  assertJobJournalCursorList(JSON.parse(json));

export const assertJobProcessSample = typia.createAssertEquals<Api.JobProcessSample>();
export const parseJobProcessSample = (json: string): Api.JobProcessSample => assertJobProcessSample(JSON.parse(json));
export const assertJobProcessSampleList = typia.createAssertEquals<readonly Api.JobProcessSample[]>();
export const parseJobProcessSampleList = (json: string): readonly Api.JobProcessSample[] =>
  assertJobProcessSampleList(JSON.parse(json));

export const assertJobProcessTree = typia.createAssertEquals<Api.JobProcessTree>();
export const parseJobProcessTree = (json: string): Api.JobProcessTree => assertJobProcessTree(JSON.parse(json));
export const assertJobProcessTreeList = typia.createAssertEquals<readonly Api.JobProcessTree[]>();
export const parseJobProcessTreeList = (json: string): readonly Api.JobProcessTree[] =>
  assertJobProcessTreeList(JSON.parse(json));

export const assertJobRequest = typia.createAssertEquals<Api.JobRequest>();
export const parseJobRequest = (json: string): Api.JobRequest => assertJobRequest(JSON.parse(json));
export const assertJobRequestList = typia.createAssertEquals<readonly Api.JobRequest[]>();
export const parseJobRequestList = (json: string): readonly Api.JobRequest[] => assertJobRequestList(JSON.parse(json));

export const assertJobState = typia.createAssertEquals<Api.JobState>();
export const parseJobState = (json: string): Api.JobState => assertJobState(JSON.parse(json));
export const assertJobStateList = typia.createAssertEquals<readonly Api.JobState[]>();
export const parseJobStateList = (json: string): readonly Api.JobState[] => assertJobStateList(JSON.parse(json));

export const assertJobStream = typia.createAssertEquals<Api.JobStream>();
export const parseJobStream = (json: string): Api.JobStream => assertJobStream(JSON.parse(json));
export const assertJobStreamList = typia.createAssertEquals<readonly Api.JobStream[]>();
export const parseJobStreamList = (json: string): readonly Api.JobStream[] => assertJobStreamList(JSON.parse(json));

export const assertJobTail = typia.createAssertEquals<Api.JobTail>();
export const parseJobTail = (json: string): Api.JobTail => assertJobTail(JSON.parse(json));
export const assertJobTailList = typia.createAssertEquals<readonly Api.JobTail[]>();
export const parseJobTailList = (json: string): readonly Api.JobTail[] => assertJobTailList(JSON.parse(json));

export const assertJobTailBytes = typia.createAssertEquals<Api.JobTailBytes>();
export const parseJobTailBytes = (json: string): Api.JobTailBytes => assertJobTailBytes(JSON.parse(json));
export const assertJobTailBytesList = typia.createAssertEquals<readonly Api.JobTailBytes[]>();
export const parseJobTailBytesList = (json: string): readonly Api.JobTailBytes[] =>
  assertJobTailBytesList(JSON.parse(json));

export const assertJobTailLimits = typia.createAssertEquals<Api.JobTailLimits>();
export const parseJobTailLimits = (json: string): Api.JobTailLimits => assertJobTailLimits(JSON.parse(json));
export const assertJobTailLimitsList = typia.createAssertEquals<readonly Api.JobTailLimits[]>();
export const parseJobTailLimitsList = (json: string): readonly Api.JobTailLimits[] =>
  assertJobTailLimitsList(JSON.parse(json));

export const assertLandAdoptionCommitment = typia.createAssertEquals<Api.LandAdoptionCommitment>();
export const parseLandAdoptionCommitment = (json: string): Api.LandAdoptionCommitment =>
  assertLandAdoptionCommitment(JSON.parse(json));
export const assertLandAdoptionCommitmentList = typia.createAssertEquals<readonly Api.LandAdoptionCommitment[]>();
export const parseLandAdoptionCommitmentList = (json: string): readonly Api.LandAdoptionCommitment[] =>
  assertLandAdoptionCommitmentList(JSON.parse(json));

export const assertLandBuildVolume = typia.createAssertEquals<Api.LandBuildVolume>();
export const parseLandBuildVolume = (json: string): Api.LandBuildVolume => assertLandBuildVolume(JSON.parse(json));
export const assertLandBuildVolumeList = typia.createAssertEquals<readonly Api.LandBuildVolume[]>();
export const parseLandBuildVolumeList = (json: string): readonly Api.LandBuildVolume[] =>
  assertLandBuildVolumeList(JSON.parse(json));

export const assertLandOptions = typia.createAssertEquals<Api.LandOptions>();
export const parseLandOptions = (json: string): Api.LandOptions => assertLandOptions(JSON.parse(json));
export const assertLandOptionsList = typia.createAssertEquals<readonly Api.LandOptions[]>();
export const parseLandOptionsList = (json: string): readonly Api.LandOptions[] =>
  assertLandOptionsList(JSON.parse(json));

export const assertLandReport = typia.createAssertEquals<Api.LandReport>();
export const parseLandReport = (json: string): Api.LandReport => assertLandReport(JSON.parse(json));
export const assertLandReportList = typia.createAssertEquals<readonly Api.LandReport[]>();
export const parseLandReportList = (json: string): readonly Api.LandReport[] => assertLandReportList(JSON.parse(json));

export const assertLandRequest = typia.createAssertEquals<Api.LandRequest>();
export const parseLandRequest = (json: string): Api.LandRequest => assertLandRequest(JSON.parse(json));
export const assertLandRequestList = typia.createAssertEquals<readonly Api.LandRequest[]>();
export const parseLandRequestList = (json: string): readonly Api.LandRequest[] =>
  assertLandRequestList(JSON.parse(json));

export const assertLandingCommits = typia.createAssertEquals<Api.LandingCommits>();
export const parseLandingCommits = (json: string): Api.LandingCommits => assertLandingCommits(JSON.parse(json));
export const assertLandingCommitsList = typia.createAssertEquals<readonly Api.LandingCommits[]>();
export const parseLandingCommitsList = (json: string): readonly Api.LandingCommits[] =>
  assertLandingCommitsList(JSON.parse(json));

export const assertLogsChunk = typia.createAssertEquals<Api.LogsChunk>();
export const parseLogsChunk = (json: string): Api.LogsChunk => assertLogsChunk(JSON.parse(json));
export const assertLogsChunkList = typia.createAssertEquals<readonly Api.LogsChunk[]>();
export const parseLogsChunkList = (json: string): readonly Api.LogsChunk[] => assertLogsChunkList(JSON.parse(json));

export const assertLogsRequest = typia.createAssertEquals<Api.LogsRequest>();
export const parseLogsRequest = (json: string): Api.LogsRequest => assertLogsRequest(JSON.parse(json));
export const assertLogsRequestList = typia.createAssertEquals<readonly Api.LogsRequest[]>();
export const parseLogsRequestList = (json: string): readonly Api.LogsRequest[] =>
  assertLogsRequestList(JSON.parse(json));

export const assertMirrorInfo = typia.createAssertEquals<Api.MirrorInfo>();
export const parseMirrorInfo = (json: string): Api.MirrorInfo => assertMirrorInfo(JSON.parse(json));
export const assertMirrorInfoList = typia.createAssertEquals<readonly Api.MirrorInfo[]>();
export const parseMirrorInfoList = (json: string): readonly Api.MirrorInfo[] => assertMirrorInfoList(JSON.parse(json));

export const assertMirrorRequest = typia.createAssertEquals<Api.MirrorRequest>();
export const parseMirrorRequest = (json: string): Api.MirrorRequest => assertMirrorRequest(JSON.parse(json));
export const assertMirrorRequestList = typia.createAssertEquals<readonly Api.MirrorRequest[]>();
export const parseMirrorRequestList = (json: string): readonly Api.MirrorRequest[] =>
  assertMirrorRequestList(JSON.parse(json));

export const assertMountResult = typia.createAssertEquals<Api.MountResult>();
export const parseMountResult = (json: string): Api.MountResult => assertMountResult(JSON.parse(json));
export const assertMountResultList = typia.createAssertEquals<readonly Api.MountResult[]>();
export const parseMountResultList = (json: string): readonly Api.MountResult[] =>
  assertMountResultList(JSON.parse(json));

export const assertMoveCheckoutRequest = typia.createAssertEquals<Api.MoveCheckoutRequest>();
export const parseMoveCheckoutRequest = (json: string): Api.MoveCheckoutRequest =>
  assertMoveCheckoutRequest(JSON.parse(json));
export const assertMoveCheckoutRequestList = typia.createAssertEquals<readonly Api.MoveCheckoutRequest[]>();
export const parseMoveCheckoutRequestList = (json: string): readonly Api.MoveCheckoutRequest[] =>
  assertMoveCheckoutRequestList(JSON.parse(json));

export const assertNxCarry = typia.createAssertEquals<Api.NxCarry>();
export const parseNxCarry = (json: string): Api.NxCarry => assertNxCarry(JSON.parse(json));
export const assertNxCarryList = typia.createAssertEquals<readonly Api.NxCarry[]>();
export const parseNxCarryList = (json: string): readonly Api.NxCarry[] => assertNxCarryList(JSON.parse(json));

export const assertOtherBuild = typia.createAssertEquals<Api.OtherBuild>();
export const parseOtherBuild = (json: string): Api.OtherBuild => assertOtherBuild(JSON.parse(json));
export const assertOtherBuildList = typia.createAssertEquals<readonly Api.OtherBuild[]>();
export const parseOtherBuildList = (json: string): readonly Api.OtherBuild[] => assertOtherBuildList(JSON.parse(json));

export const assertOutputLimitInfo = typia.createAssertEquals<Api.OutputLimitInfo>();
export const parseOutputLimitInfo = (json: string): Api.OutputLimitInfo => assertOutputLimitInfo(JSON.parse(json));
export const assertOutputLimitInfoList = typia.createAssertEquals<readonly Api.OutputLimitInfo[]>();
export const parseOutputLimitInfoList = (json: string): readonly Api.OutputLimitInfo[] =>
  assertOutputLimitInfoList(JSON.parse(json));

export const assertOutputPublication = typia.createAssertEquals<Api.OutputPublication>();
export const parseOutputPublication = (json: string): Api.OutputPublication =>
  assertOutputPublication(JSON.parse(json));
export const assertOutputPublicationList = typia.createAssertEquals<readonly Api.OutputPublication[]>();
export const parseOutputPublicationList = (json: string): readonly Api.OutputPublication[] =>
  assertOutputPublicationList(JSON.parse(json));

export const assertOutputStorage = typia.createAssertEquals<Api.OutputStorage>();
export const parseOutputStorage = (json: string): Api.OutputStorage => assertOutputStorage(JSON.parse(json));
export const assertOutputStorageList = typia.createAssertEquals<readonly Api.OutputStorage[]>();
export const parseOutputStorageList = (json: string): readonly Api.OutputStorage[] =>
  assertOutputStorageList(JSON.parse(json));

export const assertOutputSummary = typia.createAssertEquals<Api.OutputSummary>();
export const parseOutputSummary = (json: string): Api.OutputSummary => assertOutputSummary(JSON.parse(json));
export const assertOutputSummaryList = typia.createAssertEquals<readonly Api.OutputSummary[]>();
export const parseOutputSummaryList = (json: string): readonly Api.OutputSummary[] =>
  assertOutputSummaryList(JSON.parse(json));

export const assertPortBlock = typia.createAssertEquals<Api.PortBlock>();
export const parsePortBlock = (json: string): Api.PortBlock => assertPortBlock(JSON.parse(json));
export const assertPortBlockList = typia.createAssertEquals<readonly Api.PortBlock[]>();
export const parsePortBlockList = (json: string): readonly Api.PortBlock[] => assertPortBlockList(JSON.parse(json));

export const assertProcessCoverage = typia.createAssertEquals<Api.ProcessCoverage>();
export const parseProcessCoverage = (json: string): Api.ProcessCoverage => assertProcessCoverage(JSON.parse(json));
export const assertProcessCoverageList = typia.createAssertEquals<readonly Api.ProcessCoverage[]>();
export const parseProcessCoverageList = (json: string): readonly Api.ProcessCoverage[] =>
  assertProcessCoverageList(JSON.parse(json));

export const assertProcessCoverageGap = typia.createAssertEquals<Api.ProcessCoverageGap>();
export const parseProcessCoverageGap = (json: string): Api.ProcessCoverageGap =>
  assertProcessCoverageGap(JSON.parse(json));
export const assertProcessCoverageGapList = typia.createAssertEquals<readonly Api.ProcessCoverageGap[]>();
export const parseProcessCoverageGapList = (json: string): readonly Api.ProcessCoverageGap[] =>
  assertProcessCoverageGapList(JSON.parse(json));

export const assertProcessExit = typia.createAssertEquals<Api.ProcessExit>();
export const parseProcessExit = (json: string): Api.ProcessExit => assertProcessExit(JSON.parse(json));
export const assertProcessExitList = typia.createAssertEquals<readonly Api.ProcessExit[]>();
export const parseProcessExitList = (json: string): readonly Api.ProcessExit[] =>
  assertProcessExitList(JSON.parse(json));

export const assertProcessIoUnavailable = typia.createAssertEquals<Api.ProcessIoUnavailable>();
export const parseProcessIoUnavailable = (json: string): Api.ProcessIoUnavailable =>
  assertProcessIoUnavailable(JSON.parse(json));
export const assertProcessIoUnavailableList = typia.createAssertEquals<readonly Api.ProcessIoUnavailable[]>();
export const parseProcessIoUnavailableList = (json: string): readonly Api.ProcessIoUnavailable[] =>
  assertProcessIoUnavailableList(JSON.parse(json));

export const assertProcessStorageIo = typia.createAssertEquals<Api.ProcessStorageIo>();
export const parseProcessStorageIo = (json: string): Api.ProcessStorageIo => assertProcessStorageIo(JSON.parse(json));
export const assertProcessStorageIoList = typia.createAssertEquals<readonly Api.ProcessStorageIo[]>();
export const parseProcessStorageIoList = (json: string): readonly Api.ProcessStorageIo[] =>
  assertProcessStorageIoList(JSON.parse(json));

export const assertProcessUsage = typia.createAssertEquals<Api.ProcessUsage>();
export const parseProcessUsage = (json: string): Api.ProcessUsage => assertProcessUsage(JSON.parse(json));
export const assertProcessUsageList = typia.createAssertEquals<readonly Api.ProcessUsage[]>();
export const parseProcessUsageList = (json: string): readonly Api.ProcessUsage[] =>
  assertProcessUsageList(JSON.parse(json));

export const assertProjectGrantDelta = typia.createAssertEquals<Api.ProjectGrantDelta>();
export const parseProjectGrantDelta = (json: string): Api.ProjectGrantDelta =>
  assertProjectGrantDelta(JSON.parse(json));
export const assertProjectGrantDeltaList = typia.createAssertEquals<readonly Api.ProjectGrantDelta[]>();
export const parseProjectGrantDeltaList = (json: string): readonly Api.ProjectGrantDelta[] =>
  assertProjectGrantDeltaList(JSON.parse(json));

export const assertProjectGrantRequest = typia.createAssertEquals<Api.ProjectGrantRequest>();
export const parseProjectGrantRequest = (json: string): Api.ProjectGrantRequest =>
  assertProjectGrantRequest(JSON.parse(json));
export const assertProjectGrantRequestList = typia.createAssertEquals<readonly Api.ProjectGrantRequest[]>();
export const parseProjectGrantRequestList = (json: string): readonly Api.ProjectGrantRequest[] =>
  assertProjectGrantRequestList(JSON.parse(json));

export const assertProjectGrants = typia.createAssertEquals<Api.ProjectGrants>();
export const parseProjectGrants = (json: string): Api.ProjectGrants => assertProjectGrants(JSON.parse(json));
export const assertProjectGrantsList = typia.createAssertEquals<readonly Api.ProjectGrants[]>();
export const parseProjectGrantsList = (json: string): readonly Api.ProjectGrants[] =>
  assertProjectGrantsList(JSON.parse(json));

export const assertProjectOpenRequest = typia.createAssertEquals<Api.ProjectOpenRequest>();
export const parseProjectOpenRequest = (json: string): Api.ProjectOpenRequest =>
  assertProjectOpenRequest(JSON.parse(json));
export const assertProjectOpenRequestList = typia.createAssertEquals<readonly Api.ProjectOpenRequest[]>();
export const parseProjectOpenRequestList = (json: string): readonly Api.ProjectOpenRequest[] =>
  assertProjectOpenRequestList(JSON.parse(json));

export const assertProjectOpened = typia.createAssertEquals<Api.ProjectOpened>();
export const parseProjectOpened = (json: string): Api.ProjectOpened => assertProjectOpened(JSON.parse(json));
export const assertProjectOpenedList = typia.createAssertEquals<readonly Api.ProjectOpened[]>();
export const parseProjectOpenedList = (json: string): readonly Api.ProjectOpened[] =>
  assertProjectOpenedList(JSON.parse(json));

export const assertProjectWorkspaces = typia.createAssertEquals<Api.ProjectWorkspaces>();
export const parseProjectWorkspaces = (json: string): Api.ProjectWorkspaces =>
  assertProjectWorkspaces(JSON.parse(json));
export const assertProjectWorkspacesList = typia.createAssertEquals<readonly Api.ProjectWorkspaces[]>();
export const parseProjectWorkspacesList = (json: string): readonly Api.ProjectWorkspaces[] =>
  assertProjectWorkspacesList(JSON.parse(json));

export const assertProtectedOutput = typia.createAssertEquals<Api.ProtectedOutput>();
export const parseProtectedOutput = (json: string): Api.ProtectedOutput => assertProtectedOutput(JSON.parse(json));
export const assertProtectedOutputList = typia.createAssertEquals<readonly Api.ProtectedOutput[]>();
export const parseProtectedOutputList = (json: string): readonly Api.ProtectedOutput[] =>
  assertProtectedOutputList(JSON.parse(json));

export const assertPublicationPolicy = typia.createAssertEquals<Api.PublicationPolicy>();
export const parsePublicationPolicy = (json: string): Api.PublicationPolicy =>
  assertPublicationPolicy(JSON.parse(json));
export const assertPublicationPolicyList = typia.createAssertEquals<readonly Api.PublicationPolicy[]>();
export const parsePublicationPolicyList = (json: string): readonly Api.PublicationPolicy[] =>
  assertPublicationPolicyList(JSON.parse(json));

export const assertPushOptions = typia.createAssertEquals<Api.PushOptions>();
export const parsePushOptions = (json: string): Api.PushOptions => assertPushOptions(JSON.parse(json));
export const assertPushOptionsList = typia.createAssertEquals<readonly Api.PushOptions[]>();
export const parsePushOptionsList = (json: string): readonly Api.PushOptions[] =>
  assertPushOptionsList(JSON.parse(json));

export const assertPushReport = typia.createAssertEquals<Api.PushReport>();
export const parsePushReport = (json: string): Api.PushReport => assertPushReport(JSON.parse(json));
export const assertPushReportList = typia.createAssertEquals<readonly Api.PushReport[]>();
export const parsePushReportList = (json: string): readonly Api.PushReport[] => assertPushReportList(JSON.parse(json));

export const assertPushRequest = typia.createAssertEquals<Api.PushRequest>();
export const parsePushRequest = (json: string): Api.PushRequest => assertPushRequest(JSON.parse(json));
export const assertPushRequestList = typia.createAssertEquals<readonly Api.PushRequest[]>();
export const parsePushRequestList = (json: string): readonly Api.PushRequest[] =>
  assertPushRequestList(JSON.parse(json));

export const assertQuotaRequest = typia.createAssertEquals<Api.QuotaRequest>();
export const parseQuotaRequest = (json: string): Api.QuotaRequest => assertQuotaRequest(JSON.parse(json));
export const assertQuotaRequestList = typia.createAssertEquals<readonly Api.QuotaRequest[]>();
export const parseQuotaRequestList = (json: string): readonly Api.QuotaRequest[] =>
  assertQuotaRequestList(JSON.parse(json));

export const assertRebaseBuildVolume = typia.createAssertEquals<Api.RebaseBuildVolume>();
export const parseRebaseBuildVolume = (json: string): Api.RebaseBuildVolume =>
  assertRebaseBuildVolume(JSON.parse(json));
export const assertRebaseBuildVolumeList = typia.createAssertEquals<readonly Api.RebaseBuildVolume[]>();
export const parseRebaseBuildVolumeList = (json: string): readonly Api.RebaseBuildVolume[] =>
  assertRebaseBuildVolumeList(JSON.parse(json));

export const assertRebaseCarrySkip = typia.createAssertEquals<Api.RebaseCarrySkip>();
export const parseRebaseCarrySkip = (json: string): Api.RebaseCarrySkip => assertRebaseCarrySkip(JSON.parse(json));
export const assertRebaseCarrySkipList = typia.createAssertEquals<readonly Api.RebaseCarrySkip[]>();
export const parseRebaseCarrySkipList = (json: string): readonly Api.RebaseCarrySkip[] =>
  assertRebaseCarrySkipList(JSON.parse(json));

export const assertRebaseOptions = typia.createAssertEquals<Api.RebaseOptions>();
export const parseRebaseOptions = (json: string): Api.RebaseOptions => assertRebaseOptions(JSON.parse(json));
export const assertRebaseOptionsList = typia.createAssertEquals<readonly Api.RebaseOptions[]>();
export const parseRebaseOptionsList = (json: string): readonly Api.RebaseOptions[] =>
  assertRebaseOptionsList(JSON.parse(json));

export const assertRebaseReport = typia.createAssertEquals<Api.RebaseReport>();
export const parseRebaseReport = (json: string): Api.RebaseReport => assertRebaseReport(JSON.parse(json));
export const assertRebaseReportList = typia.createAssertEquals<readonly Api.RebaseReport[]>();
export const parseRebaseReportList = (json: string): readonly Api.RebaseReport[] =>
  assertRebaseReportList(JSON.parse(json));

export const assertRebaseRequest = typia.createAssertEquals<Api.RebaseRequest>();
export const parseRebaseRequest = (json: string): Api.RebaseRequest => assertRebaseRequest(JSON.parse(json));
export const assertRebaseRequestList = typia.createAssertEquals<readonly Api.RebaseRequest[]>();
export const parseRebaseRequestList = (json: string): readonly Api.RebaseRequest[] =>
  assertRebaseRequestList(JSON.parse(json));

export const assertRekeyResult = typia.createAssertEquals<Api.RekeyResult>();
export const parseRekeyResult = (json: string): Api.RekeyResult => assertRekeyResult(JSON.parse(json));
export const assertRekeyResultList = typia.createAssertEquals<readonly Api.RekeyResult[]>();
export const parseRekeyResultList = (json: string): readonly Api.RekeyResult[] =>
  assertRekeyResultList(JSON.parse(json));

export const assertRemoveOptions = typia.createAssertEquals<Api.RemoveOptions>();
export const parseRemoveOptions = (json: string): Api.RemoveOptions => assertRemoveOptions(JSON.parse(json));
export const assertRemoveOptionsList = typia.createAssertEquals<readonly Api.RemoveOptions[]>();
export const parseRemoveOptionsList = (json: string): readonly Api.RemoveOptions[] =>
  assertRemoveOptionsList(JSON.parse(json));

export const assertRemoveProjectOptions = typia.createAssertEquals<Api.RemoveProjectOptions>();
export const parseRemoveProjectOptions = (json: string): Api.RemoveProjectOptions =>
  assertRemoveProjectOptions(JSON.parse(json));
export const assertRemoveProjectOptionsList = typia.createAssertEquals<readonly Api.RemoveProjectOptions[]>();
export const parseRemoveProjectOptionsList = (json: string): readonly Api.RemoveProjectOptions[] =>
  assertRemoveProjectOptionsList(JSON.parse(json));

export const assertRemoveProjectReport = typia.createAssertEquals<Api.RemoveProjectReport>();
export const parseRemoveProjectReport = (json: string): Api.RemoveProjectReport =>
  assertRemoveProjectReport(JSON.parse(json));
export const assertRemoveProjectReportList = typia.createAssertEquals<readonly Api.RemoveProjectReport[]>();
export const parseRemoveProjectReportList = (json: string): readonly Api.RemoveProjectReport[] =>
  assertRemoveProjectReportList(JSON.parse(json));

export const assertRemoveProjectRequest = typia.createAssertEquals<Api.RemoveProjectRequest>();
export const parseRemoveProjectRequest = (json: string): Api.RemoveProjectRequest =>
  assertRemoveProjectRequest(JSON.parse(json));
export const assertRemoveProjectRequestList = typia.createAssertEquals<readonly Api.RemoveProjectRequest[]>();
export const parseRemoveProjectRequestList = (json: string): readonly Api.RemoveProjectRequest[] =>
  assertRemoveProjectRequestList(JSON.parse(json));

export const assertRemoveReport = typia.createAssertEquals<Api.RemoveReport>();
export const parseRemoveReport = (json: string): Api.RemoveReport => assertRemoveReport(JSON.parse(json));
export const assertRemoveReportList = typia.createAssertEquals<readonly Api.RemoveReport[]>();
export const parseRemoveReportList = (json: string): readonly Api.RemoveReport[] =>
  assertRemoveReportList(JSON.parse(json));

export const assertRemovedWorkspace = typia.createAssertEquals<Api.RemovedWorkspace>();
export const parseRemovedWorkspace = (json: string): Api.RemovedWorkspace => assertRemovedWorkspace(JSON.parse(json));
export const assertRemovedWorkspaceList = typia.createAssertEquals<readonly Api.RemovedWorkspace[]>();
export const parseRemovedWorkspaceList = (json: string): readonly Api.RemovedWorkspace[] =>
  assertRemovedWorkspaceList(JSON.parse(json));

export const assertRepoId = typia.createAssertEquals<Api.RepoId>();
export const parseRepoId = (json: string): Api.RepoId => assertRepoId(JSON.parse(json));
export const assertRepoIdList = typia.createAssertEquals<readonly Api.RepoId[]>();
export const parseRepoIdList = (json: string): readonly Api.RepoId[] => assertRepoIdList(JSON.parse(json));

export const assertRepoRequest = typia.createAssertEquals<Api.RepoRequest>();
export const parseRepoRequest = (json: string): Api.RepoRequest => assertRepoRequest(JSON.parse(json));
export const assertRepoRequestList = typia.createAssertEquals<readonly Api.RepoRequest[]>();
export const parseRepoRequestList = (json: string): readonly Api.RepoRequest[] =>
  assertRepoRequestList(JSON.parse(json));

export const assertRepoRule = typia.createAssertEquals<Api.RepoRule>();
export const parseRepoRule = (json: string): Api.RepoRule => assertRepoRule(JSON.parse(json));
export const assertRepoRuleList = typia.createAssertEquals<readonly Api.RepoRule[]>();
export const parseRepoRuleList = (json: string): readonly Api.RepoRule[] => assertRepoRuleList(JSON.parse(json));

export const assertRepositoryBinding = typia.createAssertEquals<Api.RepositoryBinding>();
export const parseRepositoryBinding = (json: string): Api.RepositoryBinding =>
  assertRepositoryBinding(JSON.parse(json));
export const assertRepositoryBindingList = typia.createAssertEquals<readonly Api.RepositoryBinding[]>();
export const parseRepositoryBindingList = (json: string): readonly Api.RepositoryBinding[] =>
  assertRepositoryBindingList(JSON.parse(json));

export const assertReseed = typia.createAssertEquals<Api.Reseed>();
export const parseReseed = (json: string): Api.Reseed => assertReseed(JSON.parse(json));
export const assertReseedList = typia.createAssertEquals<readonly Api.Reseed[]>();
export const parseReseedList = (json: string): readonly Api.Reseed[] => assertReseedList(JSON.parse(json));

export const assertReseedResult = typia.createAssertEquals<Api.ReseedResult>();
export const parseReseedResult = (json: string): Api.ReseedResult => assertReseedResult(JSON.parse(json));
export const assertReseedResultList = typia.createAssertEquals<readonly Api.ReseedResult[]>();
export const parseReseedResultList = (json: string): readonly Api.ReseedResult[] =>
  assertReseedResultList(JSON.parse(json));

export const assertReseedSkip = typia.createAssertEquals<Api.ReseedSkip>();
export const parseReseedSkip = (json: string): Api.ReseedSkip => assertReseedSkip(JSON.parse(json));
export const assertReseedSkipList = typia.createAssertEquals<readonly Api.ReseedSkip[]>();
export const parseReseedSkipList = (json: string): readonly Api.ReseedSkip[] => assertReseedSkipList(JSON.parse(json));

export const assertResidentBytes = typia.createAssertEquals<Api.ResidentBytes>();
export const parseResidentBytes = (json: string): Api.ResidentBytes => assertResidentBytes(JSON.parse(json));
export const assertResidentBytesList = typia.createAssertEquals<readonly Api.ResidentBytes[]>();
export const parseResidentBytesList = (json: string): readonly Api.ResidentBytes[] =>
  assertResidentBytesList(JSON.parse(json));

export const assertResizeRequest = typia.createAssertEquals<Api.ResizeRequest>();
export const parseResizeRequest = (json: string): Api.ResizeRequest => assertResizeRequest(JSON.parse(json));
export const assertResizeRequestList = typia.createAssertEquals<readonly Api.ResizeRequest[]>();
export const parseResizeRequestList = (json: string): readonly Api.ResizeRequest[] =>
  assertResizeRequestList(JSON.parse(json));

export const assertResizeResult = typia.createAssertEquals<Api.ResizeResult>();
export const parseResizeResult = (json: string): Api.ResizeResult => assertResizeResult(JSON.parse(json));
export const assertResizeResultList = typia.createAssertEquals<readonly Api.ResizeResult[]>();
export const parseResizeResultList = (json: string): readonly Api.ResizeResult[] =>
  assertResizeResultList(JSON.parse(json));

export const assertResizeVolume = typia.createAssertEquals<Api.ResizeVolume>();
export const parseResizeVolume = (json: string): Api.ResizeVolume => assertResizeVolume(JSON.parse(json));
export const assertResizeVolumeList = typia.createAssertEquals<readonly Api.ResizeVolume[]>();
export const parseResizeVolumeList = (json: string): readonly Api.ResizeVolume[] =>
  assertResizeVolumeList(JSON.parse(json));

export const assertRestoreCommitment = typia.createAssertEquals<Api.RestoreCommitment>();
export const parseRestoreCommitment = (json: string): Api.RestoreCommitment =>
  assertRestoreCommitment(JSON.parse(json));
export const assertRestoreCommitmentList = typia.createAssertEquals<readonly Api.RestoreCommitment[]>();
export const parseRestoreCommitmentList = (json: string): readonly Api.RestoreCommitment[] =>
  assertRestoreCommitmentList(JSON.parse(json));

export const assertRestoreRequest = typia.createAssertEquals<Api.RestoreRequest>();
export const parseRestoreRequest = (json: string): Api.RestoreRequest => assertRestoreRequest(JSON.parse(json));
export const assertRestoreRequestList = typia.createAssertEquals<readonly Api.RestoreRequest[]>();
export const parseRestoreRequestList = (json: string): readonly Api.RestoreRequest[] =>
  assertRestoreRequestList(JSON.parse(json));

export const assertRetry = typia.createAssertEquals<Api.Retry>();
export const parseRetry = (json: string): Api.Retry => assertRetry(JSON.parse(json));
export const assertRetryList = typia.createAssertEquals<readonly Api.Retry[]>();
export const parseRetryList = (json: string): readonly Api.Retry[] => assertRetryList(JSON.parse(json));

export const assertRevisionTarget = typia.createAssertEquals<Api.RevisionTarget>();
export const parseRevisionTarget = (json: string): Api.RevisionTarget => assertRevisionTarget(JSON.parse(json));
export const assertRevisionTargetList = typia.createAssertEquals<readonly Api.RevisionTarget[]>();
export const parseRevisionTargetList = (json: string): readonly Api.RevisionTarget[] =>
  assertRevisionTargetList(JSON.parse(json));

export const assertRunSandboxMode = typia.createAssertEquals<Api.RunSandboxMode>();
export const parseRunSandboxMode = (json: string): Api.RunSandboxMode => assertRunSandboxMode(JSON.parse(json));
export const assertRunSandboxModeList = typia.createAssertEquals<readonly Api.RunSandboxMode[]>();
export const parseRunSandboxModeList = (json: string): readonly Api.RunSandboxMode[] =>
  assertRunSandboxModeList(JSON.parse(json));

export const assertSccacheStats = typia.createAssertEquals<Api.SccacheStats>();
export const parseSccacheStats = (json: string): Api.SccacheStats => assertSccacheStats(JSON.parse(json));
export const assertSccacheStatsList = typia.createAssertEquals<readonly Api.SccacheStats[]>();
export const parseSccacheStatsList = (json: string): readonly Api.SccacheStats[] =>
  assertSccacheStatsList(JSON.parse(json));

export const assertSccacheStatus = typia.createAssertEquals<Api.SccacheStatus>();
export const parseSccacheStatus = (json: string): Api.SccacheStatus => assertSccacheStatus(JSON.parse(json));
export const assertSccacheStatusList = typia.createAssertEquals<readonly Api.SccacheStatus[]>();
export const parseSccacheStatusList = (json: string): readonly Api.SccacheStatus[] =>
  assertSccacheStatusList(JSON.parse(json));

export const assertScriptCommand = typia.createAssertEquals<Api.ScriptCommand>();
export const parseScriptCommand = (json: string): Api.ScriptCommand => assertScriptCommand(JSON.parse(json));
export const assertScriptCommandList = typia.createAssertEquals<readonly Api.ScriptCommand[]>();
export const parseScriptCommandList = (json: string): readonly Api.ScriptCommand[] =>
  assertScriptCommandList(JSON.parse(json));

export const assertScriptValue = typia.createAssertEquals<Api.ScriptValue>();
export const parseScriptValue = (json: string): Api.ScriptValue => assertScriptValue(JSON.parse(json));
export const assertScriptValueList = typia.createAssertEquals<readonly Api.ScriptValue[]>();
export const parseScriptValueList = (json: string): readonly Api.ScriptValue[] =>
  assertScriptValueList(JSON.parse(json));

export const assertSealedJob = typia.createAssertEquals<Api.SealedJob>();
export const parseSealedJob = (json: string): Api.SealedJob => assertSealedJob(JSON.parse(json));
export const assertSealedJobList = typia.createAssertEquals<readonly Api.SealedJob[]>();
export const parseSealedJobList = (json: string): readonly Api.SealedJob[] => assertSealedJobList(JSON.parse(json));

export const assertSessionRequest = typia.createAssertEquals<Api.SessionRequest>();
export const parseSessionRequest = (json: string): Api.SessionRequest => assertSessionRequest(JSON.parse(json));
export const assertSessionRequestList = typia.createAssertEquals<readonly Api.SessionRequest[]>();
export const parseSessionRequestList = (json: string): readonly Api.SessionRequest[] =>
  assertSessionRequestList(JSON.parse(json));

export const assertSha256Digest = typia.createAssertEquals<Api.Sha256Digest>();
export const parseSha256Digest = (json: string): Api.Sha256Digest => assertSha256Digest(JSON.parse(json));
export const assertSha256DigestList = typia.createAssertEquals<readonly Api.Sha256Digest[]>();
export const parseSha256DigestList = (json: string): readonly Api.Sha256Digest[] =>
  assertSha256DigestList(JSON.parse(json));

export const assertSimVerb = typia.createAssertEquals<Api.SimVerb>();
export const parseSimVerb = (json: string): Api.SimVerb => assertSimVerb(JSON.parse(json));
export const assertSimVerbList = typia.createAssertEquals<readonly Api.SimVerb[]>();
export const parseSimVerbList = (json: string): readonly Api.SimVerb[] => assertSimVerbList(JSON.parse(json));

export const assertSkillInstall = typia.createAssertEquals<Api.SkillInstall>();
export const parseSkillInstall = (json: string): Api.SkillInstall => assertSkillInstall(JSON.parse(json));
export const assertSkillInstallList = typia.createAssertEquals<readonly Api.SkillInstall[]>();
export const parseSkillInstallList = (json: string): readonly Api.SkillInstall[] =>
  assertSkillInstallList(JSON.parse(json));

export const assertSkillInstallReport = typia.createAssertEquals<Api.SkillInstallReport>();
export const parseSkillInstallReport = (json: string): Api.SkillInstallReport =>
  assertSkillInstallReport(JSON.parse(json));
export const assertSkillInstallReportList = typia.createAssertEquals<readonly Api.SkillInstallReport[]>();
export const parseSkillInstallReportList = (json: string): readonly Api.SkillInstallReport[] =>
  assertSkillInstallReportList(JSON.parse(json));

export const assertSkillInstallStatus = typia.createAssertEquals<Api.SkillInstallStatus>();
export const parseSkillInstallStatus = (json: string): Api.SkillInstallStatus =>
  assertSkillInstallStatus(JSON.parse(json));
export const assertSkillInstallStatusList = typia.createAssertEquals<readonly Api.SkillInstallStatus[]>();
export const parseSkillInstallStatusList = (json: string): readonly Api.SkillInstallStatus[] =>
  assertSkillInstallStatusList(JSON.parse(json));

export const assertSlotRequest = typia.createAssertEquals<Api.SlotRequest>();
export const parseSlotRequest = (json: string): Api.SlotRequest => assertSlotRequest(JSON.parse(json));
export const assertSlotRequestList = typia.createAssertEquals<readonly Api.SlotRequest[]>();
export const parseSlotRequestList = (json: string): readonly Api.SlotRequest[] =>
  assertSlotRequestList(JSON.parse(json));

export const assertSlotResult = typia.createAssertEquals<Api.SlotResult>();
export const parseSlotResult = (json: string): Api.SlotResult => assertSlotResult(JSON.parse(json));
export const assertSlotResultList = typia.createAssertEquals<readonly Api.SlotResult[]>();
export const parseSlotResultList = (json: string): readonly Api.SlotResult[] => assertSlotResultList(JSON.parse(json));

export const assertSourceDestinationRequest = typia.createAssertEquals<Api.SourceDestinationRequest>();
export const parseSourceDestinationRequest = (json: string): Api.SourceDestinationRequest =>
  assertSourceDestinationRequest(JSON.parse(json));
export const assertSourceDestinationRequestList = typia.createAssertEquals<readonly Api.SourceDestinationRequest[]>();
export const parseSourceDestinationRequestList = (json: string): readonly Api.SourceDestinationRequest[] =>
  assertSourceDestinationRequestList(JSON.parse(json));

export const assertSpanId = typia.createAssertEquals<Api.SpanId>();
export const parseSpanId = (json: string): Api.SpanId => assertSpanId(JSON.parse(json));
export const assertSpanIdList = typia.createAssertEquals<readonly Api.SpanId[]>();
export const parseSpanIdList = (json: string): readonly Api.SpanId[] => assertSpanIdList(JSON.parse(json));

export const assertStaleDaemonBinary = typia.createAssertEquals<Api.StaleDaemonBinary>();
export const parseStaleDaemonBinary = (json: string): Api.StaleDaemonBinary =>
  assertStaleDaemonBinary(JSON.parse(json));
export const assertStaleDaemonBinaryList = typia.createAssertEquals<readonly Api.StaleDaemonBinary[]>();
export const parseStaleDaemonBinaryList = (json: string): readonly Api.StaleDaemonBinary[] =>
  assertStaleDaemonBinaryList(JSON.parse(json));

export const assertStartupHeal = typia.createAssertEquals<Api.StartupHeal>();
export const parseStartupHeal = (json: string): Api.StartupHeal => assertStartupHeal(JSON.parse(json));
export const assertStartupHealList = typia.createAssertEquals<readonly Api.StartupHeal[]>();
export const parseStartupHealList = (json: string): readonly Api.StartupHeal[] =>
  assertStartupHealList(JSON.parse(json));

export const assertStdinInfo = typia.createAssertEquals<Api.StdinInfo>();
export const parseStdinInfo = (json: string): Api.StdinInfo => assertStdinInfo(JSON.parse(json));
export const assertStdinInfoList = typia.createAssertEquals<readonly Api.StdinInfo[]>();
export const parseStdinInfoList = (json: string): readonly Api.StdinInfo[] => assertStdinInfoList(JSON.parse(json));

export const assertStdinKind = typia.createAssertEquals<Api.StdinKind>();
export const parseStdinKind = (json: string): Api.StdinKind => assertStdinKind(JSON.parse(json));
export const assertStdinKindList = typia.createAssertEquals<readonly Api.StdinKind[]>();
export const parseStdinKindList = (json: string): readonly Api.StdinKind[] => assertStdinKindList(JSON.parse(json));

export const assertStepReport = typia.createAssertEquals<Api.StepReport>();
export const parseStepReport = (json: string): Api.StepReport => assertStepReport(JSON.parse(json));
export const assertStepReportList = typia.createAssertEquals<readonly Api.StepReport[]>();
export const parseStepReportList = (json: string): readonly Api.StepReport[] => assertStepReportList(JSON.parse(json));

export const assertStorageIoBytes = typia.createAssertEquals<Api.StorageIoBytes>();
export const parseStorageIoBytes = (json: string): Api.StorageIoBytes => assertStorageIoBytes(JSON.parse(json));
export const assertStorageIoBytesList = typia.createAssertEquals<readonly Api.StorageIoBytes[]>();
export const parseStorageIoBytesList = (json: string): readonly Api.StorageIoBytes[] =>
  assertStorageIoBytesList(JSON.parse(json));

export const assertStreamInfo = typia.createAssertEquals<Api.StreamInfo>();
export const parseStreamInfo = (json: string): Api.StreamInfo => assertStreamInfo(JSON.parse(json));
export const assertStreamInfoList = typia.createAssertEquals<readonly Api.StreamInfo[]>();
export const parseStreamInfoList = (json: string): readonly Api.StreamInfo[] => assertStreamInfoList(JSON.parse(json));

export const assertStreamInfoRef = typia.createAssertEquals<Api.StreamInfoRef>();
export const parseStreamInfoRef = (json: string): Api.StreamInfoRef => assertStreamInfoRef(JSON.parse(json));
export const assertStreamInfoRefList = typia.createAssertEquals<readonly Api.StreamInfoRef[]>();
export const parseStreamInfoRefList = (json: string): readonly Api.StreamInfoRef[] =>
  assertStreamInfoRefList(JSON.parse(json));

export const assertSupervisorRecovery = typia.createAssertEquals<Api.SupervisorRecovery>();
export const parseSupervisorRecovery = (json: string): Api.SupervisorRecovery =>
  assertSupervisorRecovery(JSON.parse(json));
export const assertSupervisorRecoveryList = typia.createAssertEquals<readonly Api.SupervisorRecovery[]>();
export const parseSupervisorRecoveryList = (json: string): readonly Api.SupervisorRecovery[] =>
  assertSupervisorRecoveryList(JSON.parse(json));

export const assertTaggedBytesEncoding = typia.createAssertEquals<Api.TaggedBytesEncoding>();
export const parseTaggedBytesEncoding = (json: string): Api.TaggedBytesEncoding =>
  assertTaggedBytesEncoding(JSON.parse(json));
export const assertTaggedBytesEncodingList = typia.createAssertEquals<readonly Api.TaggedBytesEncoding[]>();
export const parseTaggedBytesEncodingList = (json: string): readonly Api.TaggedBytesEncoding[] =>
  assertTaggedBytesEncodingList(JSON.parse(json));

export const assertTaggedBytesRef = typia.createAssertEquals<Api.TaggedBytesRef>();
export const parseTaggedBytesRef = (json: string): Api.TaggedBytesRef => assertTaggedBytesRef(JSON.parse(json));
export const assertTaggedBytesRefList = typia.createAssertEquals<readonly Api.TaggedBytesRef[]>();
export const parseTaggedBytesRefList = (json: string): readonly Api.TaggedBytesRef[] =>
  assertTaggedBytesRefList(JSON.parse(json));

export const assertTailRequest = typia.createAssertEquals<Api.TailRequest>();
export const parseTailRequest = (json: string): Api.TailRequest => assertTailRequest(JSON.parse(json));
export const assertTailRequestList = typia.createAssertEquals<readonly Api.TailRequest[]>();
export const parseTailRequestList = (json: string): readonly Api.TailRequest[] =>
  assertTailRequestList(JSON.parse(json));

export const assertTerminalCommitment = typia.createAssertEquals<Api.TerminalCommitment>();
export const parseTerminalCommitment = (json: string): Api.TerminalCommitment =>
  assertTerminalCommitment(JSON.parse(json));
export const assertTerminalCommitmentList = typia.createAssertEquals<readonly Api.TerminalCommitment[]>();
export const parseTerminalCommitmentList = (json: string): readonly Api.TerminalCommitment[] =>
  assertTerminalCommitmentList(JSON.parse(json));

export const assertTraceContext = typia.createAssertEquals<Api.TraceContext>();
export const parseTraceContext = (json: string): Api.TraceContext => assertTraceContext(JSON.parse(json));
export const assertTraceContextList = typia.createAssertEquals<readonly Api.TraceContext[]>();
export const parseTraceContextList = (json: string): readonly Api.TraceContext[] =>
  assertTraceContextList(JSON.parse(json));

export const assertTraceId = typia.createAssertEquals<Api.TraceId>();
export const parseTraceId = (json: string): Api.TraceId => assertTraceId(JSON.parse(json));
export const assertTraceIdList = typia.createAssertEquals<readonly Api.TraceId[]>();
export const parseTraceIdList = (json: string): readonly Api.TraceId[] => assertTraceIdList(JSON.parse(json));

export const assertUnattributedCheck = typia.createAssertEquals<Api.UnattributedCheck>();
export const parseUnattributedCheck = (json: string): Api.UnattributedCheck =>
  assertUnattributedCheck(JSON.parse(json));
export const assertUnattributedCheckList = typia.createAssertEquals<readonly Api.UnattributedCheck[]>();
export const parseUnattributedCheckList = (json: string): readonly Api.UnattributedCheck[] =>
  assertUnattributedCheckList(JSON.parse(json));

export const assertUnattributedRun = typia.createAssertEquals<Api.UnattributedRun>();
export const parseUnattributedRun = (json: string): Api.UnattributedRun => assertUnattributedRun(JSON.parse(json));
export const assertUnattributedRunList = typia.createAssertEquals<readonly Api.UnattributedRun[]>();
export const parseUnattributedRunList = (json: string): readonly Api.UnattributedRun[] =>
  assertUnattributedRunList(JSON.parse(json));

export const assertUtcTimestamp = typia.createAssertEquals<Api.UtcTimestamp>();
export const parseUtcTimestamp = (json: string): Api.UtcTimestamp => assertUtcTimestamp(JSON.parse(json));
export const assertUtcTimestampList = typia.createAssertEquals<readonly Api.UtcTimestamp[]>();
export const parseUtcTimestampList = (json: string): readonly Api.UtcTimestamp[] =>
  assertUtcTimestampList(JSON.parse(json));

export const assertWorkerScope = typia.createAssertEquals<Api.WorkerScope>();
export const parseWorkerScope = (json: string): Api.WorkerScope => assertWorkerScope(JSON.parse(json));
export const assertWorkerScopeList = typia.createAssertEquals<readonly Api.WorkerScope[]>();
export const parseWorkerScopeList = (json: string): readonly Api.WorkerScope[] =>
  assertWorkerScopeList(JSON.parse(json));

export const assertWorkerView = typia.createAssertEquals<Api.WorkerView>();
export const parseWorkerView = (json: string): Api.WorkerView => assertWorkerView(JSON.parse(json));
export const assertWorkerViewList = typia.createAssertEquals<readonly Api.WorkerView[]>();
export const parseWorkerViewList = (json: string): readonly Api.WorkerView[] => assertWorkerViewList(JSON.parse(json));

export const assertWorkspaceAtRequest = typia.createAssertEquals<Api.WorkspaceAtRequest>();
export const parseWorkspaceAtRequest = (json: string): Api.WorkspaceAtRequest =>
  assertWorkspaceAtRequest(JSON.parse(json));
export const assertWorkspaceAtRequestList = typia.createAssertEquals<readonly Api.WorkspaceAtRequest[]>();
export const parseWorkspaceAtRequestList = (json: string): readonly Api.WorkspaceAtRequest[] =>
  assertWorkspaceAtRequestList(JSON.parse(json));

export const assertWorkspaceAttachRequest = typia.createAssertEquals<Api.WorkspaceAttachRequest>();
export const parseWorkspaceAttachRequest = (json: string): Api.WorkspaceAttachRequest =>
  assertWorkspaceAttachRequest(JSON.parse(json));
export const assertWorkspaceAttachRequestList = typia.createAssertEquals<readonly Api.WorkspaceAttachRequest[]>();
export const parseWorkspaceAttachRequestList = (json: string): readonly Api.WorkspaceAttachRequest[] =>
  assertWorkspaceAttachRequestList(JSON.parse(json));

export const assertWorkspaceGrantsRequest = typia.createAssertEquals<Api.WorkspaceGrantsRequest>();
export const parseWorkspaceGrantsRequest = (json: string): Api.WorkspaceGrantsRequest =>
  assertWorkspaceGrantsRequest(JSON.parse(json));
export const assertWorkspaceGrantsRequestList = typia.createAssertEquals<readonly Api.WorkspaceGrantsRequest[]>();
export const parseWorkspaceGrantsRequestList = (json: string): readonly Api.WorkspaceGrantsRequest[] =>
  assertWorkspaceGrantsRequestList(JSON.parse(json));

export const assertWorkspaceIncarnation = typia.createAssertEquals<Api.WorkspaceIncarnation>();
export const parseWorkspaceIncarnation = (json: string): Api.WorkspaceIncarnation =>
  assertWorkspaceIncarnation(JSON.parse(json));
export const assertWorkspaceIncarnationList = typia.createAssertEquals<readonly Api.WorkspaceIncarnation[]>();
export const parseWorkspaceIncarnationList = (json: string): readonly Api.WorkspaceIncarnation[] =>
  assertWorkspaceIncarnationList(JSON.parse(json));

export const assertWorkspaceInfo = typia.createAssertEquals<Api.WorkspaceInfo>();
export const parseWorkspaceInfo = (json: string): Api.WorkspaceInfo => assertWorkspaceInfo(JSON.parse(json));
export const assertWorkspaceInfoList = typia.createAssertEquals<readonly Api.WorkspaceInfo[]>();
export const parseWorkspaceInfoList = (json: string): readonly Api.WorkspaceInfo[] =>
  assertWorkspaceInfoList(JSON.parse(json));

export const assertWorkspaceIntroducedCommitment = typia.createAssertEquals<Api.WorkspaceIntroducedCommitment>();
export const parseWorkspaceIntroducedCommitment = (json: string): Api.WorkspaceIntroducedCommitment =>
  assertWorkspaceIntroducedCommitment(JSON.parse(json));
export const assertWorkspaceIntroducedCommitmentList =
  typia.createAssertEquals<readonly Api.WorkspaceIntroducedCommitment[]>();
export const parseWorkspaceIntroducedCommitmentList = (json: string): readonly Api.WorkspaceIntroducedCommitment[] =>
  assertWorkspaceIntroducedCommitmentList(JSON.parse(json));

export const assertWorkspaceLanding = typia.createAssertEquals<Api.WorkspaceLanding>();
export const parseWorkspaceLanding = (json: string): Api.WorkspaceLanding => assertWorkspaceLanding(JSON.parse(json));
export const assertWorkspaceLandingList = typia.createAssertEquals<readonly Api.WorkspaceLanding[]>();
export const parseWorkspaceLandingList = (json: string): readonly Api.WorkspaceLanding[] =>
  assertWorkspaceLandingList(JSON.parse(json));

export const assertWorkspaceName = typia.createAssertEquals<Api.WorkspaceName>();
export const parseWorkspaceName = (json: string): Api.WorkspaceName => assertWorkspaceName(JSON.parse(json));
export const assertWorkspaceNameList = typia.createAssertEquals<readonly Api.WorkspaceName[]>();
export const parseWorkspaceNameList = (json: string): readonly Api.WorkspaceName[] =>
  assertWorkspaceNameList(JSON.parse(json));

export const assertWorkspacePath = typia.createAssertEquals<Api.WorkspacePath>();
export const parseWorkspacePath = (json: string): Api.WorkspacePath => assertWorkspacePath(JSON.parse(json));
export const assertWorkspacePathList = typia.createAssertEquals<readonly Api.WorkspacePath[]>();
export const parseWorkspacePathList = (json: string): readonly Api.WorkspacePath[] =>
  assertWorkspacePathList(JSON.parse(json));

export const assertWorkspaceRequest = typia.createAssertEquals<Api.WorkspaceRequest>();
export const parseWorkspaceRequest = (json: string): Api.WorkspaceRequest => assertWorkspaceRequest(JSON.parse(json));
export const assertWorkspaceRequestList = typia.createAssertEquals<readonly Api.WorkspaceRequest[]>();
export const parseWorkspaceRequestList = (json: string): readonly Api.WorkspaceRequest[] =>
  assertWorkspaceRequestList(JSON.parse(json));

export const assertWorkspaceRetiredCommitment = typia.createAssertEquals<Api.WorkspaceRetiredCommitment>();
export const parseWorkspaceRetiredCommitment = (json: string): Api.WorkspaceRetiredCommitment =>
  assertWorkspaceRetiredCommitment(JSON.parse(json));
export const assertWorkspaceRetiredCommitmentList =
  typia.createAssertEquals<readonly Api.WorkspaceRetiredCommitment[]>();
export const parseWorkspaceRetiredCommitmentList = (json: string): readonly Api.WorkspaceRetiredCommitment[] =>
  assertWorkspaceRetiredCommitmentList(JSON.parse(json));

export const assertWorkspaceRole = typia.createAssertEquals<Api.WorkspaceRole>();
export const parseWorkspaceRole = (json: string): Api.WorkspaceRole => assertWorkspaceRole(JSON.parse(json));
export const assertWorkspaceRoleList = typia.createAssertEquals<readonly Api.WorkspaceRole[]>();
export const parseWorkspaceRoleList = (json: string): readonly Api.WorkspaceRole[] =>
  assertWorkspaceRoleList(JSON.parse(json));

export const assertWorkspaceState = typia.createAssertEquals<Api.WorkspaceState>();
export const parseWorkspaceState = (json: string): Api.WorkspaceState => assertWorkspaceState(JSON.parse(json));
export const assertWorkspaceStateList = typia.createAssertEquals<readonly Api.WorkspaceState[]>();
export const parseWorkspaceStateList = (json: string): readonly Api.WorkspaceState[] =>
  assertWorkspaceStateList(JSON.parse(json));

export const assertWorkspaceTarget = typia.createAssertEquals<Api.WorkspaceTarget>();
export const parseWorkspaceTarget = (json: string): Api.WorkspaceTarget => assertWorkspaceTarget(JSON.parse(json));
export const assertWorkspaceTargetList = typia.createAssertEquals<readonly Api.WorkspaceTarget[]>();
export const parseWorkspaceTargetList = (json: string): readonly Api.WorkspaceTarget[] =>
  assertWorkspaceTargetList(JSON.parse(json));

export const assertWorkspaceView = typia.createAssertEquals<Api.WorkspaceView>();
export const parseWorkspaceView = (json: string): Api.WorkspaceView => assertWorkspaceView(JSON.parse(json));
export const assertWorkspaceViewList = typia.createAssertEquals<readonly Api.WorkspaceView[]>();
export const parseWorkspaceViewList = (json: string): readonly Api.WorkspaceView[] =>
  assertWorkspaceViewList(JSON.parse(json));
