/**
 * WASM-backed SpanBuffer class generation.
 *
 * Implements spec 01q: WASM Memory Architecture for SpanBuffer Storage
 *
 * Key differences from JS SpanBuffer:
 * - System columns (timestamp, entry_type) live in WASM memory at _systemPtr
 * - Numeric columns allocated lazily from WASM freelists
 * - String columns (category, text) remain as JS string[] arrays
 * - All TypedArray views created on-demand from WASM memory.buffer
 */

import { getSchemaType } from '@smoothbricks/arrow-builder';
import { checkCapacityTuning } from '../capacityTuning.js';
import type { OpMetadata } from '../op.js';
import type { LogSchema } from '../schema/LogSchema.js';
import type { SpanBufferStats } from '../spanBufferStats.js';
import type { ITraceRoot } from '../traceRoot.js';
import type { WasmAllocator } from './wasmAllocator.js';

// =============================================================================
// Types
// =============================================================================

/**
 * Options for creating a ROOT WASM SpanBuffer instance.
 * Thread ID comes from WASM header, span_id generated by WASM.
 */
export interface WasmSpanBufferRootOptions {
  /** WASM allocator for memory management */
  allocator: WasmAllocator;
  /** Buffer capacity (rows) */
  capacity: number;
  /** Span name (written to row 0 message column) */
  spanName: string;
  /** Trace ID (string UUID) - stored in identity block */
  trace_id: string;
  /** Log schema defining columns */
  logSchema: LogSchema;
}

/**
 * Options for creating a CHILD WASM SpanBuffer instance.
 * Inherits trace_id from parent, span_id generated by WASM.
 */
export interface WasmSpanBufferChildOptions {
  /** Parent buffer to link to */
  parent: WasmSpanBufferInstance;
  /** Span name (written to row 0 message column) */
  spanName: string;
  /** Buffer capacity (rows) - optional, inherits from parent */
  capacity?: number;
}

// Legacy options type for compatibility during migration
export interface WasmSpanBufferOptions {
  allocator: WasmAllocator;
  capacity: number;
  trace_id: string;
  thread_id: bigint;
  span_id: number;
  parent_thread_id?: bigint;
  parent_span_id?: number;
  logSchema: LogSchema;
  _traceRoot: ITraceRoot;
  _scopeValues: Readonly<Record<string, unknown>>;
  _opMetadata: OpMetadata;
  _callsiteMetadata: OpMetadata;
}

/**
 * WASM SpanBuffer instance interface.
 * Mirrors AnySpanBuffer but with WASM-specific internals.
 */
export interface WasmSpanBufferInstance {
  // ===========================================================================
  // Identity (same as JS SpanBuffer)
  // ===========================================================================
  readonly trace_id: string;
  readonly thread_id: bigint;
  readonly span_id: number;
  readonly parent_thread_id: bigint;
  readonly parent_span_id: number;
  readonly _hasParent: boolean;

  // ===========================================================================
  // Capacity and write tracking
  // ===========================================================================
  readonly _capacity: number;
  _writeIndex: number;

  // ===========================================================================
  // Cached WASM function refs (hot path optimization)
  // ===========================================================================
  readonly _writeColF64: (colOffset: number, rowIdx: number, value: number, capacity: number) => number;
  readonly _writeColU32: (colOffset: number, rowIdx: number, value: number, capacity: number) => number;
  readonly _writeColU8: (colOffset: number, rowIdx: number, value: number, capacity: number) => number;
  readonly _writeLogEntry: (
    systemPtr: number,
    identityPtr: number,
    traceRootPtr: number,
    entryType: number,
    capacity: number,
  ) => number;

  // ===========================================================================
  // WASM pointers
  // ===========================================================================
  /** Byte offset into WASM memory for system columns (timestamp + entry_type) */
  readonly _systemPtr: number;
  /** Byte offset into WASM memory for identity block (writeIndex, span_id, trace_id) */
  readonly _identityPtr: number;
  /** Array of byte offsets for each column (-1 = not allocated) */
  readonly _columnPtrs: Int32Array;
  /** Reference to the WASM allocator */
  readonly _allocator: WasmAllocator;

  // ===========================================================================
  // Schema
  // ===========================================================================
  readonly _logSchema: LogSchema;

  // ===========================================================================
  // Tree structure
  // ===========================================================================
  _parent: WasmSpanBufferInstance | null;
  _children: WasmSpanBufferInstance[];
  _overflow: WasmSpanBufferInstance | null;

  // ===========================================================================
  // System column views (created on demand from WASM memory)
  // ===========================================================================
  get timestamp(): BigInt64Array;
  get entry_type(): Uint8Array;

  // ===========================================================================
  // Message column (system, eager string)
  // ===========================================================================
  readonly _message: string[];
  message(idx: number, value: string): this;

  // ===========================================================================
  // Methods
  // ===========================================================================
  /** Free all WASM memory for this buffer */
  free(): void;

  /** Check if column is allocated */
  isColumnAllocated(columnIndex: number): boolean;

  /** Get column values array if allocated */
  getColumnIfAllocated(columnName: string): unknown;

  /** Get column nulls array if allocated */
  getNullsIfAllocated(columnName: string): Uint8Array | undefined;
}

/**
 * Constructor type for generated WASM SpanBuffer classes.
 */
export interface WasmSpanBufferConstructor {
  new (opts: WasmSpanBufferOptions): WasmSpanBufferInstance;
  readonly schema: LogSchema;
  stats: SpanBufferStats; // Mutable stats shared across all instances
}

// =============================================================================
// Column Metadata
// =============================================================================

/**
 * Size class for WASM allocation (determines which freelist to use).
 */
type SizeClass = '1b' | '4b' | '8b' | 'string';

/**
 * Metadata for a single column - used during code generation.
 */
interface ColumnMeta {
  /** Column name from schema */
  name: string;
  /** WASM allocation size class */
  sizeClass: SizeClass;
  /** Schema type (enum, category, text, number, etc.) */
  schemaType: string;
  /** Index in the _columnPtrs array */
  columnIndex: number;
  /** Whether this column is eager (always allocated) */
  isEager: boolean;
  /** Enum values if schemaType === 'enum' */
  enumValues?: readonly string[];
}

/**
 * Build column metadata array from schema.
 * Maps each schema field to its storage characteristics.
 */
function buildColumnMeta(schema: LogSchema): ColumnMeta[] {
  const result: ColumnMeta[] = [];
  const fields = schema.fields;
  let columnIndex = 0;

  for (const name of schema._columnNames) {
    const field = fields[name];
    const schemaType = getSchemaType(field);
    const isEager = (field as { __eager?: boolean }).__eager === true;
    const enumValues = (field as { __enum_values?: readonly string[] }).__enum_values;

    let sizeClass: SizeClass;
    switch (schemaType) {
      case 'enum':
      case 'boolean':
        sizeClass = '1b';
        break;
      case 'number':
      case 'bigUint64':
        sizeClass = '8b';
        break;
      case 'category':
      case 'text':
        sizeClass = 'string';
        break;
      default:
        sizeClass = '8b'; // Default to largest for unknown types
    }

    result.push({
      name,
      sizeClass,
      schemaType: schemaType ?? 'unknown',
      columnIndex,
      isEager,
      enumValues,
    });
    columnIndex++;
  }

  return result;
}

// =============================================================================
// Code Generation Helpers
// =============================================================================

/**
 * Generate constructor body code.
 * Note: For root buffers, identity is allocated with trace_id.
 * For child buffers, identity is allocated without trace_id.
 * The constructor handles both via opts.trace_id presence.
 */
function generateConstructorCode(columnMeta: ColumnMeta[]): string {
  const lines: string[] = [
    // Store allocator and capacity
    'this._allocator = opts.allocator;',
    'this._capacity = opts.capacity;',
    // Note: _logSchema, _columns, and _stats are provided by getters (not stored)
    '',
    // Cache WASM function refs for hot path (avoid allocator wrapper indirection)
    'const exports = opts.allocator.exports;',
    'this._writeColF64 = exports.write_col_f64;',
    'this._writeColU32 = exports.write_col_u32;',
    'this._writeColU8 = exports.write_col_u8;',
    'this._writeLogEntry = exports.write_log_entry;',
    '',
    // Allocate identity block from WASM (root has trace_id, child does not)
    'if (opts.trace_id) {',
    '  // Root buffer: allocate identity with trace_id',
    '  const traceIdBytes = new TextEncoder().encode(opts.trace_id);',
    '  const packed = opts.allocator.allocIdentityRootForJsWrite(traceIdBytes.length);',
    '  this._identityPtr = Number(packed >> 32n);  // Upper 32 bits = identity offset',
    '  const traceIdOffset = Number(packed & 0xFFFFFFFFn);  // Lower 32 bits = trace_id field offset',
    '  // Write trace_id bytes directly to identity block (no scratch, no allocator.u8)',
    '  new Uint8Array(opts.allocator.memory.buffer).set(traceIdBytes, traceIdOffset);',
    '} else {',
    '  // Child buffer: allocate identity without trace_id',
    '  this._identityPtr = opts.allocator.allocIdentityChild();',
    '}',
    '',
    // Allocate system block from WASM
    'this._systemPtr = opts.allocator.allocSpanSystem();',
    '',
    // Initialize column pointers as unallocated (-1)
    `this._columnPtrs = new Int32Array(${columnMeta.length}).fill(-1);`,
    '',
    // Tree structure
    'this._parent = null;',
    'this._children = [];',
    'this._overflow = null;',
    '',
    // Assign context properties from opts
    'this._traceRoot = opts._traceRoot;',
    'this._scopeValues = opts._scopeValues;',
    'this._opMetadata = opts._opMetadata;',
    'this._callsiteMetadata = opts._callsiteMetadata;',
    '',
    // Initialize string arrays for string columns and eager message
    'this._message = new Array(opts.capacity);',
  ];

  // Initialize string arrays for string columns
  // Note: 'message' is handled separately above with this._message
  for (const col of columnMeta) {
    // Skip 'message' - handled specially above
    if (col.name === 'message') {
      continue;
    }

    if (col.sizeClass === 'string') {
      if (col.isEager) {
        lines.push(`this._${col.name}_values = new Array(opts.capacity);`);
      } else {
        // Lazy string columns start as undefined
        lines.push(`this._${col.name}_values = undefined;`);
        lines.push(`this._${col.name}_nulls = undefined;`);
      }
    } else if (col.isEager) {
      // Eager non-string columns: pre-allocate from WASM
      lines.push(`this._columnPtrs[${col.columnIndex}] = opts.allocator.alloc${col.sizeClass.toUpperCase()}();`);
    }
  }

  return lines.join('\n    ');
}

/**
 * Generate getter for timestamp system column.
 */
function generateTimestampGetter(): string {
  return `get timestamp() {
    return new BigInt64Array(
      this._allocator.memory.buffer,
      this._systemPtr,
      this._capacity
    );
  }`;
}

/**
 * Generate getter for entry_type system column.
 */
function generateEntryTypeGetter(): string {
  return `get entry_type() {
    return new Uint8Array(
      this._allocator.memory.buffer,
      this._systemPtr + this._capacity * 8,
      this._capacity
    );
  }`;
}

/**
 * Generate message column methods (eager string, system column).
 * Includes both the setter method and the _values getter for SpanLogger compatibility.
 */
function generateMessageMethods(): string {
  return `message(idx, value) {
    this._message[idx] = value;
    return this;
  }
  
  get message_values() {
    return this._message;
  }
  
  get message_nulls() {
    return undefined;
  }`;
}

/**
 * Generate setter method for a numeric column (stored in WASM).
 */
function generateNumericSetter(col: ColumnMeta): string {
  const allocMethod = `alloc${col.sizeClass.toUpperCase()}`;
  const writeMethod =
    col.schemaType === 'number'
      ? 'writeColF64'
      : col.schemaType === 'bigUint64'
        ? 'writeColF64' // BigUint64 uses F64 write for now
        : col.sizeClass === '1b'
          ? 'writeColU8'
          : col.sizeClass === '4b'
            ? 'writeColU32'
            : 'writeColF64';

  if (col.isEager) {
    // Eager: column is pre-allocated, just write value
    return `${col.name}(idx, value) {
    const ptr = this._columnPtrs[${col.columnIndex}];
    this._${writeMethod}(ptr, idx, value, this._capacity);
    return this;
  }`;
  }

  // Lazy: allocate on first write
  return `${col.name}(idx, value) {
    let ptr = this._columnPtrs[${col.columnIndex}];
    if (ptr < 0) {
      ptr = this._allocator.${allocMethod}();
      this._columnPtrs[${col.columnIndex}] = ptr;
    }
    this._${writeMethod}(ptr, idx, value, this._capacity);
    return this;
  }`;
}

/**
 * Generate getter for numeric column values (creates view on demand).
 */
function generateNumericValuesGetter(col: ColumnMeta): string {
  const arrayType =
    col.schemaType === 'number'
      ? 'Float64Array'
      : col.schemaType === 'bigUint64'
        ? 'BigUint64Array'
        : col.sizeClass === '1b'
          ? 'Uint8Array'
          : col.sizeClass === '4b'
            ? 'Uint32Array'
            : 'Float64Array';

  const bytesPerElement = col.sizeClass === '1b' ? 1 : col.sizeClass === '4b' ? 4 : 8;

  return `get ${col.name}_values() {
    const ptr = this._columnPtrs[${col.columnIndex}];
    if (ptr < 0) return ${col.isEager ? 'null' : 'undefined'};
    const nullBitmapSize = Math.ceil(this._capacity / 8);
    const valueOffset = ptr + nullBitmapSize;
    // Align offset for typed array
    const alignedOffset = (valueOffset + ${bytesPerElement - 1}) & ~${bytesPerElement - 1};
    return new ${arrayType}(
      this._allocator.memory.buffer,
      alignedOffset,
      this._capacity
    );
  }`;
}

/**
 * Generate getter for numeric column nulls bitmap.
 */
function generateNumericNullsGetter(col: ColumnMeta): string {
  if (col.isEager) {
    // Eager columns don't have null bitmaps
    return `get ${col.name}_nulls() {
    return undefined;
  }`;
  }

  return `get ${col.name}_nulls() {
    const ptr = this._columnPtrs[${col.columnIndex}];
    if (ptr < 0) return undefined;
    const nullBitmapSize = Math.ceil(this._capacity / 8);
    return new Uint8Array(
      this._allocator.memory.buffer,
      ptr,
      nullBitmapSize
    );
  }`;
}

/**
 * Generate setter method for a string column (stored in JS).
 */
function generateStringSetter(col: ColumnMeta): string {
  if (col.isEager) {
    return `${col.name}(idx, value) {
    this._${col.name}_values[idx] = value;
    return this;
  }`;
  }

  // Lazy string column: allocate arrays on first write
  return `${col.name}(idx, value) {
    if (this._${col.name}_values === undefined) {
      this._${col.name}_values = new Array(this._capacity);
      const nullBitmapSize = Math.ceil(this._capacity / 8);
      this._${col.name}_nulls = new Uint8Array(nullBitmapSize);
    }
    if (value == null) {
      // Clear validity bit
      this._${col.name}_nulls[idx >>> 3] &= ~(1 << (idx & 7));
    } else {
      this._${col.name}_values[idx] = value;
      // Set validity bit
      this._${col.name}_nulls[idx >>> 3] |= (1 << (idx & 7));
    }
    return this;
  }`;
}

/**
 * Generate getter for string column values.
 */
function generateStringValuesGetter(col: ColumnMeta): string {
  if (col.isEager) {
    return `get ${col.name}_values() {
    return this._${col.name}_values;
  }`;
  }

  return `get ${col.name}_values() {
    return this._${col.name}_values;
  }`;
}

/**
 * Generate getter for string column nulls.
 */
function generateStringNullsGetter(col: ColumnMeta): string {
  if (col.isEager) {
    return `get ${col.name}_nulls() {
    return undefined;
  }`;
  }

  return `get ${col.name}_nulls() {
    return this._${col.name}_nulls;
  }`;
}

/**
 * Generate column methods for all schema columns.
 * Note: 'message' column is handled specially by generateMessageMethods() and excluded here.
 */
function generateColumnMethods(columnMeta: ColumnMeta[]): string {
  const methods: string[] = [];

  for (const col of columnMeta) {
    // Skip 'message' - handled specially by generateMessageMethods()
    if (col.name === 'message') {
      continue;
    }

    if (col.sizeClass === 'string') {
      methods.push(generateStringSetter(col));
      methods.push(generateStringValuesGetter(col));
      methods.push(generateStringNullsGetter(col));
    } else {
      methods.push(generateNumericSetter(col));
      methods.push(generateNumericValuesGetter(col));
      methods.push(generateNumericNullsGetter(col));
    }
  }

  return methods.join('\n\n  ');
}

/**
 * Generate free() method to return all WASM memory to freelists.
 */
function generateFreeMethod(columnMeta: ColumnMeta[]): string {
  const freeStatements: string[] = [
    '// Free identity block',
    'this._allocator.freeIdentity(this._identityPtr);',
    '',
    '// Free system block',
    'this._allocator.freeSpanSystem(this._systemPtr);',
    '',
    '// Free column blocks',
  ];

  for (const col of columnMeta) {
    if (col.sizeClass !== 'string') {
      const freeMethod = `free${col.sizeClass.toUpperCase()}`;
      freeStatements.push(`if (this._columnPtrs[${col.columnIndex}] >= 0) {
      this._allocator.${freeMethod}(this._columnPtrs[${col.columnIndex}]);
    }`);
    }
  }

  return `free() {
    ${freeStatements.join('\n    ')}
  }`;
}

/**
 * Generate identity getters.
 * Identity data is stored in WASM memory at _identityPtr:
 * - writeIndex: u32 at offset 0 (managed separately via _writeIndex getter)
 * - span_id: u32 at offset 4
 * - trace_id_len: u8 at offset 8
 * - trace_id: u8[128] at offset 9
 * Thread ID is global in WASM header, accessed via getThreadIdHigh/Low.
 * Parent info is stored in JS (parent buffer reference).
 */
function generateIdentityGetters(): string {
  return `get trace_id() {
    // Read trace_id from WASM identity block
    const len = this._allocator.readIdentityTraceIdLen(this._identityPtr);
    if (len === 0) {
      // Child buffer - get trace_id from root parent
      let p = this._parent;
      while (p && p._parent) p = p._parent;
      return p ? p.trace_id : '';
    }
    const traceIdPtr = this._allocator.getIdentityTraceIdPtr(this._identityPtr);
    return new TextDecoder().decode(
      new Uint8Array(this._allocator.memory.buffer, traceIdPtr, len)
    );
  }
  get thread_id() {
    // Thread ID is global in WASM header
    const high = this._allocator.getThreadIdHigh();
    const low = this._allocator.getThreadIdLow();
    return (BigInt(high) << 32n) | BigInt(low >>> 0);
  }
  get span_id() {
    return this._allocator.readIdentitySpanId(this._identityPtr);
  }
  get parent_thread_id() {
    // Parent info comes from parent buffer reference
    return this._parent ? this._parent.thread_id : 0n;
  }
  get parent_span_id() {
    return this._parent ? this._parent.span_id : 0;
  }
  get _hasParent() { return this._parent !== null; }`;
}

/**
 * Generate utility methods.
 */
function generateUtilityMethods(columnMeta: ColumnMeta[]): string {
  const columnNameToIndex = columnMeta.reduce(
    (acc, col, idx) => {
      acc[col.name] = idx;
      return acc;
    },
    {} as Record<string, number>,
  );

  return `get _stats() {
    return this.constructor.stats;
  }

  get _logSchema() {
    return this.constructor.schema;
  }

  get _columns() {
    return this.constructor.schema._columns;
  }

  isColumnAllocated(columnIndex) {
    return this._columnPtrs[columnIndex] >= 0;
  }

  getColumnIfAllocated(columnName) {
    const COLUMN_NAME_TO_INDEX = ${JSON.stringify(columnNameToIndex)};
    const idx = COLUMN_NAME_TO_INDEX[columnName];
    if (idx === undefined) return undefined;
    // Try to get the values getter
    const getter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(this), columnName + '_values');
    if (getter && getter.get) {
      return getter.get.call(this);
    }
    return this['_' + columnName + '_values'];
  }

  getNullsIfAllocated(columnName) {
    // Try to get the nulls getter
    const getter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(this), columnName + '_nulls');
    if (getter && getter.get) {
      return getter.get.call(this);
    }
    return this['_' + columnName + '_nulls'];
  }`;
}

/**
 * Generate writeIndex getter/setter.
 * writeIndex is stored at offset 0 of the identity block.
 */
function generateWriteIndexAccessor(): string {
  return `get _writeIndex() {
    return this._allocator.readWriteIndex(this._identityPtr);
  }
  set _writeIndex(value) {
    // Write directly to WASM memory at identity block offset 0
    new DataView(this._allocator.memory.buffer).setUint32(this._identityPtr, value, true);
  }`;
}

/**
 * Generate custom inspect for debugging.
 */
function generateInspect(): string {
  return `[Symbol.for('nodejs.util.inspect.custom')](depth, opts) {
    return \`WasmSpanBuffer { _writeIndex: \${this._writeIndex}, _capacity: \${this._capacity}, trace_id: \${this.trace_id ?? 'N/A'}, _systemPtr: \${this._systemPtr} }\`;
  }`;
}

// =============================================================================
// Class Cache and Generation
// =============================================================================

/**
 * Cache for generated WASM SpanBuffer classes.
 * Key is the schema object reference (WeakMap for GC).
 */
const wasmSpanBufferClassCache = new WeakMap<LogSchema, WasmSpanBufferConstructor>();

/**
 * Generate a WASM SpanBuffer class for the given schema.
 *
 * Similar to getSpanBufferClass but uses WASM memory backing.
 *
 * @param schema - LogSchema defining the buffer structure
 * @returns WasmSpanBufferConstructor for creating buffer instances
 */
export function getWasmSpanBufferClass(schema: LogSchema): WasmSpanBufferConstructor {
  const cached = wasmSpanBufferClassCache.get(schema);
  if (cached) {
    return cached;
  }

  // Pre-compute column metadata
  const columnMeta = buildColumnMeta(schema);

  // Generate class code
  const classCode = `
class WasmSpanBuffer {
  constructor(opts) {
    ${generateConstructorCode(columnMeta)}
  }

  // writeIndex accessor (stored in WASM identity block)
  ${generateWriteIndexAccessor()}

  // Identity getters
  ${generateIdentityGetters()}

  // System column getters (create views on demand from WASM memory)
  ${generateTimestampGetter()}

  ${generateEntryTypeGetter()}

  // Message column (system, eager string)
  ${generateMessageMethods()}

  // Schema column methods
  ${generateColumnMethods(columnMeta)}

  // Free all WASM memory
  ${generateFreeMethod(columnMeta)}

  // Utility methods
  ${generateUtilityMethods(columnMeta)}

  // Overflow handling (called by SpanLogger._checkOverflow)
  getOrCreateOverflow() {
    if (this._overflow) return this._overflow;
    const tracer = this._traceRoot.tracer;
    tracer.onStatsWillResetFor(this);
    checkCapacityTuning(this.constructor.stats);
    return tracer.bufferStrategy.createOverflowBuffer(this);
  }

  // Custom inspect
  ${generateInspect()}
}

return WasmSpanBuffer;
`;

  // Create the class using Function constructor, passing checkCapacityTuning as dependency
  const factory = new Function('checkCapacityTuning', classCode) as (
    fn: typeof checkCapacityTuning,
  ) => WasmSpanBufferConstructor;
  const WasmSpanBufferClass = factory(checkCapacityTuning);

  // Add static schema property
  Object.defineProperty(WasmSpanBufferClass, 'schema', {
    value: schema,
    writable: false,
    enumerable: true,
    configurable: false,
  });

  // Add static stats property (required by SpanContext and arrow-builder's ColumnWriter)
  // This matches the structure in spanBuffer.ts
  // IMPORTANT: stats object itself must be writable so totalWrites++ and spansCreated++ can modify it
  const statsObject = {
    capacity: 64, // Default capacity, will be overridden by allocator
    totalWrites: 0,
    spansCreated: 0,
  };
  Object.defineProperty(WasmSpanBufferClass, 'stats', {
    value: statsObject,
    writable: true, // Allow the reference to be replaced if needed
    enumerable: true,
    configurable: true,
  });

  // Cache the class
  wasmSpanBufferClassCache.set(schema, WasmSpanBufferClass);

  return WasmSpanBufferClass;
}

// =============================================================================
// Factory Functions
// =============================================================================

/**
 * Create a WASM SpanBuffer instance.
 *
 * @param schema - LogSchema defining the buffer structure
 * @param opts - Options for buffer creation
 * @param _traceRoot - Trace root context
 * @param _scopeValues - Scope values for this span
 * @param _opMetadata - Op metadata for attribution
 * @param _callsiteMetadata - Callsite metadata for attribution
 * @returns WasmSpanBufferInstance
 */
export function createWasmSpanBuffer(
  schema: LogSchema,
  opts: Omit<WasmSpanBufferOptions, 'logSchema' | '_traceRoot' | '_scopeValues' | '_opMetadata' | '_callsiteMetadata'>,
  _traceRoot: ITraceRoot,
  _scopeValues: Readonly<Record<string, unknown>>,
  _opMetadata: OpMetadata,
  _callsiteMetadata: OpMetadata,
): WasmSpanBufferInstance {
  const WasmSpanBufferClass = getWasmSpanBufferClass(schema);
  return new WasmSpanBufferClass({
    ...opts,
    logSchema: schema,
    _traceRoot,
    _scopeValues,
    _opMetadata,
    _callsiteMetadata,
  });
}

/**
 * Create a child WASM SpanBuffer linked to a parent.
 *
 * For cross-library calls, the child buffer may use a different schema than the parent.
 * Pass the schema option to use a different schema.
 *
 * @param parent - Parent WASM SpanBuffer
 * @param opts - Options for child buffer creation (schema is optional, defaults to parent's)
 * @param _traceRoot - Trace root context
 * @param _scopeValues - Scope values for this span
 * @param _opMetadata - Op metadata for attribution
 * @param _callsiteMetadata - Callsite metadata for attribution
 * @returns WasmSpanBufferInstance linked to parent
 */
export function createWasmChildSpanBuffer(
  parent: WasmSpanBufferInstance,
  opts: Omit<
    WasmSpanBufferOptions,
    | 'logSchema'
    | 'trace_id'
    | 'parent_thread_id'
    | 'parent_span_id'
    | '_traceRoot'
    | '_scopeValues'
    | '_opMetadata'
    | '_callsiteMetadata'
  > & {
    schema?: LogSchema;
  },
  _traceRoot: ITraceRoot,
  _scopeValues: Readonly<Record<string, unknown>>,
  _opMetadata: OpMetadata,
  _callsiteMetadata: OpMetadata,
): WasmSpanBufferInstance {
  // Use provided schema (for cross-library calls) or parent's schema
  const childSchema = opts.schema ?? parent._logSchema;
  const WasmSpanBufferClass = getWasmSpanBufferClass(childSchema);

  const child = new WasmSpanBufferClass({
    ...opts,
    logSchema: childSchema, // Use the child's schema (may differ from parent)
    trace_id: parent.trace_id,
    parent_thread_id: parent.thread_id,
    parent_span_id: parent.span_id,
    _traceRoot,
    _scopeValues,
    _opMetadata,
    _callsiteMetadata,
  });

  // Link to parent (SpanContext will push to parent._children with possible RemappedBufferView wrapper)
  child._parent = parent;

  return child;
}

/**
 * Create an overflow WASM SpanBuffer for chaining.
 *
 * @param buffer - The full buffer that needs overflow handling
 * @param _traceRoot - Trace root context
 * @param _scopeValues - Scope values for this span
 * @param _opMetadata - Op metadata for attribution
 * @param _callsiteMetadata - Callsite metadata for attribution
 * @returns WasmSpanBufferInstance linked as overflow
 */
export function createWasmOverflowBuffer(
  buffer: WasmSpanBufferInstance,
  _traceRoot: ITraceRoot,
  _scopeValues: Readonly<Record<string, unknown>>,
  _opMetadata: OpMetadata,
  _callsiteMetadata: OpMetadata,
): WasmSpanBufferInstance {
  const WasmSpanBufferClass = getWasmSpanBufferClass(buffer._logSchema);

  const overflow = new WasmSpanBufferClass({
    allocator: buffer._allocator,
    capacity: buffer._capacity,
    trace_id: buffer.trace_id,
    thread_id: buffer.thread_id,
    span_id: buffer.span_id,
    parent_thread_id: buffer.parent_thread_id,
    parent_span_id: buffer.parent_span_id,
    logSchema: buffer._logSchema,
    _traceRoot,
    _scopeValues,
    _opMetadata,
    _callsiteMetadata,
  });

  // Link as overflow (not child - same logical span)
  overflow._parent = buffer._parent;
  buffer._overflow = overflow;

  return overflow;
}
