// Generated by cowshed-api-gen from cowshed-core's operation table. Do not edit.
//! Which handle may call which operation, the request fields it binds for it, and that
//! operation's request built from them: the bound fields cloned from the handle's authority
//! (an optional one outside its fence sent as `None`), the rest decoded from the caller's
//! arguments as a record of exactly those fields.

use super::*;
use crate::api::call::{Arguments, Binder, Serves, decode, owned};
use crate::api::capability::{Coordinator, JobHandle, Project, WorkspaceHandle, WorkspaceRef};

impl Serves<ProjectWorkspace> for Project {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkspaceRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
        }
        let Caller { workspace } = decode::<ProjectWorkspace, Caller>(arguments)?;
        Ok(WorkspaceRequest {
            repo_id: owned(authority.repo_id),
            workspace,
        })
    }
}

impl Serves<ProjectWorkspaceAt> for Project {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkspaceAtRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            path: String,
        }
        let Caller { path } = decode::<ProjectWorkspaceAt, Caller>(arguments)?;
        Ok(WorkspaceAtRequest {
            repo_id: owned(authority.repo_id),
            path,
        })
    }
}

impl Serves<ProjectList> for Project {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<RepoRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<ProjectList, Caller>(arguments)?;
        Ok(RepoRequest {
            repo_id: owned(authority.repo_id),
        })
    }
}

impl Serves<WorkspaceInfoRead> for WorkspaceRef {
    const BOUND: &'static [&'static str] = &["repoId", "workspace"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkspaceRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<WorkspaceInfoRead, Caller>(arguments)?;
        Ok(WorkspaceRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
        })
    }
}

impl Serves<WorkspaceAttach> for WorkspaceRef {
    const BOUND: &'static [&'static str] = &["repoId", "workspace"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkspaceAttachRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            options: AttachOptions,
        }
        let Caller { options } = decode::<WorkspaceAttach, Caller>(arguments)?;
        Ok(WorkspaceAttachRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            options,
        })
    }
}

impl Serves<WorkspaceGrants> for WorkspaceRef {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkspaceGrantsRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<WorkspaceGrants, Caller>(arguments)?;
        Ok(WorkspaceGrantsRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: None,
        })
    }
}

impl Serves<WorkspaceBuildVolume> for WorkspaceRef {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkerScope> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<WorkspaceBuildVolume, Caller>(arguments)?;
        Ok(WorkerScope {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
        })
    }
}

impl Serves<CoordinatorRename> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<SourceDestinationRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            source: WorkspaceName,
            destination: WorkspaceName,
        }
        let Caller {
            source,
            destination,
        } = decode::<CoordinatorRename, Caller>(arguments)?;
        Ok(SourceDestinationRequest {
            repo_id: owned(authority.repo_id),
            source,
            destination,
        })
    }
}

impl Serves<CoordinatorAdopt> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<AdoptRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            options: AdoptOptions,
        }
        let Caller { options } = decode::<CoordinatorAdopt, Caller>(arguments)?;
        Ok(AdoptRequest {
            repo_id: owned(authority.repo_id),
            options,
        })
    }
}

impl Serves<CoordinatorCreate> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<CreateRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            options: CreateOptions,
        }
        let Caller { workspace, options } = decode::<CoordinatorCreate, Caller>(arguments)?;
        Ok(CreateRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            options,
        })
    }
}

impl Serves<CoordinatorFork> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<SourceDestinationRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            source: WorkspaceName,
            destination: WorkspaceName,
        }
        let Caller {
            source,
            destination,
        } = decode::<CoordinatorFork, Caller>(arguments)?;
        Ok(SourceDestinationRequest {
            repo_id: owned(authority.repo_id),
            source,
            destination,
        })
    }
}

impl Serves<CoordinatorMoveCheckout> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<MoveCheckoutRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            destination: PathBuf,
        }
        let Caller { destination } = decode::<CoordinatorMoveCheckout, Caller>(arguments)?;
        Ok(MoveCheckoutRequest {
            repo_id: owned(authority.repo_id),
            destination,
        })
    }
}

impl Serves<CoordinatorChangeRepoId> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<ChangeRepoIdRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            new_repo_id: RepoId,
        }
        let Caller { new_repo_id } = decode::<CoordinatorChangeRepoId, Caller>(arguments)?;
        Ok(ChangeRepoIdRequest {
            repo_id: owned(authority.repo_id),
            new_repo_id,
        })
    }
}

impl Serves<CoordinatorGrant> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<GrantRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            delta: GrantDelta,
        }
        let Caller { workspace, delta } = decode::<CoordinatorGrant, Caller>(arguments)?;
        Ok(GrantRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            delta,
        })
    }
}

impl Serves<CoordinatorRevoke> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<GrantRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            delta: GrantDelta,
        }
        let Caller { workspace, delta } = decode::<CoordinatorRevoke, Caller>(arguments)?;
        Ok(GrantRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            delta,
        })
    }
}

impl Serves<CoordinatorProjectGrants> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<RepoRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<CoordinatorProjectGrants, Caller>(arguments)?;
        Ok(RepoRequest {
            repo_id: owned(authority.repo_id),
        })
    }
}

impl Serves<CoordinatorGrantProject> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<ProjectGrantRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            delta: ProjectGrantDelta,
        }
        let Caller { delta } = decode::<CoordinatorGrantProject, Caller>(arguments)?;
        Ok(ProjectGrantRequest {
            repo_id: owned(authority.repo_id),
            delta,
        })
    }
}

impl Serves<CoordinatorRevokeProject> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<ProjectGrantRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            delta: ProjectGrantDelta,
        }
        let Caller { delta } = decode::<CoordinatorRevokeProject, Caller>(arguments)?;
        Ok(ProjectGrantRequest {
            repo_id: owned(authority.repo_id),
            delta,
        })
    }
}

impl Serves<CoordinatorRebase> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<RebaseRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            #[serde(default)]
            into: Option<WorkspaceTarget>,
            options: RebaseOptions,
        }
        let Caller {
            workspace,
            into,
            options,
        } = decode::<CoordinatorRebase, Caller>(arguments)?;
        Ok(RebaseRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            into,
            options,
        })
    }
}

impl Serves<CoordinatorLand> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<LandRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            #[serde(default)]
            into: Option<WorkspaceTarget>,
            options: LandOptions,
        }
        let Caller {
            workspace,
            into,
            options,
        } = decode::<CoordinatorLand, Caller>(arguments)?;
        Ok(LandRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            into,
            options,
        })
    }
}

impl Serves<CoordinatorRestore> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<RestoreRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            label: String,
        }
        let Caller { workspace, label } = decode::<CoordinatorRestore, Caller>(arguments)?;
        Ok(RestoreRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            label,
        })
    }
}

impl Serves<CoordinatorResize> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<ResizeRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            capacity: String,
            volume: ResizeVolume,
        }
        let Caller {
            workspace,
            capacity,
            volume,
        } = decode::<CoordinatorResize, Caller>(arguments)?;
        Ok(ResizeRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            capacity,
            volume,
        })
    }
}

impl Serves<CoordinatorDefragment> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkspaceRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
        }
        let Caller { workspace } = decode::<CoordinatorDefragment, Caller>(arguments)?;
        Ok(WorkspaceRequest {
            repo_id: owned(authority.repo_id),
            workspace,
        })
    }
}

impl Serves<CoordinatorReseed> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkspaceRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
        }
        let Caller { workspace } = decode::<CoordinatorReseed, Caller>(arguments)?;
        Ok(WorkspaceRequest {
            repo_id: owned(authority.repo_id),
            workspace,
        })
    }
}

impl Serves<CoordinatorDetach> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkspaceRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
        }
        let Caller { workspace } = decode::<CoordinatorDetach, Caller>(arguments)?;
        Ok(WorkspaceRequest {
            repo_id: owned(authority.repo_id),
            workspace,
        })
    }
}

impl Serves<CoordinatorAssignSlot> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<SlotRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            slot: u32,
        }
        let Caller { workspace, slot } = decode::<CoordinatorAssignSlot, Caller>(arguments)?;
        Ok(SlotRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            slot,
        })
    }
}

impl Serves<CoordinatorDestroy> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<DestroyRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            options: RemoveOptions,
        }
        let Caller { workspace, options } = decode::<CoordinatorDestroy, Caller>(arguments)?;
        Ok(DestroyRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            options,
        })
    }
}

impl Serves<CoordinatorGc> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<GcRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            options: GcOptions,
        }
        let Caller { options } = decode::<CoordinatorGc, Caller>(arguments)?;
        Ok(GcRequest {
            repo_id: owned(authority.repo_id),
            options,
        })
    }
}

impl Serves<CoordinatorRemoveProject> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<RemoveProjectRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            options: RemoveProjectOptions,
        }
        let Caller { options } = decode::<CoordinatorRemoveProject, Caller>(arguments)?;
        Ok(RemoveProjectRequest {
            repo_id: owned(authority.repo_id),
            options,
        })
    }
}

impl Serves<CoordinatorRepoMirror> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<MirrorRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            url: String,
        }
        let Caller { workspace, url } = decode::<CoordinatorRepoMirror, Caller>(arguments)?;
        Ok(MirrorRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            url,
        })
    }
}

impl Serves<CoordinatorSetCheckpointQuota> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<QuotaRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
            quota: CheckpointQuota,
        }
        let Caller { workspace, quota } =
            decode::<CoordinatorSetCheckpointQuota, Caller>(arguments)?;
        Ok(QuotaRequest {
            repo_id: owned(authority.repo_id),
            workspace,
            quota,
        })
    }
}

impl Serves<CoordinatorDoctor> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<RepoRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<CoordinatorDoctor, Caller>(arguments)?;
        Ok(RepoRequest {
            repo_id: owned(authority.repo_id),
        })
    }
}

impl Serves<CoordinatorWorker> for Coordinator {
    const BOUND: &'static [&'static str] = &["repoId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkspaceRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            workspace: WorkspaceName,
        }
        let Caller { workspace } = decode::<CoordinatorWorker, Caller>(arguments)?;
        Ok(WorkspaceRequest {
            repo_id: owned(authority.repo_id),
            workspace,
        })
    }
}

impl Serves<WorkspaceGrants> for WorkspaceHandle {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkspaceGrantsRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<WorkspaceGrants, Caller>(arguments)?;
        Ok(WorkspaceGrantsRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: Some(owned(authority.workspace_incarnation)),
        })
    }
}

impl Serves<WorkerExec> for WorkspaceHandle {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<ExecParams> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            session: Option<String>,
            #[serde(default)]
            argv: Option<Vec<CommandArg>>,
            #[serde(default)]
            script: Option<ScriptCommand>,
            cwd: Option<WorkspacePath>,
            mode: RunSandboxMode,
            env: HashMap<String, String>,
            trace: Option<TraceContext>,
            stdin: ExecStdin,
            stdout_copy: Option<OutputPublication>,
            stderr_copy: Option<OutputPublication>,
        }
        let Caller {
            session,
            argv,
            script,
            cwd,
            mode,
            env,
            trace,
            stdin,
            stdout_copy,
            stderr_copy,
        } = decode::<WorkerExec, Caller>(arguments)?;
        Ok(ExecParams {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            session,
            argv,
            script,
            cwd,
            mode,
            env,
            trace,
            stdin,
            stdout_copy,
            stderr_copy,
        })
    }
}

impl Serves<WorkerStdinChunk> for WorkspaceHandle {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<JobRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            job_id: JobId,
        }
        let Caller { job_id } = decode::<WorkerStdinChunk, Caller>(arguments)?;
        Ok(JobRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id,
        })
    }
}

impl Serves<WorkerStdinClose> for WorkspaceHandle {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<JobRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            job_id: JobId,
        }
        let Caller { job_id } = decode::<WorkerStdinClose, Caller>(arguments)?;
        Ok(JobRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id,
        })
    }
}

impl Serves<WorkerShell> for WorkspaceHandle {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<SessionRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            session: Option<String>,
        }
        let Caller { session } = decode::<WorkerShell, Caller>(arguments)?;
        Ok(SessionRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            session,
        })
    }
}

impl Serves<WorkerListJobs> for WorkspaceHandle {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<WorkerScope> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<WorkerListJobs, Caller>(arguments)?;
        Ok(WorkerScope {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
        })
    }
}

impl Serves<WorkerJob> for WorkspaceHandle {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<JobRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            job_id: JobId,
        }
        let Caller { job_id } = decode::<WorkerJob, Caller>(arguments)?;
        Ok(JobRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id,
        })
    }
}

impl Serves<WorkerCheckpoint> for WorkspaceHandle {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<CheckpointRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            options: CheckpointOptions,
        }
        let Caller { options } = decode::<WorkerCheckpoint, Caller>(arguments)?;
        Ok(CheckpointRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            options,
        })
    }
}

impl Serves<WorkerPush> for WorkspaceHandle {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<PushRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            options: PushOptions,
        }
        let Caller { options } = decode::<WorkerPush, Caller>(arguments)?;
        Ok(PushRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            options,
        })
    }
}

impl Serves<SessionClose> for WorkspaceHandle {
    const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<SessionRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            session: Option<String>,
        }
        let Caller { session } = decode::<SessionClose, Caller>(arguments)?;
        Ok(SessionRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            session,
        })
    }
}

impl Serves<JobStatus> for JobHandle {
    const BOUND: &'static [&'static str] =
        &["repoId", "workspace", "workspaceIncarnation", "jobId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<JobRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<JobStatus, Caller>(arguments)?;
        Ok(JobRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id: owned(authority.job_id),
        })
    }
}

impl Serves<JobSealed> for JobHandle {
    const BOUND: &'static [&'static str] =
        &["repoId", "workspace", "workspaceIncarnation", "jobId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<JobRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<JobSealed, Caller>(arguments)?;
        Ok(JobRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id: owned(authority.job_id),
        })
    }
}

impl Serves<JobLogs> for JobHandle {
    const BOUND: &'static [&'static str] =
        &["repoId", "workspace", "workspaceIncarnation", "jobId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<LogsRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            stream: JobStream,
            follow: bool,
            offset: u64,
        }
        let Caller {
            stream,
            follow,
            offset,
        } = decode::<JobLogs, Caller>(arguments)?;
        Ok(LogsRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id: owned(authority.job_id),
            stream,
            follow,
            offset,
        })
    }
}

impl Serves<JobTailRead> for JobHandle {
    const BOUND: &'static [&'static str] =
        &["repoId", "workspace", "workspaceIncarnation", "jobId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<TailRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            #[serde(default)]
            cursor: Option<JobJournalCursor>,
            limits: JobTailLimits,
        }
        let Caller { cursor, limits } = decode::<JobTailRead, Caller>(arguments)?;
        Ok(TailRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id: owned(authority.job_id),
            cursor,
            limits,
        })
    }
}

impl Serves<JobListeningPortsRead> for JobHandle {
    const BOUND: &'static [&'static str] =
        &["repoId", "workspace", "workspaceIncarnation", "jobId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<JobRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<JobListeningPortsRead, Caller>(arguments)?;
        Ok(JobRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id: owned(authority.job_id),
        })
    }
}

impl Serves<JobProgress> for JobHandle {
    const BOUND: &'static [&'static str] =
        &["repoId", "workspace", "workspaceIncarnation", "jobId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<ProgressRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {
            every_ms: SampleInterval,
        }
        let Caller { every_ms } = decode::<JobProgress, Caller>(arguments)?;
        Ok(ProgressRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id: owned(authority.job_id),
            every_ms,
        })
    }
}

impl Serves<JobAttachWrite> for JobHandle {
    const BOUND: &'static [&'static str] =
        &["repoId", "workspace", "workspaceIncarnation", "jobId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<JobRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<JobAttachWrite, Caller>(arguments)?;
        Ok(JobRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id: owned(authority.job_id),
        })
    }
}

impl Serves<JobDetach> for JobHandle {
    const BOUND: &'static [&'static str] =
        &["repoId", "workspace", "workspaceIncarnation", "jobId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<JobRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<JobDetach, Caller>(arguments)?;
        Ok(JobRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id: owned(authority.job_id),
        })
    }
}

impl Serves<JobWait> for JobHandle {
    const BOUND: &'static [&'static str] =
        &["repoId", "workspace", "workspaceIncarnation", "jobId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<JobRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<JobWait, Caller>(arguments)?;
        Ok(JobRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id: owned(authority.job_id),
        })
    }
}

impl Serves<JobKill> for JobHandle {
    const BOUND: &'static [&'static str] =
        &["repoId", "workspace", "workspaceIncarnation", "jobId"];

    fn request(
        authority: &<Self as Binder>::Fields<'_>,
        arguments: Arguments,
    ) -> Result<JobRequest> {
        #[derive(Deserialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct Caller {}
        let Caller {} = decode::<JobKill, Caller>(arguments)?;
        Ok(JobRequest {
            repo_id: owned(authority.repo_id),
            workspace: owned(authority.workspace),
            workspace_incarnation: owned(authority.workspace_incarnation),
            job_id: owned(authority.job_id),
        })
    }
}

/// A check that must hold for every operation each handle serves. `absent` names the bound
/// fields the handle supplies as `None`: optional fields its authority holds but does not fence.
#[cfg(test)]
pub(crate) trait EachServed {
    fn served<O: Operation, H: Serves<O>>(&mut self, handle: &H, absent: &[&str])
    where
        O::Request: PartialEq + std::fmt::Debug;
}

/// Runs `check` over every operation each handle serves, through the given handles.
#[cfg(test)]
pub(crate) fn each_served(
    check: &mut impl EachServed,
    project: &Project,
    workspace_ref: &WorkspaceRef,
    coordinator: &Coordinator,
    workspace_handle: &WorkspaceHandle,
    job_handle: &JobHandle,
) {
    check.served::<ProjectWorkspace, _>(project, &[]);
    check.served::<ProjectWorkspaceAt, _>(project, &[]);
    check.served::<ProjectList, _>(project, &[]);
    check.served::<WorkspaceInfoRead, _>(workspace_ref, &[]);
    check.served::<WorkspaceAttach, _>(workspace_ref, &[]);
    check.served::<WorkspaceGrants, _>(workspace_ref, &["workspaceIncarnation"]);
    check.served::<WorkspaceBuildVolume, _>(workspace_ref, &[]);
    check.served::<CoordinatorRename, _>(coordinator, &[]);
    check.served::<CoordinatorAdopt, _>(coordinator, &[]);
    check.served::<CoordinatorCreate, _>(coordinator, &[]);
    check.served::<CoordinatorFork, _>(coordinator, &[]);
    check.served::<CoordinatorMoveCheckout, _>(coordinator, &[]);
    check.served::<CoordinatorChangeRepoId, _>(coordinator, &[]);
    check.served::<CoordinatorGrant, _>(coordinator, &[]);
    check.served::<CoordinatorRevoke, _>(coordinator, &[]);
    check.served::<CoordinatorProjectGrants, _>(coordinator, &[]);
    check.served::<CoordinatorGrantProject, _>(coordinator, &[]);
    check.served::<CoordinatorRevokeProject, _>(coordinator, &[]);
    check.served::<CoordinatorRebase, _>(coordinator, &[]);
    check.served::<CoordinatorLand, _>(coordinator, &[]);
    check.served::<CoordinatorRestore, _>(coordinator, &[]);
    check.served::<CoordinatorResize, _>(coordinator, &[]);
    check.served::<CoordinatorDefragment, _>(coordinator, &[]);
    check.served::<CoordinatorReseed, _>(coordinator, &[]);
    check.served::<CoordinatorDetach, _>(coordinator, &[]);
    check.served::<CoordinatorAssignSlot, _>(coordinator, &[]);
    check.served::<CoordinatorDestroy, _>(coordinator, &[]);
    check.served::<CoordinatorGc, _>(coordinator, &[]);
    check.served::<CoordinatorRemoveProject, _>(coordinator, &[]);
    check.served::<CoordinatorRepoMirror, _>(coordinator, &[]);
    check.served::<CoordinatorSetCheckpointQuota, _>(coordinator, &[]);
    check.served::<CoordinatorDoctor, _>(coordinator, &[]);
    check.served::<CoordinatorWorker, _>(coordinator, &[]);
    check.served::<WorkspaceGrants, _>(workspace_handle, &[]);
    check.served::<WorkerExec, _>(workspace_handle, &[]);
    check.served::<WorkerStdinChunk, _>(workspace_handle, &[]);
    check.served::<WorkerStdinClose, _>(workspace_handle, &[]);
    check.served::<WorkerShell, _>(workspace_handle, &[]);
    check.served::<WorkerListJobs, _>(workspace_handle, &[]);
    check.served::<WorkerJob, _>(workspace_handle, &[]);
    check.served::<WorkerCheckpoint, _>(workspace_handle, &[]);
    check.served::<WorkerPush, _>(workspace_handle, &[]);
    check.served::<SessionClose, _>(workspace_handle, &[]);
    check.served::<JobStatus, _>(job_handle, &[]);
    check.served::<JobSealed, _>(job_handle, &[]);
    check.served::<JobLogs, _>(job_handle, &[]);
    check.served::<JobTailRead, _>(job_handle, &[]);
    check.served::<JobListeningPortsRead, _>(job_handle, &[]);
    check.served::<JobProgress, _>(job_handle, &[]);
    check.served::<JobAttachWrite, _>(job_handle, &[]);
    check.served::<JobDetach, _>(job_handle, &[]);
    check.served::<JobWait, _>(job_handle, &[]);
    check.served::<JobKill, _>(job_handle, &[]);
}
