// Generated by cowshed-api-gen from cowshed-core's operation table. Do not edit.
//! One adapter per controller operation, on each handle that serves it.

use super::{Coordinator, JobHandle, Project, WorkspaceHandle, WorkspaceRef};
use cowshed_core::api::operations;
use napi::{Env, JsObject, bindgen_prelude::Buffer};
use napi_derive::napi;
use std::sync::Arc;

#[napi]
impl Project {
    /// Resolves one workspace by name.
    #[napi(js_name = "workspace")]
    pub fn workspace(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::workspace_call::<operations::ProjectWorkspace, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Resolves the workspace an existing path belongs to.
    #[napi(js_name = "workspaceAt")]
    pub fn workspace_at(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::workspace_call::<operations::ProjectWorkspaceAt, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Lists every published workspace.
    #[napi(js_name = "list")]
    pub fn list(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::ProjectList, _>(env, Arc::clone(&self.inner), arguments)
    }
}

#[napi]
impl WorkspaceRef {
    /// Refreshes one workspace's information.
    #[napi(js_name = "info")]
    pub fn info(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::WorkspaceInfoRead, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Attaches a detached workspace.
    #[napi(js_name = "attach")]
    pub fn attach(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::WorkspaceAttach, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Reads one workspace's grants; a worker reads its own, fenced on its incarnation.
    #[napi(js_name = "grants")]
    pub fn grants(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::WorkspaceGrants, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// The build volume a job of the workspace incarnation would be granted now.
    #[napi(js_name = "buildVolume")]
    pub fn build_volume(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::WorkspaceBuildVolume, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }
}

#[napi]
impl Coordinator {
    /// Renames a session workspace.
    #[napi(js_name = "rename")]
    pub fn rename(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::workspace_call::<operations::CoordinatorRename, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Adopts the project's checkout as main.
    #[napi(js_name = "adopt")]
    pub fn adopt(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::workspace_call::<operations::CoordinatorAdopt, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Creates a session workspace from main.
    #[napi(js_name = "create")]
    pub fn create(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::workspace_call::<operations::CoordinatorCreate, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Forks a workspace into a new session workspace.
    #[napi(js_name = "fork")]
    pub fn fork(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::workspace_call::<operations::CoordinatorFork, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Moves the project's checkout.
    #[napi(js_name = "moveCheckout")]
    pub fn move_checkout(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::workspace_call::<operations::CoordinatorMoveCheckout, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Changes the adopted project's repository identity.
    #[napi(js_name = "changeRepoId")]
    pub fn change_repo_id(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::workspace_call::<operations::CoordinatorChangeRepoId, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Adds grants to one workspace.
    #[napi(js_name = "grant")]
    pub fn grant(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorGrant, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Removes grants from one workspace.
    #[napi(js_name = "revoke")]
    pub fn revoke(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorRevoke, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Reads the project's standing grants.
    #[napi(js_name = "projectGrants")]
    pub fn project_grants(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorProjectGrants, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Adds project-wide grants.
    #[napi(js_name = "grantProject")]
    pub fn grant_project(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorGrantProject, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Removes project-wide grants.
    #[napi(js_name = "revokeProject")]
    pub fn revoke_project(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorRevokeProject, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Rebases a workspace onto what it lands into.
    #[napi(js_name = "rebase")]
    pub fn rebase(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorRebase, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Lands a workspace into its target.
    #[napi(js_name = "land")]
    pub fn land(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorLand, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Restores a workspace to a checkpoint.
    #[napi(js_name = "restore")]
    pub fn restore(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorRestore, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Grows a workspace's image or build volume.
    #[napi(js_name = "resize")]
    pub fn resize(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorResize, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Rewrites a workspace's image contiguously.
    #[napi(js_name = "defragment")]
    pub fn defragment(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorDefragment, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Refreezes a target's seed from its live build volume.
    #[napi(js_name = "reseed")]
    pub fn reseed(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorReseed, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Detaches a workspace.
    #[napi(js_name = "detach")]
    pub fn detach(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorDetach, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Assigns a workspace's gateway port slot.
    #[napi(js_name = "assignSlot")]
    pub fn assign_slot(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorAssignSlot, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Destroys a session workspace.
    #[napi(js_name = "destroy")]
    pub fn destroy(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorDestroy, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Collects unreferenced storage.
    #[napi(js_name = "gc")]
    pub fn gc(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorGc, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Removes the adopted project end to end.
    #[napi(js_name = "removeProject")]
    pub fn remove_project(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorRemoveProject, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Points a workspace's repository mirror at a URL.
    #[napi(js_name = "repoMirror")]
    pub fn repo_mirror(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorRepoMirror, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Sets a workspace's checkpoint quota.
    #[napi(js_name = "setCheckpointQuota")]
    pub fn set_checkpoint_quota(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorSetCheckpointQuota, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Reports the project's health findings.
    #[napi(js_name = "doctor")]
    pub fn doctor(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::CoordinatorDoctor, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Mints a worker capability for one workspace.
    #[napi(js_name = "worker")]
    pub fn worker(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::worker_call::<operations::CoordinatorWorker>(env, Arc::clone(&self.inner), arguments)
    }
}

#[napi]
impl WorkspaceHandle {
    /// Reads one workspace's grants; a worker reads its own, fenced on its incarnation.
    #[napi(js_name = "grants")]
    pub fn grants(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::WorkspaceGrants, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Admits one job; inline stdin travels as the upload frame.
    #[napi(js_name = "exec")]
    pub fn exec(
        &self,
        env: Env,
        arguments: String,
        bytes: Option<Buffer>,
    ) -> napi::Result<JsObject> {
        super::job_upload_call::<operations::WorkerExec>(
            env,
            Arc::clone(&self.inner),
            arguments,
            bytes,
        )
    }

    /// Writes one chunk of a streamed stdin.
    #[napi(js_name = "stdinChunk")]
    pub fn stdin_chunk(
        &self,
        env: Env,
        arguments: String,
        bytes: Option<Buffer>,
    ) -> napi::Result<JsObject> {
        super::upload_call::<operations::WorkerStdinChunk, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
            bytes,
        )
    }

    /// Ends a streamed stdin.
    #[napi(js_name = "stdinClose")]
    pub fn stdin_close(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::WorkerStdinClose, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Opens a shell session.
    #[napi(js_name = "shell")]
    pub fn shell(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::WorkerShell, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Lists the workspace incarnation's jobs.
    #[napi(js_name = "listJobs")]
    pub fn list_jobs(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::WorkerListJobs, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Resolves one job.
    #[napi(js_name = "job")]
    pub fn job(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::job_call::<operations::WorkerJob>(env, Arc::clone(&self.inner), arguments)
    }

    /// Names the job an admission key admitted in the workspace incarnation: the job whose exec
    /// reply was lost.
    #[napi(js_name = "jobByKey")]
    pub fn job_by_key(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::job_call::<operations::WorkerJobByKey>(env, Arc::clone(&self.inner), arguments)
    }

    /// Takes a checkpoint.
    #[napi(js_name = "checkpoint")]
    pub fn checkpoint(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::WorkerCheckpoint, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Pushes the workspace's branch.
    #[napi(js_name = "push")]
    pub fn push(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::WorkerPush, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Closes a shell session.
    #[napi(js_name = "close")]
    pub fn close(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::SessionClose, _>(env, Arc::clone(&self.inner), arguments)
    }
}

#[napi]
impl JobHandle {
    /// Reads one job's status.
    #[napi(js_name = "status")]
    pub fn status(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::JobStatus, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Reads one ended job's sealed record.
    #[napi(js_name = "sealed")]
    pub fn sealed(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::JobSealed, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Reads one bounded raw chunk from an offset. Without follow, an empty chunk is the current
    /// written end even when eof is false; follow waits on supervisor output notifications.
    #[napi(js_name = "logs")]
    pub fn logs(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::download_call::<operations::JobLogs, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Reads a bounded slice of both streams after a cursor, or their latest bounded tail.
    #[napi(js_name = "tail")]
    pub fn tail(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::JobTailRead, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Reads the TCP ports the job's process group listens on, from the kernel.
    #[napi(js_name = "listeningPorts")]
    pub fn listening_ports(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::JobListeningPortsRead, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
        )
    }

    /// Streams one job's resource samples: the latest at once, one every interval while it runs,
    /// then its terminal sample once.
    #[napi(js_name = "progress")]
    pub fn progress(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::stream_call::<operations::JobProgress, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Writes to an attached job's stdin.
    #[napi(js_name = "attachWrite")]
    pub fn attach_write(
        &self,
        env: Env,
        arguments: String,
        bytes: Option<Buffer>,
    ) -> napi::Result<JsObject> {
        super::upload_call::<operations::JobAttachWrite, _>(
            env,
            Arc::clone(&self.inner),
            arguments,
            bytes,
        )
    }

    /// Detaches from a job.
    #[napi(js_name = "detach")]
    pub fn detach(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::JobDetach, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Waits for a job to end.
    #[napi(js_name = "wait")]
    pub fn wait(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::JobWait, _>(env, Arc::clone(&self.inner), arguments)
    }

    /// Kills a job's complete process group.
    #[napi(js_name = "kill")]
    pub fn kill(&self, env: Env, arguments: String) -> napi::Result<JsObject> {
        super::json_call::<operations::JobKill, _>(env, Arc::clone(&self.inner), arguments)
    }
}

/// The canonical core error, with every serialized detail retained on the JS Error.
pub(super) fn cowshed_error(
    env: Env,
    source: cowshed_core::CowshedError,
) -> napi::Result<napi::Error> {
    let details = env.to_js_value(&source)?.coerce_to_object()?;
    let mut error = napi::JsError::from(napi::Error::new(source.code.as_str(), source.message))
        .into_unknown(env)
        .coerce_to_object()?;
    if details.has_named_property("hint")? {
        error.set_named_property(
            "hint",
            details.get_named_property::<napi::JsUnknown>("hint")?,
        )?;
    }
    if details.has_named_property("otherBuild")? {
        error.set_named_property(
            "otherBuild",
            details.get_named_property::<napi::JsUnknown>("otherBuild")?,
        )?;
    }
    if details.has_named_property("recovering")? {
        error.set_named_property(
            "recovering",
            details.get_named_property::<napi::JsUnknown>("recovering")?,
        )?;
    }
    if details.has_named_property("healing")? {
        error.set_named_property(
            "healing",
            details.get_named_property::<napi::JsUnknown>("healing")?,
        )?;
    }
    if details.has_named_property("fence")? {
        error.set_named_property(
            "fence",
            details.get_named_property::<napi::JsUnknown>("fence")?,
        )?;
    }
    if details.has_named_property("retry")? {
        error.set_named_property(
            "retry",
            details.get_named_property::<napi::JsUnknown>("retry")?,
        )?;
    }
    if details.has_named_property("admission")? {
        error.set_named_property(
            "admission",
            details.get_named_property::<napi::JsUnknown>("admission")?,
        )?;
    }
    Ok(napi::Error::from(error.into_unknown()))
}
