# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  bun-aarch64-darwin = {
    pname = "bun-aarch64-darwin";
    version = "1.2.16";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.2.16/bun-darwin-aarch64.zip";
      sha256 = "sha256-IBaCFzMLDruOkUg25jqvVxQK/wz5VxYidlh8qwQS8X8=";
    };
  };
  bun-aarch64-linux = {
    pname = "bun-aarch64-linux";
    version = "1.2.16";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.2.16/bun-linux-aarch64.zip";
      sha256 = "sha256-gKAkQ0q1sJjCWe5VsfWCgFkdHeKGxcZStjNkCoyZ5j4=";
    };
  };
  bun-x86_64-darwin = {
    pname = "bun-x86_64-darwin";
    version = "1.2.16";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.2.16/bun-darwin-x64.zip";
      sha256 = "sha256-k7JuZ9HyGaKrgIZ70TDbH10QkXCzjMcPQZJdQZjBF1M=";
    };
  };
  bun-x86_64-linux = {
    pname = "bun-x86_64-linux";
    version = "1.2.16";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.2.16/bun-linux-x64.zip";
      sha256 = "sha256-+DEdjXyqDZOMbEzs8KYA5enOTidaQR44oun4x30MEAI=";
    };
  };
}
