# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  bun-aarch64-darwin = {
    pname = "bun-aarch64-darwin";
    version = "canary";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/canary/bun-darwin-aarch64.zip";
      sha256 = "sha256-x1m2QXUxCN54wnYBabXyUdy6yekLpbxU+i/LfhYg5Xo=";
    };
  };
  bun-aarch64-linux = {
    pname = "bun-aarch64-linux";
    version = "canary";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/canary/bun-linux-aarch64.zip";
      sha256 = "sha256-jfreZ2R2Dz2dufeRhT9R7YKsFKWfXZ7tgkcWv2Gayzo=";
    };
  };
  bun-x86_64-darwin = {
    pname = "bun-x86_64-darwin";
    version = "canary";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/canary/bun-darwin-x64.zip";
      sha256 = "sha256-zrtzr0U7A24hxVn/X1EsvSV10+44ynxsaV9SsXGOpYA=";
    };
  };
  bun-x86_64-linux = {
    pname = "bun-x86_64-linux";
    version = "canary";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/canary/bun-linux-x64.zip";
      sha256 = "sha256-K9jnJqFA0FyBK1ZvfBUNZHO/u9emGb2cNClaWUwKmJQ=";
    };
  };
}
