/**
 * Shared types for dep-updater
 */

import type { Options } from 'execa';

/**
 * Simplified result interface for command execution
 * Contains only the fields we actually use from execa's Result type
 */
export interface ExecutorResult {
  /** Standard output */
  stdout: string;
  /** Standard error */
  stderr: string;
  /** Exit code */
  exitCode: number;
}

/**
 * Deep partial type - makes all properties and nested properties optional
 * Useful for partial configuration updates
 */
export type DeepPartial<T> = T extends object
  ? {
      [P in keyof T]?: DeepPartial<T[P]>;
    }
  : T;

/**
 * Update type classification
 */
export type UpdateType = 'major' | 'minor' | 'patch' | 'unknown';

/**
 * Dependency ecosystem
 */
export type DependencyEcosystem = 'npm' | 'nix' | 'nixpkgs' | 'expo';

/**
 * Information about a single package update
 */
export interface PackageUpdate {
  /** Package name */
  name: string;
  /** Version before update */
  fromVersion: string;
  /** Version after update */
  toVersion: string;
  /** Update type (major/minor/patch) */
  updateType: UpdateType;
  /** Ecosystem this package belongs to */
  ecosystem: DependencyEcosystem;
  /** Changelog URL or text */
  changelog?: string;
  /** Changelog source URL (e.g., GitHub releases) */
  changelogUrl?: string;
  /** Breaking changes detected */
  breakingChanges?: string[];
}

/**
 * Result of a dependency update operation
 */
export interface UpdateResult {
  /** Whether the update was successful */
  success: boolean;
  /** List of package updates (upgrades only) */
  updates: PackageUpdate[];
  /** List of package downgrades (for informational purposes, not included in PRs) */
  downgrades?: PackageUpdate[];
  /** Error message if failed */
  error?: string;
  /** Ecosystem that was updated */
  ecosystem: DependencyEcosystem;
}

/**
 * nvfetcher source entry structure
 * Generated by nvfetcher in _sources/generated.json
 */
export interface NvfetcherSource {
  /** Package version */
  version: string;
  /** Source information (git, url, etc.) */
  src?: {
    /** Source type (git, url, pypi, etc.) */
    type?: string;
    /** Source URL */
    url?: string;
    /** Git revision/tag */
    rev?: string;
    /** SHA256 hash */
    sha256?: string;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

/**
 * nvfetcher generated sources file structure
 * Maps package name to source information
 */
export interface NvfetcherSources {
  [packageName: string]: NvfetcherSource;
}

/**
 * Information about an open PR
 */
export interface OpenPR {
  /** PR number */
  number: number;
  /** PR title */
  title: string;
  /** Branch name */
  branch: string;
  /** Creation date */
  createdAt: Date;
  /** Whether PR has merge conflicts */
  hasConflicts: boolean;
  /** PR URL */
  url: string;
}

/**
 * Expo SDK version information
 */
export interface ExpoSDKVersion {
  /** SDK version number (e.g., "52.0.0") */
  version: string;
  /** Whether this is the latest stable version */
  isLatest: boolean;
  /** Changelog URL */
  changelogUrl?: string;
}

/**
 * Expo recommended package versions for an SDK
 */
export interface ExpoPackageVersions {
  /** SDK version these recommendations are for */
  sdkVersion: string;
  /** Map of package name to version */
  packages: Record<string, string>;
}

/**
 * Expo project configuration
 * Used for managing multiple Expo apps in a monorepo
 */
export interface ExpoProject {
  /** Project name (optional, for logging) */
  name?: string;
  /** Path to package.json containing Expo dependency */
  packageJsonPath: string;
}

/**
 * Options for update commands
 */
export interface UpdateOptions {
  /** Dry run mode - don't make actual changes */
  dryRun: boolean;
  /** Skip git operations */
  skipGit: boolean;
  /** Skip AI changelog analysis */
  skipAI: boolean;
}

/**
 * Options for generate-workflow command
 */
export interface GenerateWorkflowOptions extends UpdateOptions {
  /** Cron schedule for workflow */
  schedule?: string;
  /** Name of the workflow */
  workflowName?: string;
  /** Explicitly enable AI (overrides auto-detection) */
  enableAI?: boolean;
}

/**
 * Options for init command
 */
export interface InitOptions extends UpdateOptions {
  /** Skip prompts and use defaults */
  yes?: boolean;
}

/**
 * Type for command executor (for testing git operations)
 * Matches the array-long form: execa(file, args, options)
 *
 * Uses simplified ExecutorResult instead of full execa Result to avoid
 * requiring mocks to implement all 15+ fields when we only use stdout/stderr/exitCode.
 * The real execa function returns a superset of this interface.
 */
export type CommandExecutor = (
  file: string | URL,
  args?: readonly string[],
  options?: Options,
) => Promise<ExecutorResult>;

/**
 * GitHub Pull Request information
 */
export interface GitHubPR {
  /** PR number */
  number: number;
  /** PR title */
  title: string;
  /** Head branch name */
  headRefName: string;
  /** PR creation date */
  createdAt: string;
  /** PR URL */
  url: string;
  /** Whether the PR is mergeable (no conflicts) */
  mergeable?: 'MERGEABLE' | 'CONFLICTING' | 'UNKNOWN';
}

/**
 * Supported AI providers for changelog analysis
 * - opencode: Free tier via OpenCode (requires `opencode auth login`, default model: big-pickle)
 * - anthropic, openai, google: Premium tiers (require API keys)
 */
export const SUPPORTED_PROVIDERS = ['opencode', 'anthropic', 'openai', 'google'] as const;
export type SupportedProvider = (typeof SUPPORTED_PROVIDERS)[number];

/**
 * Options for sending a prompt to AI
 */
export interface SendPromptOptions {
  /** Override the default model for this request */
  model?: string;
  /** Override the provider for this request */
  provider?: SupportedProvider;
}

/**
 * Result from parsing dix (devenv diff) output
 */
export interface DixParseResult {
  /** Package upgrades */
  updates: PackageUpdate[];
  /** Package downgrades */
  downgrades: PackageUpdate[];
}

/**
 * Project setup detection result
 */
export interface ProjectSetup {
  /** Whether project uses Expo */
  hasExpo: boolean;
  /** Whether project uses Nix/devenv */
  hasNix: boolean;
  /** Whether project uses syncpack */
  hasSyncpack: boolean;
  /** Detected package manager */
  packageManager: 'bun' | 'npm' | 'pnpm' | 'yarn';
}

/**
 * GitHub client interface
 * Defines operations for pull request management
 */
export interface IGitHubClient {
  /** List open pull requests with update- prefix */
  listUpdatePRs(repoRoot: string): Promise<GitHubPR[]>;
  /** Check if a PR has merge conflicts */
  checkPRConflicts(repoRoot: string, prNumber: number): Promise<boolean>;
  /** Create a new pull request */
  createPR(
    repoRoot: string,
    options: {
      title: string;
      body: string;
      head: string;
      base: string;
    },
  ): Promise<{ number: number; url: string }>;
  /** Close a pull request with a comment */
  closePR(repoRoot: string, prNumber: number, comment: string): Promise<void>;
}

/**
 * Options for generate-syncpack command
 */
export interface GenerateSyncpackOptions extends UpdateOptions {
  /** Target Expo SDK version */
  expoSdkVersion?: string;
}
