//! Frozen registry snapshots used as the ABI audit tripwire. These snapshots
//! were captured at the Rust port cutover and are the ground truth against
//! which the live registries are checked. A deliberate ABI change edits this
//! fixture in the same commit as the registry; an audit failure means the two
//! moved apart unintentionally.
//!
//! [`TYPES_OPCODE_REGISTRY`] is the snapshot of the one `Opcode` registry in
//! `types.rs`. Intentional ABI changes update it together with the registry
//! and `cargo test -p columine-types`.

pub const TYPES_OPCODE_REGISTRY: &[(&str, u8)] = &[
    ("batchaggcount", 0x41),
    ("batchaggcountif", 0x45),
    ("batchaggmax", 0x43),
    ("batchaggmaxi64", 0x4b),
    ("batchaggmaxif", 0x47),
    ("batchaggmin", 0x42),
    ("batchaggmini64", 0x4a),
    ("batchaggminif", 0x46),
    ("batchaggsum", 0x40),
    ("batchaggsumi64", 0x49),
    ("batchaggsumif", 0x44),
    ("batchbitmapadd", 0x34),
    ("batchbitmapand", 0x36),
    ("batchbitmapandnot", 0x38),
    ("batchbitmapandnotscratch", 0x3c),
    ("batchbitmapandscratch", 0x3a),
    ("batchbitmapor", 0x37),
    ("batchbitmaporscratch", 0x3b),
    ("batchbitmapremove", 0x35),
    ("batchbitmapxor", 0x39),
    ("batchbitmapxorscratch", 0x3d),
    ("batchmapremove", 0x23),
    ("batchmapremoveif", 0x2b),
    ("batchmapupsertfirst", 0x21),
    ("batchmapupsertfirstif", 0x29),
    ("batchmapupsertlast", 0x22),
    ("batchmapupsertlastif", 0x2a),
    ("batchmapupsertlastttl", 0x25),
    ("batchmapupsertlatest", 0x20),
    ("batchmapupsertlatestif", 0x28),
    ("batchmapupsertlatestttl", 0x24),
    ("batchmapupsertmax", 0x26),
    ("batchmapupsertmaxif", 0x2c),
    ("batchmapupsertmin", 0x27),
    ("batchmapupsertminif", 0x2d),
    ("batchscalarlatest", 0x48),
    ("batchsetinsert", 0x30),
    ("batchsetinsertif", 0x33),
    ("batchsetinsertttl", 0x32),
    ("batchsetremove", 0x31),
    ("batchstructmapprobe", 0x2e),
    ("batchstructmapprobescatter", 0x2f),
    ("batchstructmap2remove", 0x86),
    ("batchstructmap2upsertlast", 0x83),
    ("batchstructmap2upsertmaxi64x2", 0x87),
    ("batchstructmapupsertfirst", 0x81),
    ("batchstructmapupsertlast", 0x80),
    ("batchstructmapupsertmax", 0x82),
    ("flatmap", 0xe1),
    ("foreach", 0xe0),
    ("halt", 0x00),
    ("listappend", 0x84),
    ("listappendstruct", 0x85),
    ("nestedaggupdate", 0x95),
    ("nestedmapupsertlast", 0x92),
    ("nestedsetinsert", 0x90),
    ("slotarray", 0x14),
    ("slotdef", 0x10),
    ("slotnested", 0x1a),
    ("slotorderedlist", 0x19),
    ("slotstructmap", 0x18),
    ("slotstructmap2", 0x1b),
];

/// Complete frozen tag sets for the remaining ABI registries. `registry_audit`
/// asserts set equality against what each `from_u8`/`from_u32` decodes over
/// its whole input domain, so adding, removing, or renumbering a variant
/// fails the audit — which a pasted partial list inside a unit test cannot.
pub const SLOT_TYPES: &[(&str, u8)] = &[
    ("aggregate", 2),
    ("array", 3),
    ("bitmap", 8),
    ("conditiontree", 4),
    ("hashmap", 0),
    ("hashset", 1),
    ("nested", 9),
    ("orderedlist", 7),
    ("scalar", 5),
    ("structmap", 6),
    ("structmap2", 10),
];
pub const AGG_TYPES: &[(&str, u8)] = &[
    ("avg", 5),
    ("count", 2),
    ("max", 4),
    ("maxi64", 13),
    ("min", 3),
    ("mini64", 12),
    ("scalarf64", 9),
    ("scalari64", 10),
    ("scalaru32", 8),
    ("sum", 1),
    ("sumi64", 11),
];
pub const STRUCT_FIELD_TYPES: &[(&str, u8)] = &[
    ("arraybool", 9),
    ("arrayf64", 7),
    ("arrayi64", 6),
    ("arraystring", 8),
    ("arrayu32", 5),
    ("bool", 3),
    ("float64", 2),
    ("int64", 1),
    ("string", 4),
    ("uint32", 0),
];
pub const DURATION_UNITS: &[(&str, u8)] = &[
    ("day", 4),
    ("hour", 3),
    ("minute", 2),
    ("month", 6),
    ("none", 0),
    ("quarter", 7),
    ("second", 1),
    ("week", 5),
    ("year", 8),
];
pub const ERROR_CODES: &[(&str, u32)] = &[
    ("arenaoverflow", 6),
    ("capacityexceeded", 1),
    ("columnunderrun", 8),
    ("invalidkey", 7),
    ("invalidprogram", 2),
    ("invalidslot", 3),
    ("invalidstate", 4),
    ("needsgrowth", 5),
    ("ok", 0),
];
pub const DISPATCHED_OPCODE_BYTES: &[u8] = &[
    0x00, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e,
    0x2f, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x40,
    0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x80, 0x81, 0x82, 0x83, 0x84,
    0x85, 0x86, 0x87, 0x90, 0x92, 0x95, 0xe0, 0xe1,
];
pub const FLAT_UNDO_OPS: &[(&str, u8)] = &[
    ("aggupdate", 0x06),
    ("countupdate", 0x0b),
    ("factinsertnew", 0x07),
    ("factinsertupdate", 0x08),
    ("factretract", 0x09),
    ("listappendundo", 0x0a),
    ("mapdelete", 0x03),
    ("mapinsert", 0x01),
    ("mapupdate", 0x02),
    ("setdelete", 0x05),
    ("setinsert", 0x04),
    ("structmapfield", 0x0c),
    ("structmaprow", 0x0d),
];
pub const RETE_OPCODES: &[(&str, u8)] = &[
    ("alphacolfiltereq", 0x58),
    ("alphacolfilterge", 0x5d),
    ("alphacolfiltergt", 0x5c),
    ("alphacolfilterle", 0x5b),
    ("alphacolfilterlt", 0x5a),
    ("alphacolfilterne", 0x59),
    ("alphamapget", 0x52),
    ("alphasetcontains", 0x53),
    ("alphaslotbind", 0x50),
    ("alphaslotchanges", 0x54),
    ("alphaslotevicted", 0x56),
    ("alphaslotindexbind", 0x55),
    ("alphaslotsize", 0x51),
    ("betabvand", 0x60),
    ("betabvclear", 0x64),
    ("betabvcopy", 0x63),
    ("betabvnot", 0x62),
    ("betabvor", 0x61),
    ("betabvsetall", 0x65),
    ("betaevalax", 0x6f),
    ("betaevalwhen", 0x68),
    ("betaiterbvnext", 0x6a),
    ("betaiterbvstart", 0x69),
    ("halt", 0x00),
    ("negbvandnot", 0x6e),
    ("prodfirerules", 0x73),
    ("prodinsertfact", 0x70),
    ("prodqueuedecision", 0x72),
    ("prodretractfact", 0x71),
];
