//! The Zig ABI's tombstone: the opcode/undo/rete registries and dispatched
//! byte sets harvested from the Zig sources at cutover (rust-port, 2026-07-14,
//! the commit that deleted them). The Zig implementation is gone; these
//! frozen sets ARE the ground truth the audits compare the Rust registries
//! against. A deliberate ABI change edits this fixture in the same commit
//! that changes the registry — the audit failing means the two moved apart
//! UNINTENTIONALLY.
//!
//! Harvested mechanically by `columine_types::zig_audit` parsers from:
//! columine/src/vm/{types,opcodes,vm}.zig + axe-runtime/src/vm/rete.zig.
//! Names are in `zig_audit::norm` form (lowercased, separators dropped).

pub const TYPES_ZIG_OPCODES: &[(&str, u8)] = &[
    ("batchaggcount", 0x41),
    ("batchaggcountif", 0x45),
    ("batchaggmax", 0x43),
    ("batchaggmaxi64", 0x4b),
    ("batchaggmaxif", 0x47),
    ("batchaggmin", 0x42),
    ("batchaggmini64", 0x4a),
    ("batchaggminif", 0x46),
    ("batchaggsum", 0x40),
    ("batchaggsumi64", 0x49),
    ("batchaggsumif", 0x44),
    ("batchbitmapadd", 0x34),
    ("batchbitmapand", 0x36),
    ("batchbitmapandnot", 0x38),
    ("batchbitmapandnotscratch", 0x3c),
    ("batchbitmapandscratch", 0x3a),
    ("batchbitmapor", 0x37),
    ("batchbitmaporscratch", 0x3b),
    ("batchbitmapremove", 0x35),
    ("batchbitmapxor", 0x39),
    ("batchbitmapxorscratch", 0x3d),
    ("batchmapremove", 0x23),
    ("batchmapremoveif", 0x2b),
    ("batchmapupsertfirst", 0x21),
    ("batchmapupsertfirstif", 0x29),
    ("batchmapupsertlast", 0x22),
    ("batchmapupsertlastif", 0x2a),
    ("batchmapupsertlastttl", 0x25),
    ("batchmapupsertlatest", 0x20),
    ("batchmapupsertlatestif", 0x28),
    ("batchmapupsertlatestttl", 0x24),
    ("batchmapupsertmax", 0x26),
    ("batchmapupsertmaxif", 0x2c),
    ("batchmapupsertmin", 0x27),
    ("batchmapupsertminif", 0x2d),
    ("batchscalarlatest", 0x48),
    ("batchsetinsert", 0x30),
    ("batchsetinsertif", 0x33),
    ("batchsetinsertttl", 0x32),
    ("batchsetremove", 0x31),
    ("batchstructmapprobe", 0x2e),
    ("batchstructmapprobescatter", 0x2f),
    ("batchstructmap2remove", 0x86),
    ("batchstructmap2upsertlast", 0x83),
    ("batchstructmap2upsertmaxi64x2", 0x87),
    ("batchstructmapupsertfirst", 0x81),
    ("batchstructmapupsertlast", 0x80),
    ("batchstructmapupsertmax", 0x82),
    ("flatmap", 0xe1),
    ("foreach", 0xe0),
    ("halt", 0x00),
    ("listappend", 0x84),
    ("listappendstruct", 0x85),
    ("nestedaggupdate", 0x95),
    ("nestedmapupsertlast", 0x92),
    ("nestedsetinsert", 0x90),
    ("slotarray", 0x14),
    ("slotdef", 0x10),
    ("slotnested", 0x1a),
    ("slotorderedlist", 0x19),
    ("slotstructmap", 0x18),
    ("slotstructmap2", 0x1b),
];
pub const OPCODES_ZIG_OPCODES: &[(&str, u8)] = &[
    ("batchaggcount", 0x41),
    ("batchaggcountif", 0x45),
    ("batchaggmax", 0x43),
    ("batchaggmaxi64", 0x4b),
    ("batchaggmaxif", 0x47),
    ("batchaggmin", 0x42),
    ("batchaggmini64", 0x4a),
    ("batchaggminif", 0x46),
    ("batchaggsum", 0x40),
    ("batchaggsumi64", 0x49),
    ("batchaggsumif", 0x44),
    ("batchbitmapadd", 0x34),
    ("batchbitmapand", 0x36),
    ("batchbitmapandnot", 0x38),
    ("batchbitmapandnotscratch", 0x3c),
    ("batchbitmapandscratch", 0x3a),
    ("batchbitmapor", 0x37),
    ("batchbitmaporscratch", 0x3b),
    ("batchbitmapremove", 0x35),
    ("batchbitmapxor", 0x39),
    ("batchbitmapxorscratch", 0x3d),
    ("batchmapremove", 0x23),
    ("batchmapremoveif", 0x2b),
    ("batchmapupsertfirst", 0x21),
    ("batchmapupsertfirstif", 0x29),
    ("batchmapupsertlast", 0x22),
    ("batchmapupsertlastif", 0x2a),
    ("batchmapupsertlastttl", 0x25),
    ("batchmapupsertlatest", 0x20),
    ("batchmapupsertlatestif", 0x28),
    ("batchmapupsertlatestttl", 0x24),
    ("batchmapupsertmax", 0x26),
    ("batchmapupsertmaxif", 0x2c),
    ("batchmapupsertmin", 0x27),
    ("batchmapupsertminif", 0x2d),
    ("batchscalarlatest", 0x48),
    ("batchsetinsert", 0x30),
    ("batchsetinsertif", 0x33),
    ("batchsetinsertttl", 0x32),
    ("batchsetremove", 0x31),
    ("batchstructmapprobe", 0x2e),
    ("batchstructmapprobescatter", 0x2f),
    ("batchstructmap2remove", 0x86),
    ("batchstructmap2upsertlast", 0x83),
    ("batchstructmap2upsertmaxi64x2", 0x87),
    ("batchstructmapupsertfirst", 0x81),
    ("batchstructmapupsertlast", 0x80),
    ("batchstructmapupsertmax", 0x82),
    ("flatmap", 0xe1),
    ("foreach", 0xe0),
    ("halt", 0x00),
    ("listappend", 0x84),
    ("listappendstruct", 0x85),
    ("slotarray", 0x14),
    ("slotdef", 0x10),
    ("slotorderedlist", 0x19),
    ("slotstructmap", 0x18),
    ("slotstructmap2", 0x1b),
];
pub const ZIG_DISPATCHED_BYTES: &[u8] = &[
    0x00, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e,
    0x2f, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x40,
    0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x80, 0x81, 0x82, 0x83, 0x84,
    0x85, 0x86, 0x87, 0x90, 0x92, 0x95, 0xe0, 0xe1,
];
pub const FLAT_UNDO_OPS: &[(&str, u8)] = &[
    ("aggupdate", 0x06),
    ("countupdate", 0x0b),
    ("factinsertnew", 0x07),
    ("factinsertupdate", 0x08),
    ("factretract", 0x09),
    ("listappendundo", 0x0a),
    ("mapdelete", 0x03),
    ("mapinsert", 0x01),
    ("mapupdate", 0x02),
    ("setdelete", 0x05),
    ("setinsert", 0x04),
    ("structmapfield", 0x0c),
    ("structmaprow", 0x0d),
];
pub const RETE_OPCODES: &[(&str, u8)] = &[
    ("alphacolfiltereq", 0x58),
    ("alphacolfilterge", 0x5d),
    ("alphacolfiltergt", 0x5c),
    ("alphacolfilterle", 0x5b),
    ("alphacolfilterlt", 0x5a),
    ("alphacolfilterne", 0x59),
    ("alphamapget", 0x52),
    ("alphasetcontains", 0x53),
    ("alphaslotbind", 0x50),
    ("alphaslotchanges", 0x54),
    ("alphaslotevicted", 0x56),
    ("alphaslotindexbind", 0x55),
    ("alphaslotsize", 0x51),
    ("betabvand", 0x60),
    ("betabvclear", 0x64),
    ("betabvcopy", 0x63),
    ("betabvnot", 0x62),
    ("betabvor", 0x61),
    ("betabvsetall", 0x65),
    ("betaevalax", 0x6f),
    ("betaevalwhen", 0x68),
    ("betaiterbvnext", 0x6a),
    ("betaiterbvstart", 0x69),
    ("halt", 0x00),
    ("negbvandnot", 0x6e),
    ("prodfirerules", 0x73),
    ("prodinsertfact", 0x70),
    ("prodqueuedecision", 0x72),
    ("prodretractfact", 0x71),
];
