/**
 * LMAO-specific types for trace logging
 *
 * These types extend the generic ColumnBuffer from arrow-builder
 * with span-specific fields and tracing concepts.
 *
 * **Unified SpanBuffer Memory Layout**
 *
 * SpanBuffer uses a unified memory layout per specs/01b_columnar_buffer_architecture.md:
 * - Single `_system` ArrayBuffer contains timestamps + operations + identity
 * - Identity stored inline (root/child) or shared reference (chained)
 * - Parent ancestry via pointer (not copied bytes)
 * - O(1) isParentOf/isChildOf via pointer comparison
 */
import type { TypedColumnBuffer } from '@smoothbricks/arrow-builder';
import type { ModuleContext } from './moduleContext.js';
import type { LogSchema } from './schema/LogSchema.js';
import type { TraceId } from './traceId.js';

// Re-export context classes
export { ModuleContext } from './moduleContext.js';

/**
 * SpanBuffer - lmao-specific extension of TypedColumnBuffer
 *
 * Adds span tree structure and task context to the base TypedColumnBuffer.
 *
 * **Type Parameter**
 *
 * `T` is a LogSchema. The buffer gets typed setters for `T['fields']`.
 *
 * **Naming Convention**
 *
 * System properties use `_` prefix to avoid collision with user column names:
 * - `_system`, `_identity`, `_timestamps`, `_operations`, `_writeIndex`, `_capacity`, `_next`
 *
 * User columns use NO prefix - just the field name:
 * - `userId`, `userId_values`, `userId_nulls`
 *
 * **Unified Memory Layout (per specs/01b_columnar_buffer_architecture.md)**
 *
 * Single `_system` ArrayBuffer contains:
 * - timestamps (BigInt64Array) at offset 0
 * - operations (Uint8Array) at offset capacity * 8
 * - identity (Uint8Array) at offset capacity * 9 (for root/child, not chained)
 *
 * Identity layout:
 * - ROOT: [threadId(8)][spanId(4)][traceIdLen(1)][traceId(N)]
 * - CHILD: [threadId(8)][spanId(4)] (12 bytes, parent via pointer)
 * - CHAINED: shares identity reference from first buffer
 *
 * Parent ancestry is via `parent` pointer, not copied bytes.
 * This makes isParentOf/isChildOf O(1) pointer comparisons.
 */

/**
 * SpanBuffer type - parameterized by LogSchema. Uses T['fields'] for column types.
 */
export type SpanBuffer<T extends LogSchema = LogSchema> = TypedColumnBuffer<T['fields']> & {
  // ============================================================================
  // System Column Setters (generated by arrow-builder)
  // Pattern: buffer.columnName(position, value) => SpanBuffer<T>
  //
  // Note: Returns SpanBuffer<T> instead of `this` because SpanBuffer must be
  // a type alias to extend TypedColumnBuffer (which uses mapped types with
  // computed property names - not supported by interfaces).
  // ============================================================================

  /**
   * Set unified message at position (category/string column).
   * Used for span names, log messages, exception messages, result messages, and FF names.
   */
  message(pos: number, val: string): SpanBuffer<T>;

  /** Set line number at position (number column) */
  lineNumber(pos: number, val: number): SpanBuffer<T>;

  /** Set error code at position (category/string column) */
  errorCode(pos: number, val: string): SpanBuffer<T>;

  /** Set exception stack at position (text/string column) */
  exceptionStack(pos: number, val: string): SpanBuffer<T>;

  /** Set feature flag value at position (category/string column) */
  ffValue(pos: number, val: string): SpanBuffer<T>;

  // ============================================================================
  // Unified System ArrayBuffer
  // ============================================================================

  /**
   * The unified ArrayBuffer containing timestamps, operations, and identity.
   * Layout: [timestamps (8*capacity)] [operations (1*capacity)] [identity (variable)]
   */
  readonly _system: ArrayBuffer;

  /**
   * Identity bytes (Uint8Array view into _system or shared reference for chained).
   * - Root: 13 + traceId.length bytes at offset capacity * 9
   * - Child: 12 bytes at offset capacity * 9
   * - Chained: shared reference to first buffer's identity
   */
  readonly _identity: Uint8Array;

  // ============================================================================
  // Convenient aliases for system columns (same as ColumnBuffer._timestamps etc.)
  // These are generated as direct references in spanBuffer.ts
  // ============================================================================

  /** Alias for _timestamps - nanosecond-precision timestamps */
  readonly timestamps: BigInt64Array;

  /** Alias for _operations - entry type codes */
  readonly operations: Uint8Array;

  /** Alias for _writeIndex - current write position */
  writeIndex: number;

  /** Alias for _capacity - buffer capacity */
  readonly capacity: number;

  /** Alias for _next - chain to overflow buffer */
  next?: SpanBuffer<T>;

  // ============================================================================
  // Identity Getters (read from _identity bytes)
  // ============================================================================

  /**
   * Span ID (32-bit unsigned integer).
   * Read from _identity bytes 8-11 (little-endian).
   */
  readonly spanId: number;

  /**
   * Thread ID (64-bit unsigned integer as BigInt).
   * Read from _identity bytes 0-7 (little-endian).
   * Used for Arrow conversion (cold path).
   */
  readonly threadId: bigint;

  /**
   * Trace ID for this span.
   * For root spans: decoded from _identity bytes [12]=len, [13+]=traceId
   * For child/chained spans: walks up parent chain to root
   */
  readonly traceId: TraceId;

  /**
   * Whether this span has a parent.
   * Equivalent to `parent !== undefined`.
   */
  readonly hasParent: boolean;

  /**
   * Parent's spanId (0 if no parent).
   * Derived from parent?.spanId.
   */
  readonly parentSpanId: number;

  // ============================================================================
  // Tree Structure
  // ============================================================================

  /**
   * Child spans (lmao-specific for span hierarchy).
   */
  children: SpanBuffer<T>[];

  /**
   * Parent span buffer.
   * Used to derive traceId, parentSpanId, and for isParentOf/isChildOf.
   */
  parent?: SpanBuffer<T>;

  // ============================================================================
  // Context
  // ============================================================================

  /**
   * Op's module context (what code is executing).
   * Used for rows 1+ metadata (gitSha, packageName, packagePath).
   *
   * Per specs/01c_context_flow_and_op_wrappers.md and 01b5_spanbuffer_memory_layout.md.
   */
  module: ModuleContext;

  /**
   * Span name for this invocation.
   */
  spanName: string;

  /**
   * Pre-encoded UTF-8 bytes for span name (for Arrow conversion).
   */
  utf8SpanName: Uint8Array;

  /**
   * The caller's module context (where span() was invoked from).
   *
   * Used for row 0 (span-start) metadata attribution - records WHERE the span
   * was invoked from, not where the code is executing.
   *
   * For root spans: undefined (no caller, or same as module)
   * For child spans: the parent span's module context
   *
   * Access pattern (per specs/01c_context_flow_and_op_wrappers.md):
   * - Row 0: buffer.callsiteModule?.packageName (caller's module)
   * - Rows 1+: buffer.module.packageName (op's module)
   */
  callsiteModule?: ModuleContext;

  /**
   * Scoped attribute values for this span.
   *
   * Updated when ctx.setScope() is called, and inherited by child spans.
   * Stored here so child spans can access parent's scope during Op._invoke.
   *
   * Child spans inherit parent's scopeValues BY REFERENCE (safe because immutable/frozen).
   * This enables zero-cost scope inheritance and async-safe snapshot semantics.
   *
   * NOT initialized in constructor to avoid allocating empty objects that get replaced.
   * - Root context: set to Object.freeze({}) in op.ts
   * - Child spans: set to parent's scopeValues reference in op.ts/spanContext.ts
   *
   * @internal Set by SpanLogger._setScope() or during span creation
   */
  scopeValues?: Readonly<Record<string, unknown>>;

  // ============================================================================
  // Methods
  // ============================================================================

  /**
   * Check if this span is the parent of another span.
   * O(1) pointer comparison: `this === other.parent`
   */
  isParentOf(other: SpanBuffer<T>): boolean;

  /**
   * Check if this span is a child of another span.
   * O(1) pointer comparison: `this.parent === other`
   */
  isChildOf(other: SpanBuffer<T>): boolean;

  /**
   * Copy threadId bytes (8 bytes) to destination at offset.
   * Used for Arrow conversion (cold path).
   */
  copyThreadIdTo(dest: Uint8Array, offset: number): void;

  /**
   * Copy parent's threadId bytes (8 bytes) to destination.
   * If no parent, fills with zeros.
   */
  copyParentThreadIdTo(dest: Uint8Array, offset: number): void;
};

// Re-export useful arrow-builder types for convenience
export type { ColumnBuffer } from '@smoothbricks/arrow-builder';
