//! The N-API projection of the controller's operation table: which handle may call which
//! operation and how it builds that operation's request (cowshed-core's `Serves` impls), one Rust
//! adapter per served operation in `cowshed-napi`, and the TypeScript that declares and calls it.
//!
//! A handle class serves an operation of its namespaces whose scope its authority admits: a
//! worker capability never reaches a coordinator-scoped operation, whatever its namespace. The
//! handle binds every request field its authority holds — the [`Class::authority`] fields the
//! request record declares — and the caller names the rest. The generated `Serves` impl clones
//! the bound fields from the handle's validated authority, except an optional one outside the
//! class's [`Class::fence`], which it sends absent, and decodes only the caller's, as a record of
//! exactly those fields mirroring the declaration's serde spelling, so neither the addon nor any
//! other caller chooses a bound field and the authority never round-trips through JSON.
//! The TypeScript wrapper's argument type is `Pick<Request, …>` over exactly the caller's fields,
//! so a request field the declaration renames, adds or drops moves the binding, the construction
//! and the adapter's `.d.ts` together.

use crate::ir::{Api, Field, Fields, Record, Shape};
use crate::operations::{Lane, Operation, Scope};
use std::collections::BTreeMap;
use std::fmt::Write;
use syn::{GenericArgument, PathArguments, Type};

const HEADER: &str =
    "// Generated by cowshed-api-gen from cowshed-core's operation table. Do not edit.\n";

/// A handle class: the namespaces whose operations it serves, the scopes its authority admits, the
/// fence a request it serves must declare, and the request fields its authority supplies. A served
/// request binds every fence field from the handle, so no caller can name another workspace or
/// job; a request that leaves one undeclared is refused, never served with that field left to the
/// caller. An authority field outside the fence is bound too, but asserted only where the request
/// requires it: an optional one is sent absent (see [`Supply`]).
struct Class {
    rust: &'static str,
    namespaces: &'static [&'static str],
    scopes: &'static [Scope],
    fence: &'static [&'static str],
    authority: &'static [&'static str],
}

impl Class {
    fn serves(&self, operation: &Operation) -> bool {
        self.namespaces.contains(&operation.prefix()) && self.scopes.contains(&operation.scope)
    }
}

const WORKSPACE_AUTHORITY: &[&str] = &["repoId", "workspace", "workspaceIncarnation"];
const JOB_AUTHORITY: &[&str] = &["repoId", "workspace", "workspaceIncarnation", "jobId"];

const CLASSES: &[Class] = &[
    Class {
        rust: "Project",
        namespaces: &["project"],
        scopes: &[Scope::Coordinator],
        fence: &["repoId"],
        authority: &["repoId"],
    },
    // A read-only reference names one workspace: it holds the incarnation it was resolved at, but
    // a recreated name is still the workspace it refers to.
    Class {
        rust: "WorkspaceRef",
        namespaces: &["workspace"],
        scopes: &[Scope::Coordinator, Scope::Worker],
        fence: &["repoId", "workspace"],
        authority: WORKSPACE_AUTHORITY,
    },
    Class {
        rust: "Coordinator",
        namespaces: &["coordinator"],
        scopes: &[Scope::Coordinator],
        fence: &["repoId"],
        authority: &["repoId"],
    },
    Class {
        rust: "WorkspaceHandle",
        namespaces: &["workspace", "worker", "session"],
        scopes: &[Scope::Worker],
        fence: WORKSPACE_AUTHORITY,
        authority: WORKSPACE_AUTHORITY,
    },
    Class {
        rust: "JobHandle",
        namespaces: &["job"],
        scopes: &[Scope::Worker],
        fence: JOB_AUTHORITY,
        authority: JOB_AUTHORITY,
    },
];

/// What a handle supplies for a request field it binds.
#[derive(Clone, Copy, Eq, PartialEq)]
enum Supply {
    /// The value its authority holds: every fence field, and any field the request requires.
    Held,
    /// `None`: an optional field the authority holds outside the handle's fence. The handle does
    /// not assert it, and it stays bound, so no caller chooses it either.
    Absent,
}

/// A request field a handle binds, as the wire spells it, and what the handle supplies there.
struct Bound {
    wire: String,
    supply: Supply,
}

/// What a call answers JavaScript with.
#[derive(Clone, Copy, Eq, PartialEq)]
enum Answer {
    /// The declared result, as canonical JSON.
    Json,
    /// A download chunk's metadata and bytes.
    Download,
    /// A reference to the one workspace the result is.
    Workspace,
    /// The worker capability the result was minted as.
    Worker,
    /// A handle to the one job the result names.
    Job,
}

impl Answer {
    fn of(operation: &Operation, class: &Class) -> Result<Self, String> {
        let result = path_name(&operation.result);
        Ok(match (&operation.lane, result.as_deref(), class.rust) {
            (Lane::Download(_), _, _) => Self::Download,
            (_, Some("WorkspaceView"), _) => Self::Workspace,
            (_, Some("WorkerView"), "Coordinator") => Self::Worker,
            (_, Some("WorkerView"), _) => {
                return Err(format!(
                    "{}: only the coordinator mints a worker capability",
                    operation.method
                ));
            }
            (_, Some("JobId" | "JobInfo"), "WorkspaceHandle") => Self::Job,
            _ => Self::Json,
        })
    }

    /// The TypeScript type the addon method resolves to.
    fn native(self) -> &'static str {
        match self {
            Self::Json => "string",
            Self::Download => "NativeDownload",
            Self::Workspace => "NativeWorkspaceRefHandle",
            Self::Worker => "NativeWorkspaceHandle",
            Self::Job => "NativeJobHandle",
        }
    }
}

/// An operation's request record, and its fields with the name each travels as.
struct Request<'a> {
    name: String,
    record: &'a Record,
    fields: Vec<(String, &'a Field)>,
}

/// One operation as one class serves it: the request fields it binds and those its caller names.
struct Method<'a> {
    operation: &'a Operation,
    request: &'a Request<'a>,
    bound: Vec<Bound>,
    caller: Vec<String>,
    answer: Answer,
}

/// One operation as every class that serves it takes and answers it.
struct Signature<'a> {
    operation: &'a Operation,
    caller: Vec<String>,
    answer: Answer,
}

pub struct Output {
    /// cowshed-core's `Serves` impls.
    pub served: String,
    /// cowshed-napi's adapters.
    pub rust: String,
    /// The adapters' TypeScript declarations and typed wrappers.
    pub typescript: String,
}

pub fn emit(operations: &[Operation], api: &Api) -> Result<Output, String> {
    let requests = operations
        .iter()
        .filter(|operation| operation.scope != Scope::Internal)
        .map(|operation| Ok((operation, request(operation, api)?)))
        .collect::<Result<Vec<_>, String>>()?;
    let mut classes: Vec<(&Class, Vec<Method<'_>>)> =
        CLASSES.iter().map(|class| (class, Vec::new())).collect();
    // Each operation takes one argument type and answers one way, whichever class serves it.
    let mut served: BTreeMap<&str, Signature<'_>> = BTreeMap::new();
    for (operation, request) in &requests {
        let mut serving = false;
        for (class, methods) in &mut classes {
            if !class.serves(operation) {
                continue;
            }
            serving = true;
            let mut bound = Vec::new();
            let mut caller = Vec::new();
            for (wire, field) in &request.fields {
                if !class.authority.contains(&wire.as_str()) {
                    caller.push(wire.clone());
                    continue;
                }
                let supply = if class.fence.contains(&wire.as_str()) || !is_option(&field.ty) {
                    Supply::Held
                } else {
                    Supply::Absent
                };
                bound.push(Bound {
                    wire: wire.clone(),
                    supply,
                });
            }
            // A request that names none of the class's authority is how a handle is reached, not
            // a method of one: `project.open` opens the project the handles belong to.
            if bound.is_empty() {
                continue;
            }
            if let Some(missing) = class
                .fence
                .iter()
                .find(|field| !bound.iter().any(|bound| bound.wire == **field))
            {
                return Err(format!(
                    "{}: {} serves it but its request does not name {missing}, which the handle \
                     fences, so a caller could name another",
                    operation.method, class.rust
                ));
            }
            let method = Method {
                operation,
                request,
                bound,
                caller,
                answer: Answer::of(operation, class)?,
            };
            match served.get(operation.method.as_str()) {
                Some(other) if other.caller != method.caller || other.answer != method.answer => {
                    return Err(format!(
                        "{}: its handles take different arguments or answer differently",
                        operation.method
                    ));
                }
                Some(_) => {}
                None => {
                    served.insert(
                        &operation.method,
                        Signature {
                            operation,
                            caller: method.caller.clone(),
                            answer: method.answer,
                        },
                    );
                }
            }
            methods.push(method);
        }
        if !serving {
            return Err(format!(
                "{}: no handle serves the {} namespace at {:?} scope",
                operation.method,
                operation.prefix(),
                operation.scope
            ));
        }
    }
    Ok(Output {
        served: serves(&classes)?,
        rust: rust(&classes)?,
        typescript: typescript(&classes, &served, api)?,
    })
}

/// Marks every record a projected operation names as exported, so its TypeScript type and
/// validator exist wherever its declaration lives: an operation's request and result are public
/// API whether or not another public record reaches them.
pub fn export_records(operations: &[Operation], api: &mut Api) -> Result<(), String> {
    for operation in operations
        .iter()
        .filter(|operation| operation.scope != Scope::Internal)
    {
        let request = path_name(&operation.request)
            .ok_or_else(|| format!("{}: the request is not a named record", operation.method))?;
        let (result, _) = result_record(&operation.result)
            .map_err(|error| format!("{}: {error}", operation.method))?;
        for name in [request, result] {
            api.records
                .get_mut(&name)
                .ok_or_else(|| format!("{}: {name} has no declaration", operation.method))?
                .exported = true;
        }
    }
    Ok(())
}

/// The request record of `operation`, and its fields with their wire names in declaration order.
/// The generated construction decodes the caller's fields as a record mirroring this one, so the
/// declaration may only use the serde spellings that record reproduces exactly.
fn request<'a>(operation: &Operation, api: &'a Api) -> Result<Request<'a>, String> {
    let name = path_name(&operation.request)
        .ok_or_else(|| format!("{}: the request is not a named record", operation.method))?;
    let record = api
        .records
        .get(&name)
        .ok_or_else(|| format!("{}: request {name} has no declaration", operation.method))?;
    let Shape::Struct(Fields::Named(fields)) = &record.shape else {
        return Err(format!(
            "{}: request {name} is not a record of named fields",
            operation.method
        ));
    };
    let container = &record.serde;
    if container.tag.is_some()
        || container.content.is_some()
        || container.untagged
        || container.transparent
        || container.default
        || container.rename_all_fields.is_some()
        || container.from.is_some()
        || container.into.is_some()
    {
        return Err(format!(
            "{}: request {name} declares a container serde attribute other than rename_all and \
             deny_unknown_fields, which its generated construction does not mirror",
            operation.method
        ));
    }
    let fields = fields
        .iter()
        .map(|field| {
            if field.serde.flatten {
                return Err(format!(
                    "{}: request {name} flattens a field, which no caller can name",
                    operation.method
                ));
            }
            if field.serde.skip || field.serde.deserialize_with.is_some() {
                return Err(format!(
                    "{}: request {name} skips or custom-decodes a field, which its generated \
                     construction does not mirror",
                    operation.method
                ));
            }
            let rust = field
                .name
                .as_deref()
                .ok_or_else(|| format!("{name}: a named field without a name"))?;
            let wire = crate::typescript::renamed(
                rust,
                field.serde.rename.as_deref(),
                record.serde.rename_all.as_deref(),
            )?;
            Ok((wire, field))
        })
        .collect::<Result<_, String>>()?;
    Ok(Request {
        name,
        record,
        fields,
    })
}

/// A request field's type as Rust source: a path whose generic arguments are types, written as
/// the declaration writes it, so it names what the operation table's scope names.
fn rust_type(ty: &Type) -> Result<String, String> {
    let Type::Path(path) = ty else {
        return Err("a request field's type is a path".to_owned());
    };
    if path.qself.is_some() {
        return Err("a request field's type is a plain path".to_owned());
    }
    let mut source = String::new();
    if path.path.leading_colon.is_some() {
        source.push_str("::");
    }
    for (index, segment) in path.path.segments.iter().enumerate() {
        if index > 0 {
            source.push_str("::");
        }
        source.push_str(&segment.ident.to_string());
        match &segment.arguments {
            PathArguments::None => {}
            PathArguments::AngleBracketed(arguments) => {
                source.push('<');
                for (index, argument) in arguments.args.iter().enumerate() {
                    let GenericArgument::Type(argument) = argument else {
                        return Err(format!(
                            "{}: a request field's generic arguments are types",
                            segment.ident
                        ));
                    };
                    if index > 0 {
                        source.push_str(", ");
                    }
                    source.push_str(&rust_type(argument)?);
                }
                source.push('>');
            }
            PathArguments::Parenthesized(_) => {
                return Err(format!(
                    "{}: a request field is not a closure",
                    segment.ident
                ));
            }
        }
    }
    Ok(source)
}

/// The last path segment of a type with no generic arguments: `JobInfo` for `JobInfo`, none for
/// `Vec<JobInfo>`.
fn path_name(ty: &Type) -> Option<String> {
    let Type::Path(path) = ty else {
        return None;
    };
    let segment = path.path.segments.last()?;
    matches!(segment.arguments, PathArguments::None).then(|| segment.ident.to_string())
}

/// Whether a field's declared type is `Option<…>`. Spelled, not resolved: a type that only looks
/// optional fails to compile in the generated construction rather than binding the wrong value.
fn is_option(ty: &Type) -> bool {
    let Type::Path(path) = ty else {
        return false;
    };
    path.path.segments.last().is_some_and(|segment| {
        segment.ident == "Option" && matches!(segment.arguments, PathArguments::AngleBracketed(_))
    })
}

fn snake(name: &str) -> String {
    let mut snake = String::with_capacity(name.len() + 4);
    for character in name.chars() {
        if character.is_ascii_uppercase() {
            snake.push('_');
            snake.push(character.to_ascii_lowercase());
        } else {
            snake.push(character);
        }
    }
    snake
}

fn capitalized(name: &str) -> String {
    let mut characters = name.chars();
    characters.next().map_or_else(String::new, |first| {
        first.to_ascii_uppercase().to_string() + characters.as_str()
    })
}

/// The wrapper function's name: `jobLogs` for `job.logs`.
fn function(operation: &Operation) -> String {
    format!("{}{}", operation.prefix(), capitalized(operation.name()))
}

/// cowshed-core's `Serves` impls, generated as a child of the operation table's module so they
/// name request records and field types as the table does; and, for tests, every pair visited.
fn serves(classes: &[(&Class, Vec<Method<'_>>)]) -> Result<String, String> {
    let mut output = format!(
        "{HEADER}//! Which handle may call which operation, the request fields it binds for it, and that\n\
         //! operation's request built from them: the bound fields cloned from the handle's authority\n\
         //! (an optional one outside its fence sent as `None`), the rest decoded from the caller's\n\
         //! arguments as a record of exactly those fields.\n\n\
         use super::*;\n\
         use crate::api::call::{{Arguments, Binder, Serves, decode, owned}};\n\
         use crate::api::capability::{{Coordinator, JobHandle, Project, WorkspaceHandle, WorkspaceRef}};\n"
    );
    for (class, methods) in classes {
        for method in methods {
            serve(&mut output, class, method)?;
        }
    }
    output.push_str(
        "\n/// A check that must hold for every operation each handle serves. `absent` names the bound\n\
         /// fields the handle supplies as `None`: optional fields its authority holds but does not fence.\n\
         #[cfg(test)]\n\
         pub(crate) trait EachServed {\n    \
             fn served<O: Operation, H: Serves<O>>(&mut self, handle: &H, absent: &[&str])\n    \
             where\n        \
                 O::Request: PartialEq + std::fmt::Debug;\n\
         }\n\n\
         /// Runs `check` over every operation each handle serves, through the given handles.\n\
         #[cfg(test)]\n\
         pub(crate) fn each_served(\n    check: &mut impl EachServed,\n",
    );
    for (class, _) in classes {
        writeln!(output, "    {}: &{},", parameter(class.rust), class.rust).unwrap();
    }
    output.push_str(") {\n");
    for (class, methods) in classes {
        for method in methods {
            let absent = method
                .bound
                .iter()
                .filter(|bound| bound.supply == Supply::Absent)
                .map(|bound| format!("{:?}", bound.wire))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                output,
                "    check.served::<{}, _>({}, &[{absent}]);",
                method.operation.marker,
                parameter(class.rust)
            )
            .unwrap();
        }
    }
    output.push_str("}\n");
    Ok(output)
}

/// One `Serves` impl: the bound field names, and the request built from the handle's authority
/// and a record of exactly the caller's fields, spelled as the declaration spells them.
fn serve(output: &mut String, class: &Class, method: &Method<'_>) -> Result<(), String> {
    let operation = method.operation;
    let request = method.request;
    let bound = method
        .bound
        .iter()
        .map(|bound| format!("{:?}", bound.wire))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        output,
        "\nimpl Serves<{}> for {} {{\n    const BOUND: &'static [&'static str] = &[{bound}];\n\n    \
         fn request(authority: &<Self as Binder>::Fields<'_>, arguments: Arguments) -> Result<{}> {{\n        \
         #[derive(Deserialize)]",
        operation.marker, class.rust, request.name
    )
    .unwrap();
    let container = [
        request
            .record
            .serde
            .rename_all
            .as_ref()
            .map(|rename_all| format!("rename_all = {rename_all:?}")),
        request
            .record
            .serde
            .deny_unknown_fields
            .then(|| "deny_unknown_fields".to_owned()),
    ]
    .into_iter()
    .flatten()
    .collect::<Vec<_>>();
    if !container.is_empty() {
        writeln!(output, "        #[serde({})]", container.join(", ")).unwrap();
    }
    output.push_str("        struct Caller {\n");
    let mut caller = Vec::new();
    let mut literal = Vec::new();
    for (wire, field) in &request.fields {
        let name = field
            .name
            .as_deref()
            .ok_or_else(|| format!("{}: a named field without a name", request.name))?;
        if let Some(bound) = method.bound.iter().find(|bound| bound.wire == *wire) {
            literal.push(match (bound.supply, is_option(&field.ty)) {
                (Supply::Absent, _) => format!("{name}: None"),
                (Supply::Held, true) => format!("{name}: Some(owned(authority.{}))", snake(wire)),
                (Supply::Held, false) => format!("{name}: owned(authority.{})", snake(wire)),
            });
            continue;
        }
        let attributes = [
            field
                .serde
                .rename
                .as_ref()
                .map(|rename| format!("rename = {rename:?}")),
            // A default function is named as the declaration names it: the construction is a
            // child of the table's module, so the same path resolves to the same function.
            field
                .serde
                .default
                .then(|| match &field.serde.default_with {
                    Some(function) => format!("default = {function:?}"),
                    None => "default".to_owned(),
                }),
        ]
        .into_iter()
        .flatten()
        .collect::<Vec<_>>();
        if !attributes.is_empty() {
            writeln!(output, "            #[serde({})]", attributes.join(", ")).unwrap();
        }
        writeln!(output, "            {name}: {},", rust_type(&field.ty)?).unwrap();
        caller.push(name);
        literal.push(name.to_owned());
    }
    writeln!(
        output,
        "        }}\n        let Caller {{ {} }} = decode::<{}, Caller>(arguments)?;\n        \
         Ok({} {{ {} }})\n    }}\n}}",
        caller.join(", "),
        operation.marker,
        request.name,
        literal.join(", ")
    )
    .unwrap();
    Ok(())
}

/// A class's parameter name: `workspace_ref` for `WorkspaceRef`.
fn parameter(class: &str) -> String {
    let mut characters = class.chars();
    characters.next().map_or_else(String::new, |first| {
        snake(&(first.to_ascii_lowercase().to_string() + characters.as_str()))
    })
}

fn rust(classes: &[(&Class, Vec<Method<'_>>)]) -> Result<String, String> {
    let mut output = format!(
        "{HEADER}//! One adapter per controller operation, on each handle that serves it.\n\n\
         use super::{{Coordinator, JobHandle, Project, WorkspaceHandle, WorkspaceRef}};\n\
         use cowshed_core::api::operations;\n\
         use napi::{{Env, JsObject, bindgen_prelude::Buffer}};\n\
         use napi_derive::napi;\n\
         use std::sync::Arc;\n"
    );
    for (class, methods) in classes {
        writeln!(output, "\n#[napi]\nimpl {} {{", class.rust).unwrap();
        for (index, method) in methods.iter().enumerate() {
            if index > 0 {
                output.push('\n');
            }
            let operation = method.operation;
            for line in &operation.docs {
                writeln!(output, "    /// {line}").unwrap();
            }
            let upload = operation.lane == Lane::Upload;
            let bytes = if upload {
                ", bytes: Option<Buffer>"
            } else {
                ""
            };
            writeln!(
                output,
                "    #[napi(js_name = {:?})]\n    pub fn {}(&self, env: Env, arguments: String{bytes}) -> napi::Result<JsObject> {{",
                operation.name(),
                snake(operation.name()),
            )
            .unwrap();
            let helper = match (method.answer, upload) {
                (Answer::Json, false) => "json_call",
                (Answer::Json, true) => "upload_call",
                (Answer::Download, false) => "download_call",
                (Answer::Workspace, false) => "workspace_call",
                (Answer::Worker, false) => "worker_call",
                (Answer::Job, false) => "job_call",
                (Answer::Job, true) => "job_upload_call",
                (Answer::Download | Answer::Workspace | Answer::Worker, true) => {
                    return Err(format!(
                        "{}: an upload answers JSON or a job",
                        operation.method
                    ));
                }
            };
            let generics = match method.answer {
                Answer::Json | Answer::Download | Answer::Workspace => {
                    format!("operations::{}, _", operation.marker)
                }
                Answer::Worker | Answer::Job => format!("operations::{}", operation.marker),
            };
            let bytes = if upload { ", bytes" } else { "" };
            writeln!(
                output,
                "        super::{helper}::<{generics}>(env, Arc::clone(&self.inner), arguments{bytes})\n    }}",
            )
            .unwrap();
        }
        output.push_str("}\n");
    }
    Ok(output)
}

fn typescript(
    classes: &[(&Class, Vec<Method<'_>>)],
    served: &BTreeMap<&str, Signature<'_>>,
    api: &Api,
) -> Result<String, String> {
    let mut output = format!(
        "{HEADER}/// <reference types=\"node\" />\n\n\
         import type * as Api from './api.generated.js';\n\
         import type {{ NativeJobHandle, NativeWorkspaceHandle, NativeWorkspaceRefHandle }} from './native.js';\n\
         import * as V from './validators.generated.js';\n\n\
         /** A download's answer: its chunk's metadata as JSON, and the bytes it describes. */\n\
         export interface NativeDownload {{\n  readonly json: string;\n  readonly bytes: Buffer;\n}}\n"
    );
    for (class, methods) in classes.iter().filter(|(_, methods)| !methods.is_empty()) {
        let extends = methods
            .iter()
            .map(|method| format!("Native{}", capitalized(&function(method.operation))))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            output,
            "\n/** The operations a `{0}` serves: exactly those its authority admits. */\nexport interface Native{0}Operations extends {extends} {{}}",
            class.rust
        )
        .unwrap();
    }
    let record_name = |rust: &str| -> Result<String, String> {
        let record = api
            .records
            .get(rust)
            .ok_or_else(|| format!("API type {rust} has no declaration"))?;
        Ok(record
            .projection
            .name
            .clone()
            .unwrap_or_else(|| rust.to_owned()))
    };
    for method in served.values() {
        let operation = method.operation;
        let function = function(operation);
        let interface = format!("Native{}", capitalized(&function));
        let arguments = format!("{}Arguments", capitalized(&function));
        let upload = operation.lane == Lane::Upload;
        writeln!(
            output,
            "\n/** A handle that serves `{}`. */\nexport interface {interface} {{\n  {}(argumentsJson: string{}): Promise<{}>;\n}}",
            operation.method,
            operation.name(),
            if upload { ", bytes?: Buffer" } else { "" },
            method.answer.native(),
        )
        .unwrap();
        let request = record_name(
            &path_name(&operation.request)
                .ok_or_else(|| format!("{}: unnamed request", operation.method))?,
        )?;
        // A handle that binds every field takes exactly `{}`: `Pick<Request, never>` would be the
        // empty object type, which admits any non-nullish value.
        let fields = if method.caller.is_empty() {
            "Readonly<Record<string, never>>".to_owned()
        } else {
            let picked = method
                .caller
                .iter()
                .map(|field| format!("'{field}'"))
                .collect::<Vec<_>>()
                .join(" | ");
            format!("Pick<Api.{request}, {picked}>")
        };
        writeln!(
            output,
            "\n/** The request fields a `{}` caller names; its handle binds the rest. */\nexport type {arguments} = {fields};\n",
            operation.method
        )
        .unwrap();
        output.push_str("/**\n");
        for line in &operation.docs {
            writeln!(output, " * {line}").unwrap();
        }
        output.push_str(" */\n");
        let bytes_parameter = if upload { ", bytes?: Uint8Array" } else { "" };
        let bytes_argument = if upload {
            ", bytes === undefined ? undefined : Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength)"
        } else {
            ""
        };
        let call = format!(
            "handle.{}(JSON.stringify(args){bytes_argument})",
            operation.name()
        );
        let (returns, body) = match method.answer {
            Answer::Json => {
                let (ty, validator) = result_type(&operation.result, &record_name)?;
                (ty, format!("return V.{validator}(await {call});"))
            }
            Answer::Download => {
                let (ty, validator) = result_type(&operation.result, &record_name)?;
                (
                    format!("{ty} & {{ readonly bytes: Uint8Array }}"),
                    format!(
                        "const answer = await {call};\n  return {{ ...V.{validator}(answer.json), bytes: answer.bytes }};"
                    ),
                )
            }
            Answer::Workspace | Answer::Worker | Answer::Job => {
                (method.answer.native().to_owned(), format!("return {call};"))
            }
        };
        writeln!(
            output,
            "export async function {function}(handle: {interface}, args: {arguments}{bytes_parameter}): Promise<{returns}> {{\n  {body}\n}}"
        )
        .unwrap();
    }
    Ok(output)
}

/// A JSON result's record, and whether the result is a list of it.
fn result_record(ty: &Type) -> Result<(String, bool), String> {
    if let Some(name) = path_name(ty) {
        return Ok((name, false));
    }
    let Type::Path(path) = ty else {
        return Err("an operation result is a named record or a Vec of one".to_owned());
    };
    let segment = path
        .path
        .segments
        .last()
        .ok_or("an operation result has an empty path")?;
    let PathArguments::AngleBracketed(arguments) = &segment.arguments else {
        return Err(format!("unsupported operation result {}", segment.ident));
    };
    match (segment.ident.to_string().as_str(), arguments.args.first()) {
        ("Vec", Some(GenericArgument::Type(element))) if arguments.args.len() == 1 => {
            let element =
                path_name(element).ok_or("an operation result's element is a named record")?;
            Ok((element, true))
        }
        (ident, _) => Err(format!("unsupported operation result {ident}")),
    }
}

/// A JSON result's TypeScript type and the validator that parses it.
fn result_type(
    ty: &Type,
    record_name: &impl Fn(&str) -> Result<String, String>,
) -> Result<(String, String), String> {
    let (record, list) = result_record(ty)?;
    let name = record_name(&record)?;
    Ok(if list {
        (format!("readonly Api.{name}[]"), format!("parse{name}List"))
    } else {
        (format!("Api.{name}"), format!("parse{name}"))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn api() -> Api {
        let mut api = Api::default();
        crate::records::parse(
            r#"
            #[derive(Serialize, Deserialize)]
            #[serde(rename_all = "camelCase", deny_unknown_fields)]
            pub struct JobRequest {
                pub repo_id: RepoId,
                pub workspace: WorkspaceName,
                pub workspace_incarnation: WorkspaceIncarnation,
                pub job_id: JobId,
            }
            #[derive(Serialize, Deserialize)]
            #[serde(rename_all = "camelCase", deny_unknown_fields)]
            pub struct LogsRequest {
                pub repo_id: RepoId,
                pub workspace: WorkspaceName,
                pub workspace_incarnation: WorkspaceIncarnation,
                pub job_id: JobId,
                pub offset: u64,
            }
            #[derive(Serialize, Deserialize)]
            #[serde(rename_all = "camelCase", deny_unknown_fields)]
            pub struct WorkspaceRequest {
                pub repo_id: RepoId,
                pub workspace: WorkspaceName,
            }
            #[derive(Serialize, Deserialize)]
            #[serde(rename_all = "camelCase", deny_unknown_fields)]
            pub struct RepoRequest {
                pub repo_id: RepoId,
            }
            #[derive(Serialize, Deserialize)]
            #[serde(rename_all = "camelCase", deny_unknown_fields)]
            pub struct GrantsRequest {
                pub repo_id: RepoId,
                pub workspace: WorkspaceName,
                #[serde(default, skip_serializing_if = "Option::is_none")]
                pub workspace_incarnation: Option<WorkspaceIncarnation>,
            }
            #[derive(Serialize, Deserialize)]
            #[serde(rename_all = "camelCase", deny_unknown_fields)]
            pub struct WorkerScope {
                pub repo_id: RepoId,
                pub workspace: WorkspaceName,
                pub workspace_incarnation: WorkspaceIncarnation,
            }
            #[derive(Serialize, Deserialize)]
            pub struct EmptyResult {}
            #[derive(Serialize, Deserialize)]
            #[serde(rename_all = "camelCase")]
            pub struct LogsChunk { pub eof: bool, pub next_offset: u64 }
            "#,
            &mut api,
        )
        .expect("records");
        api
    }

    fn output(table: &str) -> Result<Output, String> {
        let operations = crate::operations::parse(table).expect("table");
        emit(&operations, &api())
    }

    #[test]
    fn a_job_operation_binds_the_handles_authority_and_picks_the_rest() {
        let output = output(
            r#"operations! {
                /// Reads one stream's bytes from an offset.
                worker download(offset) "job.logs" JobLogs(LogsRequest) -> LogsChunk;
            }"#,
        )
        .expect("projection");
        assert!(
            output.served.contains(concat!(
                "impl Serves<JobLogs> for JobHandle {\n",
                "    const BOUND: &'static [&'static str] = &[\"repoId\", \"workspace\", \"workspaceIncarnation\", \"jobId\"];\n\n",
                "    fn request(authority: &<Self as Binder>::Fields<'_>, arguments: Arguments) -> Result<LogsRequest> {\n",
                "        #[derive(Deserialize)]\n",
                "        #[serde(rename_all = \"camelCase\", deny_unknown_fields)]\n",
                "        struct Caller {\n",
                "            offset: u64,\n",
                "        }\n",
                "        let Caller { offset } = decode::<JobLogs, Caller>(arguments)?;\n",
                "        Ok(LogsRequest { repo_id: owned(authority.repo_id), workspace: owned(authority.workspace), workspace_incarnation: owned(authority.workspace_incarnation), job_id: owned(authority.job_id), offset })\n",
                "    }\n",
                "}",
            )),
            "{}",
            output.served
        );
        assert!(
            output
                .served
                .contains("    check.served::<JobLogs, _>(job_handle, &[]);"),
            "{}",
            output.served
        );
        assert!(
            output.rust.contains(
                "super::download_call::<operations::JobLogs, _>(env, Arc::clone(&self.inner), arguments)"
            ),
            "{}",
            output.rust
        );
        assert!(
            output
                .typescript
                .contains("export type JobLogsArguments = Pick<Api.LogsRequest, 'offset'>;"),
            "{}",
            output.typescript
        );
        assert!(
            output
                .typescript
                .contains("export interface NativeJobHandleOperations extends NativeJobLogs {}"),
            "{}",
            output.typescript
        );
    }

    /// One `Serves` impl in the generated file, from its header through its closing brace.
    fn served_impl<'a>(served: &'a str, operation: &str, class: &str) -> &'a str {
        let header = format!("impl Serves<{operation}> for {class} {{");
        let start = served
            .find(&header)
            .unwrap_or_else(|| panic!("{class} serves {operation}:\n{served}"));
        let rest = &served[start..];
        rest.find("\n}\n").map_or(rest, |end| &rest[..end + 2])
    }

    /// A read-only reference fences its repository and workspace, not the incarnation it was
    /// resolved at. It binds that incarnation all the same: a request that requires one carries
    /// it, and one that leaves it optional sends it absent while keeping it bound, so no caller
    /// names it. A worker fences its whole incarnation and always sends it.
    #[test]
    fn a_reference_sends_an_optional_incarnation_absent_while_a_worker_holds_it() {
        let output = output(
            r#"operations! {
                /// Reads one workspace's grants.
                worker json "workspace.grants" WorkspaceGrants(GrantsRequest) -> EmptyResult;
                /// The build volume a job of the workspace incarnation would be granted now.
                coordinator json "workspace.buildVolume" WorkspaceBuildVolume(WorkerScope) -> EmptyResult;
            }"#,
        )
        .expect("projection");
        let served = &output.served;
        let bound = r#"const BOUND: &'static [&'static str] = &["repoId", "workspace", "workspaceIncarnation"];"#;
        for (operation, class, construction, absent) in [
            (
                "WorkspaceGrants",
                "WorkspaceRef",
                "Ok(GrantsRequest { repo_id: owned(authority.repo_id), workspace: owned(authority.workspace), workspace_incarnation: None })",
                r#"workspace_ref, &["workspaceIncarnation"]"#,
            ),
            (
                "WorkspaceGrants",
                "WorkspaceHandle",
                "Ok(GrantsRequest { repo_id: owned(authority.repo_id), workspace: owned(authority.workspace), workspace_incarnation: Some(owned(authority.workspace_incarnation)) })",
                "workspace_handle, &[]",
            ),
            (
                "WorkspaceBuildVolume",
                "WorkspaceRef",
                "Ok(WorkerScope { repo_id: owned(authority.repo_id), workspace: owned(authority.workspace), workspace_incarnation: owned(authority.workspace_incarnation) })",
                "workspace_ref, &[]",
            ),
        ] {
            let implementation = served_impl(served, operation, class);
            assert!(implementation.contains(bound), "{implementation}");
            assert!(implementation.contains(construction), "{implementation}");
            assert!(
                served.contains(&format!("    check.served::<{operation}, _>({absent});")),
                "{served}"
            );
        }
        assert!(
            !served.contains("impl Serves<WorkspaceBuildVolume> for WorkspaceHandle"),
            "{served}"
        );
        assert!(
            output.typescript.contains(
                "export type WorkspaceGrantsArguments = Readonly<Record<string, never>>;"
            ),
            "{}",
            output.typescript
        );
    }

    #[test]
    fn a_worker_never_serves_a_coordinator_scoped_operation_of_its_namespace() {
        let output = output(
            r#"operations! {
                /// Attaches a detached workspace.
                coordinator json "workspace.attach" WorkspaceAttach(WorkspaceRequest) -> EmptyResult;
            }"#,
        )
        .expect("projection");
        assert!(
            output
                .served
                .contains("impl Serves<WorkspaceAttach> for WorkspaceRef")
        );
        assert!(
            !output
                .served
                .contains("impl Serves<WorkspaceAttach> for WorkspaceHandle"),
            "{}",
            output.served
        );
    }

    /// The caller's record decodes a field exactly as the declaration does: its explicit wire
    /// name, its default and its default function carry over, while a bound field never enters the
    /// record at all.
    #[test]
    fn a_caller_field_keeps_its_declared_spelling_and_default() {
        let mut api = api();
        crate::records::parse(
            r#"
            #[derive(Serialize, Deserialize)]
            #[serde(rename_all = "camelCase", deny_unknown_fields)]
            pub struct MoveRequest {
                pub repo_id: RepoId,
                #[serde(rename = "to")]
                pub destination: WorkspaceName,
                #[serde(default, skip_serializing_if = "Option::is_none")]
                pub into: Option<std::collections::BTreeMap<String, Vec<u8>>>,
                #[serde(default = "default_depth")]
                pub depth: u32,
            }
            "#,
            &mut api,
        )
        .expect("records");
        let operations = crate::operations::parse(
            r#"operations! {
                /// Moves a workspace.
                coordinator json "coordinator.move" CoordinatorMove(MoveRequest) -> EmptyResult;
            }"#,
        )
        .expect("table");
        let served = emit(&operations, &api).expect("projection").served;
        assert!(
            served.contains(concat!(
                "        struct Caller {\n",
                "            #[serde(rename = \"to\")]\n",
                "            destination: WorkspaceName,\n",
                "            #[serde(default)]\n",
                "            into: Option<std::collections::BTreeMap<String, Vec<u8>>>,\n",
                "            #[serde(default = \"default_depth\")]\n",
                "            depth: u32,\n",
                "        }\n",
            )),
            "{served}"
        );
        assert!(
            served.contains(
                "Ok(MoveRequest { repo_id: owned(authority.repo_id), destination, into, depth })"
            ),
            "{served}"
        );
    }

    #[test]
    fn a_request_field_its_construction_cannot_mirror_is_refused() {
        let mut api = api();
        crate::records::parse(
            r#"
            #[derive(Serialize, Deserialize)]
            #[serde(rename_all = "camelCase", deny_unknown_fields)]
            pub struct SkippingRequest {
                pub repo_id: RepoId,
                #[serde(skip_serializing)]
                pub hidden: u32,
            }
            "#,
            &mut api,
        )
        .expect("records");
        let operations = crate::operations::parse(
            r#"operations! {
                /// Skips a field.
                coordinator json "coordinator.skip" CoordinatorSkip(SkippingRequest) -> EmptyResult;
            }"#,
        )
        .expect("table");
        let error = emit(&operations, &api)
            .err()
            .expect("a skipped request field is refused");
        assert!(error.contains("skips or custom-decodes a field"), "{error}");
    }

    #[test]
    fn a_served_request_that_does_not_name_the_handle_is_refused() {
        let error = output(
            r#"operations! {
                /// Lists the jobs of whatever workspace the caller names.
                worker json "worker.listJobs" WorkerListJobs(RepoRequest) -> EmptyResult;
            }"#,
        )
        .err()
        .expect("a worker operation that leaves the workspace to the caller is refused");
        assert!(error.contains("does not name workspace,"), "{error}");
    }

    #[test]
    fn an_internal_operation_is_never_projected() {
        let output = output(
            r#"operations! {
                /// Kills a job.
                internal json "job.kill" JobKill(JobRequest) -> EmptyResult;
            }"#,
        )
        .expect("projection");
        assert!(!output.served.contains("JobKill"));
        assert!(!output.rust.contains("JobKill"));
        assert!(!output.typescript.contains("jobKill"));
    }
}
