use crate::ir::{Api, Field, Fields, Record, Shape, Variant};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;
use syn::{GenericArgument, PathArguments, Type};

const HEADER: &str =
    "// Generated by cowshed-api-gen from cowshed-core declarations. Do not edit.\n";

pub struct Output {
    pub types: String,
    pub validators: String,
}

pub fn emit(api: &Api) -> Result<Output, String> {
    let mut emitter = Emitter {
        api,
        visiting: BTreeSet::new(),
        declarations: BTreeMap::new(),
    };
    for record in api.records.values().filter(|record| record.exported) {
        emitter.record(&record.name)?;
    }
    let mut types = format!("{HEADER}import type {{ tags }} from 'typia';\n\n");
    let mut validators = format!(
        "{HEADER}import typia from 'typia';\nimport type * as Api from './api.generated.js';\n\n"
    );
    for (name, declaration) in emitter.declarations {
        types.push_str(&declaration);
        types.push('\n');
        writeln!(
            validators,
            "export const assert{name} = typia.createAssertEquals<Api.{name}>();"
        )
        .unwrap();
        writeln!(validators, "export const parse{name} = (json: string): Api.{name} => assert{name}(JSON.parse(json));").unwrap();
        writeln!(
            validators,
            "export const assert{name}List = typia.createAssertEquals<readonly Api.{name}[]>();"
        )
        .unwrap();
        writeln!(validators, "export const parse{name}List = (json: string): readonly Api.{name}[] => assert{name}List(JSON.parse(json));\n").unwrap();
    }
    Ok(Output { types, validators })
}

struct Emitter<'a> {
    api: &'a Api,
    visiting: BTreeSet<String>,
    declarations: BTreeMap<String, String>,
}

impl Emitter<'_> {
    fn record(&mut self, rust_name: &str) -> Result<String, String> {
        let record = self
            .api
            .records
            .get(rust_name)
            .ok_or_else(|| format!("API type {rust_name} has no declaration"))?;
        let name = record
            .projection
            .name
            .as_deref()
            .unwrap_or(rust_name)
            .to_owned();
        if self.declarations.contains_key(&name) || !self.visiting.insert(rust_name.to_owned()) {
            return Ok(name);
        }
        let body = if let Some(scalar) = &record.projection.scalar {
            scalar.clone()
        } else if let Some(proxy) = record
            .projection
            .wire
            .as_ref()
            .or(record.serde.into.as_ref())
            .or(record.serde.from.as_ref())
        {
            let proxy = syn::parse_str::<Type>(proxy)
                .map_err(|error| format!("{rust_name}: invalid serde proxy: {error}"))?;
            self.ty(&proxy)?
        } else {
            self.shape(record)?
        };
        let mut declaration = String::new();
        documentation(&mut declaration, &record.docs, "");
        writeln!(declaration, "export type {name} = {body};").unwrap();
        self.declarations.insert(name.clone(), declaration);
        self.visiting.remove(rust_name);
        Ok(name)
    }

    fn shape(&mut self, record: &Record) -> Result<String, String> {
        match &record.shape {
            Shape::Alias(ty) => self.ty(ty),
            Shape::Struct(fields) if record.serde.transparent => {
                let fields = match fields {
                    Fields::Named(fields) | Fields::Tuple(fields) => fields,
                    Fields::Unit => {
                        return Err(format!("{}: transparent record has no field", record.name));
                    }
                };
                let mut projected = fields.iter().filter(|field| !field.serde.skip);
                let field = projected.next().ok_or_else(|| {
                    format!("{}: transparent record has no projected field", record.name)
                })?;
                if projected.next().is_some() {
                    return Err(format!(
                        "{}: transparent record requires one projected field",
                        record.name
                    ));
                }
                self.ty(&field.ty)
            }
            Shape::Struct(fields) => self.fields(
                fields,
                record.serde.rename_all.as_deref(),
                record.serde.default,
                &record.projection.exclusive,
            ),
            Shape::Enum(variants) => {
                let mut branches = Vec::with_capacity(variants.len());
                for variant in variants {
                    if variant.serde.skip {
                        continue;
                    }
                    branches.push(self.variant(record, variant)?);
                }
                if branches.is_empty() {
                    return Err(format!("{} has no projected enum variants", record.name));
                }
                Ok(branches.join(" | "))
            }
        }
    }

    fn variant(&mut self, record: &Record, variant: &Variant) -> Result<String, String> {
        let name = renamed(
            &variant.name,
            variant.serde.rename.as_deref(),
            record.serde.rename_all.as_deref(),
        )?;
        let fields = self.fields(
            &variant.fields,
            variant
                .serde
                .rename_all
                .as_deref()
                .or(record.serde.rename_all_fields.as_deref()),
            false,
            &[],
        )?;
        if record.serde.untagged {
            return Ok(fields);
        }
        if let Some(tag) = &record.serde.tag {
            let discriminant = format!("{{ readonly {}: {} }}", quoted(tag), quoted(&name));
            if let Some(content) = &record.serde.content {
                return if matches!(variant.fields, Fields::Unit) {
                    Ok(discriminant)
                } else {
                    Ok(format!(
                        "{discriminant} & {{ readonly {}: {fields} }}",
                        quoted(content)
                    ))
                };
            }
            return if matches!(variant.fields, Fields::Unit) {
                Ok(discriminant)
            } else {
                Ok(format!("{discriminant} & {fields}"))
            };
        }
        if matches!(variant.fields, Fields::Unit) {
            match record.projection.unit_value.as_deref() {
                Some(value @ ("true" | "false")) => {
                    Ok(format!("{{ readonly {}: {value} }}", quoted(&name)))
                }
                Some(value) => Err(format!("unsupported unit projection literal {value}")),
                None => Ok(quoted(&name)),
            }
        } else {
            Ok(format!("{{ readonly {}: {fields} }}", quoted(&name)))
        }
    }

    fn fields(
        &mut self,
        fields: &Fields,
        rename_all: Option<&str>,
        default: bool,
        exclusive: &[String],
    ) -> Result<String, String> {
        match fields {
            Fields::Unit => Ok("null".to_owned()),
            Fields::Tuple(fields) => {
                let fields = fields
                    .iter()
                    .filter(|field| !field.serde.skip)
                    .map(|field| self.ty(&field.ty))
                    .collect::<Result<Vec<_>, _>>()?;
                match fields.as_slice() {
                    [field] => Ok(field.clone()),
                    fields => Ok(format!("readonly [{}]", fields.join(", "))),
                }
            }
            Fields::Named(fields) => {
                let mut object = String::from("{\n");
                let mut flattened = Vec::new();
                let mut alternatives = Vec::new();
                let mut has_fields = false;
                for field in fields.iter().filter(|field| !field.serde.skip) {
                    if field.serde.flatten {
                        flattened.push(self.ty(&field.ty)?);
                        continue;
                    }
                    let rust_name = field.name.as_deref().ok_or("named field lacks a name")?;
                    let name = renamed(rust_name, field.serde.rename.as_deref(), rename_all)?;
                    if exclusive.iter().any(|member| member == rust_name) {
                        alternatives
                            .push((name, self.ty(option_inner(&field.ty).unwrap_or(&field.ty))?));
                        continue;
                    }
                    has_fields = true;
                    documentation(&mut object, &field.docs, "  ");
                    let (optional, ty) = self.field(field, default)?;
                    writeln!(
                        object,
                        "  readonly {}{}: {ty};",
                        quoted(&name),
                        if optional { "?" } else { "" }
                    )
                    .unwrap();
                }
                object.push('}');
                if has_fields {
                    flattened.insert(0, object);
                }
                if !exclusive.is_empty() {
                    if alternatives.len() != exclusive.len() || alternatives.len() < 2 {
                        return Err(
                            "exclusive projection must name at least two existing fields"
                                .to_owned(),
                        );
                    }
                    let mut branches = Vec::with_capacity(alternatives.len());
                    for (selected, ty) in &alternatives {
                        let mut branch = format!("{{ readonly {}: {ty};", quoted(selected));
                        for (other, _) in &alternatives {
                            if other != selected {
                                write!(branch, " readonly {}?: never;", quoted(other)).unwrap();
                            }
                        }
                        branch.push_str(" }");
                        branches.push(branch);
                    }
                    flattened.push(format!("({})", branches.join(" | ")));
                }
                if flattened.is_empty() {
                    Ok("Readonly<Record<string, never>>".to_owned())
                } else {
                    Ok(flattened.join(" & "))
                }
            }
        }
    }

    fn field(&mut self, field: &Field, default: bool) -> Result<(bool, String), String> {
        let omitted = field.serde.skip_serializing_if.is_some();
        let optional = default || omitted;
        let ty = if let Some(inner) = option_inner(&field.ty) {
            if optional {
                self.ty(inner)?
            } else {
                format!("{} | null", self.ty(inner)?)
            }
        } else {
            self.ty(&field.ty)?
        };
        Ok((optional, ty))
    }

    fn ty(&mut self, ty: &Type) -> Result<String, String> {
        match ty {
            Type::Reference(reference) => self.ty(&reference.elem),
            Type::Slice(slice) => Ok(format!("ReadonlyArray<{}>", self.ty(&slice.elem)?)),
            Type::Array(array) => Ok(format!("ReadonlyArray<{}>", self.ty(&array.elem)?)),
            Type::Tuple(tuple) if tuple.elems.is_empty() => Ok("null".to_owned()),
            Type::Tuple(tuple) => Ok(format!(
                "readonly [{}]",
                tuple
                    .elems
                    .iter()
                    .map(|ty| self.ty(ty))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ")
            )),
            Type::Path(path) => {
                let segment = path.path.segments.last().ok_or("empty type path")?;
                let name = segment.ident.to_string();
                let arguments: Vec<_> = match &segment.arguments {
                    PathArguments::AngleBracketed(arguments) => arguments
                        .args
                        .iter()
                        .filter_map(|argument| match argument {
                            GenericArgument::Type(ty) => Some(ty),
                            _ => None,
                        })
                        .collect(),
                    PathArguments::None => Vec::new(),
                    PathArguments::Parenthesized(_) => {
                        return Err(format!("function type {name} cannot cross the API"));
                    }
                };
                match name.as_str() {
                    "String" | "str" | "PathBuf" | "Path" => Ok("string".to_owned()),
                    "bool" => Ok("boolean".to_owned()),
                    "u8" => Ok("number & tags.Type<'uint32'> & tags.Maximum<255>".to_owned()),
                    "u16" => Ok("number & tags.Type<'uint32'> & tags.Maximum<65535>".to_owned()),
                    "u32" => Ok("number & tags.Type<'uint32'>".to_owned()),
                    "i8" => Ok(
                        "number & tags.Type<'int32'> & tags.Minimum<-128> & tags.Maximum<127>"
                            .to_owned(),
                    ),
                    "i16" => Ok(
                        "number & tags.Type<'int32'> & tags.Minimum<-32768> & tags.Maximum<32767>"
                            .to_owned(),
                    ),
                    "i32" => Ok("number & tags.Type<'int32'>".to_owned()),
                    "u64" | "usize" => Ok("number & tags.Type<'uint64'>".to_owned()),
                    "i64" | "isize" => Ok("number & tags.Type<'int64'>".to_owned()),
                    "f32" | "f64" => Ok("number".to_owned()),
                    "NonZeroU8" | "NonZeroU16" | "NonZeroU32" | "NonZeroU64" | "NonZeroUsize" => {
                        let primitive = name.trim_start_matches("NonZero").to_ascii_lowercase();
                        let ty = syn::parse_str::<Type>(&primitive)
                            .map_err(|error| error.to_string())?;
                        Ok(format!("{} & tags.Minimum<1>", self.ty(&ty)?))
                    }
                    "Vec" | "VecDeque" => match arguments.as_slice() {
                        [inner] => Ok(format!("ReadonlyArray<{}>", self.ty(inner)?)),
                        _ => Err(format!("{name} requires one type argument")),
                    },
                    "Option" => match arguments.as_slice() {
                        [inner] => Ok(format!("{} | null", self.ty(inner)?)),
                        _ => Err("Option requires one type argument".to_owned()),
                    },
                    "Box" | "Arc" | "Cow" => match arguments.as_slice() {
                        [inner] => self.ty(inner),
                        _ => Err(format!("{name} requires one type argument")),
                    },
                    "HashMap" | "BTreeMap" => match arguments.as_slice() {
                        [key, value] => Ok(format!(
                            "Readonly<Record<{}, {}>>",
                            self.ty(key)?,
                            self.ty(value)?
                        )),
                        _ => Err(format!("{name} requires two type arguments")),
                    },
                    _ => self.record(&name),
                }
            }
            _ => Err(
                "unsupported Rust API type; declare its wire projection on the canonical type"
                    .to_owned(),
            ),
        }
    }
}

fn option_inner(ty: &Type) -> Option<&Type> {
    if let Type::Reference(reference) = ty {
        return option_inner(&reference.elem);
    }
    let Type::Path(path) = ty else {
        return None;
    };
    let segment = path.path.segments.last()?;
    if segment.ident != "Option" {
        return None;
    }
    let PathArguments::AngleBracketed(arguments) = &segment.arguments else {
        return None;
    };
    match arguments.args.first()? {
        GenericArgument::Type(ty) => Some(ty),
        _ => None,
    }
}

fn quoted(value: &str) -> String {
    let mut result = String::from("'");
    for character in value.chars() {
        match character {
            '\\' => result.push_str("\\\\"),
            '\'' => result.push_str("\\'"),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            _ => result.push(character),
        }
    }
    result.push('\'');
    result
}

fn documentation(output: &mut String, docs: &[String], indentation: &str) {
    if docs.is_empty() {
        return;
    }
    writeln!(output, "{indentation}/**").unwrap();
    for line in docs {
        writeln!(output, "{indentation} * {}", line.replace("*/", "* / ")).unwrap();
    }
    writeln!(output, "{indentation} */").unwrap();
}

fn renamed(name: &str, explicit: Option<&str>, rule: Option<&str>) -> Result<String, String> {
    if let Some(explicit) = explicit {
        return Ok(explicit.to_owned());
    }
    let Some(rule) = rule else {
        return Ok(name.to_owned());
    };
    let words = words(name);
    match rule {
        "lowercase" => Ok(name.to_lowercase()),
        "UPPERCASE" => Ok(name.to_uppercase()),
        "snake_case" => Ok(words.join("_")),
        "SCREAMING_SNAKE_CASE" => Ok(words.join("_").to_uppercase()),
        "kebab-case" => Ok(words.join("-")),
        "SCREAMING-KEBAB-CASE" => Ok(words.join("-").to_uppercase()),
        "PascalCase" => Ok(words.iter().map(|word| capitalized(word)).collect()),
        "camelCase" => Ok(words.first().cloned().unwrap_or_default()
            + &words
                .iter()
                .skip(1)
                .map(|word| capitalized(word))
                .collect::<String>()),
        _ => Err(format!("unsupported serde rename rule {rule}")),
    }
}

fn capitalized(word: &str) -> String {
    let mut chars = word.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

fn words(name: &str) -> Vec<String> {
    let mut result = Vec::new();
    let mut current = String::new();
    let mut chars = name.chars().peekable();
    let mut previous = None;
    while let Some(character) = chars.next() {
        if character == '_' || character == '-' {
            if !current.is_empty() {
                result.push(std::mem::take(&mut current));
            }
        } else {
            let boundary = character.is_uppercase()
                && previous.is_some_and(|previous: char| {
                    previous.is_lowercase()
                        || previous.is_ascii_digit()
                        || chars.peek().is_some_and(|next| next.is_lowercase())
                });
            if boundary && !current.is_empty() {
                result.push(std::mem::take(&mut current));
            }
            current.extend(character.to_lowercase());
        }
        previous = Some(character);
    }
    if !current.is_empty() {
        result.push(current);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::records;

    fn render(source: &str) -> Output {
        let mut api = Api::default();
        records::parse(source, &mut api).unwrap();
        emit(&api).unwrap()
    }

    #[test]
    fn fields_derive_names_defaults_and_omission_from_serde() {
        let output = render(
            r#"
            #[derive(Serialize)]
            #[serde(rename_all = "camelCase")]
            pub struct Answer {
                pub wall_ms: u64,
                pub cwd: Option<String>,
                #[serde(skip_serializing_if = "Option::is_none")]
                pub leader_pid: Option<u32>,
            }
            #[derive(Deserialize)]
            #[serde(default, rename_all = "camelCase")]
            pub struct Options { pub enabled: bool }
        "#,
        );
        assert!(
            output
                .types
                .contains("'wallMs': number & tags.Type<'uint64'>")
        );
        assert!(output.types.contains("'cwd': string | null"));
        assert!(output.types.contains("'leaderPid'?: number"));
        assert!(output.types.contains("'enabled'?: boolean"));
        assert!(
            output
                .validators
                .contains("createAssertEquals<Api.Answer>()")
        );
    }

    #[test]
    fn custom_wire_proxy_retains_exclusive_commands_without_cloning() {
        let output = render(
            r#"
            #[cfg_attr(any(), cowshed_api(wire = "JobRef"))]
            pub struct Job { private: bool }
            #[derive(Serialize)]
            #[cfg_attr(any(), cowshed_api(exclusive = "argv,script"))]
            struct JobRef<'a> {
                pub cwd: &'a Option<String>,
                pub argv: Option<&'a [String]>,
                pub script: Option<&'a str>,
            }
        "#,
        );
        assert!(output.types.contains("export type Job = JobRef;"));
        assert!(output.types.contains("readonly 'script'?: never"));
        assert!(output.types.contains("readonly 'argv'?: never"));
        assert!(!output.types.contains("private"));
    }

    #[test]
    fn tagged_content_flatten_and_transparent_follow_their_declarations() {
        let output = render(
            r#"
            #[derive(Serialize)] #[serde(transparent)] pub struct Id(String);
            #[derive(Serialize)] #[serde(tag = "kind", content = "value", rename_all = "camelCase")]
            pub enum Event { Started(Id), Ended }
            #[derive(Serialize)] pub struct Wrapped { #[serde(flatten)] pub event: Event }
        "#,
        );
        assert!(output.types.contains("export type Id = string;"));
        assert!(output.types.contains("readonly 'kind': 'started'"));
        assert!(output.types.contains("readonly 'value': Id"));
        assert!(output.types.contains("export type Wrapped = Event;"));
    }

    #[test]
    fn variant_payload_rename_and_try_from_proxy_are_not_guessed() {
        let output = render(
            r#"
            #[derive(Serialize)] #[serde(tag = "state", rename_all = "camelCase")]
            pub enum Measurement {
                #[serde(rename_all = "camelCase")]
                Measured { target_branch: String }
            }
            #[derive(Serialize, Deserialize)] #[serde(try_from = "Wire")]
            pub struct Checked { private_state: bool }
            #[derive(Deserialize)] struct Wire { observed_value: String }
            #[derive(Serialize)] #[serde(transparent)]
            pub struct NamedId { value: String }
        "#,
        );
        assert!(output.types.contains("readonly 'targetBranch': string"));
        assert!(!output.types.contains("target_branch"));
        assert!(output.types.contains("export type Checked = Wire;"));
        assert!(output.types.contains("readonly 'observed_value': string"));
        assert!(!output.types.contains("private_state"));
        assert!(output.types.contains("export type NamedId = string;"));
    }

    #[test]
    fn empty_record_is_not_the_non_null_any_type() {
        let output = render("#[derive(Serialize)] pub struct Empty {}");
        assert!(
            output
                .types
                .contains("export type Empty = Readonly<Record<string, never>>;")
        );
    }
}
