/**
 * Shared types for patchnote
 */

import type { Options } from 'execa';

/**
 * Simplified result interface for command execution
 * Contains only the fields we actually use from execa's Result type
 */
export interface ExecutorResult {
  /** Standard output */
  stdout: string;
  /** Standard error */
  stderr: string;
  /** Exit code */
  exitCode: number;
}

/**
 * Deep partial type - makes all properties and nested properties optional
 * Useful for partial configuration updates
 */
export type DeepPartial<T> = T extends object
  ? {
      [P in keyof T]?: DeepPartial<T[P]>;
    }
  : T;

/**
 * Update type classification
 */
export type UpdateType = 'major' | 'minor' | 'patch' | 'unknown';

/**
 * Merge strategy for auto-merging pull requests
 */
export type MergeStrategy = 'squash' | 'rebase' | 'merge';

/**
 * Dependency ecosystem
 */
export type DependencyEcosystem = 'npm' | 'nix' | 'nixpkgs' | 'expo';

/**
 * Information about a single package update
 */
export interface PackageUpdate {
  /** Package name */
  name: string;
  /** Version before update */
  fromVersion: string;
  /** Version after update */
  toVersion: string;
  /** Update type (major/minor/patch) */
  updateType: UpdateType;
  /** Ecosystem this package belongs to */
  ecosystem: DependencyEcosystem;
  /** Changelog URL or text */
  changelog?: string;
  /** Changelog source URL (e.g., GitHub releases) */
  changelogUrl?: string;
  /** Breaking changes detected */
  breakingChanges?: string[];
  /** Whether this is a dev dependency */
  isDev?: boolean;
  /** Whether provenance was downgraded (had -> lost) */
  provenanceDowngraded?: boolean;
  /** Deprecation message from npm registry (toVersion) */
  deprecatedMessage?: string;
  /** Suggested replacement package name (from Renovate mapping) */
  replacementName?: string;
  /** Suggested replacement package version (from Renovate mapping) */
  replacementVersion?: string;
}

/**
 * Result of a dependency update operation
 */
export interface UpdateResult {
  /** Whether the update was successful */
  success: boolean;
  /** List of package updates (upgrades only) */
  updates: PackageUpdate[];
  /** List of package downgrades (for informational purposes, not included in PRs) */
  downgrades?: PackageUpdate[];
  /** Error message if failed */
  error?: string;
  /** Ecosystem that was updated */
  ecosystem: DependencyEcosystem;
}

/**
 * nvfetcher source entry structure
 * Generated by nvfetcher in _sources/generated.json
 */
export interface NvfetcherSource {
  /** Package version */
  version: string;
  /** Source information (git, url, etc.) */
  src?: {
    /** Source type (git, url, pypi, etc.) */
    type?: string;
    /** Source URL */
    url?: string;
    /** Git revision/tag */
    rev?: string;
    /** SHA256 hash */
    sha256?: string;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

/**
 * nvfetcher generated sources file structure
 * Maps package name to source information
 */
export interface NvfetcherSources {
  [packageName: string]: NvfetcherSource;
}

/**
 * Information about an open PR
 */
export interface OpenPR {
  /** PR number */
  number: number;
  /** PR title */
  title: string;
  /** Branch name */
  branch: string;
  /** Creation date */
  createdAt: Date;
  /** Whether PR has merge conflicts */
  hasConflicts: boolean;
  /** PR URL */
  url: string;
}

/**
 * Expo SDK version information
 */
export interface ExpoSDKVersion {
  /** SDK version number (e.g., "52.0.0") */
  version: string;
  /** Whether this is the latest stable version */
  isLatest: boolean;
  /** Changelog URL */
  changelogUrl?: string;
}

/**
 * Expo recommended package versions for an SDK
 */
export interface ExpoPackageVersions {
  /** SDK version these recommendations are for */
  sdkVersion: string;
  /** Map of package name to version */
  packages: Record<string, string>;
}

/**
 * Expo project configuration
 * Used for managing multiple Expo apps in a monorepo
 */
export interface ExpoProject {
  /** Project name (optional, for logging) */
  name?: string;
  /** Path to package.json containing Expo dependency */
  packageJsonPath: string;
}

/**
 * Configuration for grouping/batching dependency updates into separate PRs.
 * Groups are evaluated in priority order: semver level first, then name patterns, then default.
 */
export interface GroupingConfig {
  /** Separate major updates into their own PR group */
  separateMajor?: boolean;
  /** Separate minor and patch updates into their own PR groups */
  separateMinorPatch?: boolean;
  /** Name-pattern groups: packages matching the pattern are grouped together */
  groups?: Array<{ name: string; match: string | string[] }>;
}

/**
 * Options for update commands
 */
export interface UpdateOptions {
  /** Dry run mode - don't make actual changes */
  dryRun: boolean;
  /** Skip git operations */
  skipGit: boolean;
  /** Skip AI changelog analysis */
  skipAI: boolean;
  /** Explicit path to patchnote config file */
  configPath?: string;
}

/**
 * Options for generate-workflow command
 */
export interface GenerateWorkflowOptions extends UpdateOptions {
  /** Cron schedule for workflow */
  schedule?: string;
  /** Name of the workflow */
  workflowName?: string;
  /** Explicitly enable AI (overrides auto-detection) */
  enableAI?: boolean;
}

/**
 * Options for init command
 */
export interface InitOptions extends UpdateOptions {
  /** Skip prompts and use defaults */
  yes?: boolean;
}

/**
 * Options for onboard command (CI onboarding PR creation)
 */
export interface OnboardOptions extends UpdateOptions {
  /** Verbose output */
  verbose?: boolean;
}

/**
 * Type for command executor (for testing git operations)
 * Matches the array-long form: execa(file, args, options)
 *
 * Uses simplified ExecutorResult instead of full execa Result to avoid
 * requiring mocks to implement all 15+ fields when we only use stdout/stderr/exitCode.
 * The real execa function returns a superset of this interface.
 */
export type CommandExecutor = (
  file: string | URL,
  args?: readonly string[],
  options?: Options,
) => Promise<ExecutorResult>;

/**
 * GitHub Pull Request information
 */
export interface GitHubPR {
  /** PR number */
  number: number;
  /** PR title */
  title: string;
  /** Head branch name */
  headRefName: string;
  /** Base branch name (the branch this PR targets) */
  baseRefName?: string;
  /** PR creation date */
  createdAt: string;
  /** PR URL */
  url: string;
  /** Whether the PR is mergeable (no conflicts) */
  mergeable?: 'MERGEABLE' | 'CONFLICTING' | 'UNKNOWN';
}

/**
 * Result of rebasing a single PR
 */
export interface RebaseResult {
  /** PR number */
  prNumber: number;
  /** Branch name */
  branch: string;
  /** Whether the rebase succeeded */
  success: boolean;
  /** Whether the PR was skipped */
  skipped: boolean;
  /** Reason for skipping */
  skipReason?: 'stale' | 'conflict' | 'parent-conflict' | 'branch-missing';
}

/**
 * Options for rebase-open-prs command
 */
export interface RebaseOpenPRsOptions extends UpdateOptions {
  /** Skip PRs older than this many days */
  maxAgeDays: number;
}

/**
 * Supported AI providers for changelog analysis
 * - zai: Z.AI GLM-5-Turbo (requires ZAI_API_KEY)
 */
export const SUPPORTED_PROVIDERS = ['zai'] as const;
export type SupportedProvider = (typeof SUPPORTED_PROVIDERS)[number];

/**
 * Options for sending a prompt to AI
 */
export interface SendPromptOptions {
  /** Override the default model for this request */
  model?: string;
  /** Override the provider for this request */
  provider?: SupportedProvider;
}

/**
 * Result from parsing dix (devenv diff) output
 */
export interface DixParseResult {
  /** Package upgrades */
  updates: PackageUpdate[];
  /** Package downgrades */
  downgrades: PackageUpdate[];
}

/**
 * Project setup detection result
 */
export interface ProjectSetup {
  /** Whether project uses Expo */
  hasExpo: boolean;
  /** Whether project uses Nix/devenv */
  hasNix: boolean;
  /** Whether project uses syncpack */
  hasSyncpack: boolean;
  /** Detected package manager */
  packageManager: 'bun' | 'npm' | 'pnpm' | 'yarn';
}

/**
 * GitHub client interface
 * Defines operations for pull request management
 */
export interface IGitHubClient {
  /** List open pull requests with update- prefix */
  listUpdatePRs(repoRoot: string): Promise<GitHubPR[]>;
  /** Check if a PR has merge conflicts */
  checkPRConflicts(repoRoot: string, prNumber: number): Promise<boolean>;
  /** Create a new pull request */
  createPR(
    repoRoot: string,
    options: {
      title: string;
      body: string;
      head: string;
      base: string;
      labels?: string[];
      assignees?: string[];
      reviewers?: string[];
      draft?: boolean;
    },
  ): Promise<{ number: number; url: string }>;
  /** Close a pull request with a comment */
  closePR(repoRoot: string, prNumber: number, comment: string): Promise<void>;
  /** Enable GitHub auto-merge on a pull request */
  enableAutoMerge(repoRoot: string, prNumber: number, strategy: MergeStrategy): Promise<void>;
  /** Find an open PR by head branch name */
  findPRByHead(repoRoot: string, headBranch: string): Promise<GitHubPR | null>;
  /** Update a PR body */
  editPR(repoRoot: string, prNumber: number, options: { body: string }): Promise<void>;
  /** Post a comment on a PR */
  commentOnPR(repoRoot: string, prNumber: number, body: string): Promise<void>;
}

/** Dependency filtering configuration */
export interface FilterConfig {
  /** Exclude packages matching these patterns (glob, exact name). Takes precedence over include. */
  exclude?: string[];
  /** Only update packages matching these patterns (allowlist mode). If empty/undefined, all packages are included. */
  include?: string[];
}

/**
 * Options for generate-syncpack command
 */
export interface GenerateSyncpackOptions extends UpdateOptions {
  /** Target Expo SDK version */
  expoSdkVersion?: string;
}

/**
 * Dependency section type for package rule constraints.
 * Used to limit rules to specific dependency categories.
 */
export type DepType = 'dependencies' | 'devDependencies' | 'peerDependencies';

/**
 * Per-package update rule for fine-grained control over dependency updates.
 * Rules are evaluated in order with last-match-wins override semantics.
 *
 * @example
 * ```typescript
 * // Auto-merge all @types/* packages
 * { match: '@types/*', automerge: true }
 *
 * // Pin React to 18.x
 * { match: 'react', allowedVersions: '^18' }
 *
 * // Ignore a specific package
 * { match: 'legacy-pkg', ignore: true }
 *
 * // Auto-merge patch updates for all packages
 * { match: '*', updateTypes: ['patch'], automerge: true }
 *
 * // Later rules override earlier ones for matching packages:
 * // [{ match: '*', automerge: true }, { match: 'react', automerge: false }]
 * // => react gets automerge: false, everything else gets automerge: true
 * ```
 */
export interface PackageRule {
  /** Pattern(s) to match package names. Supports exact names, globs, brace expansion, and `/regex/` patterns. */
  match: string | string[];
  /** Limit this rule to specific update severity levels. */
  updateTypes?: UpdateType[];
  /** Limit this rule to specific dependency section types. */
  depTypes?: DepType[];
  /** Override the global autoMerge setting for matched packages. */
  automerge?: boolean;
  /** Pin matched packages to their current major.minor range (~major.minor). */
  pin?: boolean;
  /** Remove matched packages from the update list entirely. */
  ignore?: boolean;
  /** Group name for batching matched packages into the same PR (stored in policy, no filtering effect). */
  group?: string;
  /** Semver range constraint -- reject updates whose toVersion does not satisfy this range. */
  allowedVersions?: string;
}

/**
 * Resolved policy for a single package after evaluating all matching rules.
 * Fields are only present if explicitly set by at least one matching rule.
 */
export interface ResolvedPackagePolicy {
  automerge?: boolean;
  pin?: boolean;
  ignore?: boolean;
  group?: string;
  allowedVersions?: string;
}

/**
 * Options for the setup command
 */
export interface SetupOptions extends UpdateOptions {
  /** Create a new GitHub App via manifest flow */
  createApp?: boolean;
  /** GitHub organization name */
  org?: string;
}

/**
 * GitHub App credentials returned from the manifest flow
 */
export interface GitHubAppCredentials {
  /** GitHub App ID */
  id: number;
  /** PEM-encoded private key */
  pem: string;
  /** Webhook secret */
  webhookSecret: string;
  /** App slug (URL-friendly name) */
  slug: string;
}
