name: CI

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: cachix/install-nix-action@v24
        with:
          extra-conf: |
            keep-outputs = true
            keep-derivations = true

      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install devenv
        run: |
          nix profile install --accept-flake-config nixpkgs#devenv
          echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

      # Cache devenv and direnv
      - name: Cache devenv
        uses: actions/cache@v4
        with:
          path: |
            tooling/direnv/.devenv
            tooling/direnv/.direnv
          key:
            ${{ runner.os }}-devenv-${{ hashFiles('tooling/direnv/devenv.yaml', 'tooling/direnv/devenv.nix',
            'tooling/direnv/devenv.lock', 'tooling/direnv/.envrc') }}
          restore-keys: |
            ${{ runner.os }}-devenv-

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build devenv shell
        run: devenv shell -- date

      - uses: nrwl/nx-set-shas@v4

      # Cache Nx
      - name: Cache Nx
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: bunx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      
      - run: bun install --no-cache
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: bun nx-cloud record -- echo Hello World
