name: CI

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: read

defaults:
  run:
    working-directory: tooling/direnv

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NIX_STORE_NAR: ${{ github.workspace }}/nix-store.nar
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            keep-outputs = true
            keep-derivations = true
            gc-keep-derivations = true
            gc-keep-outputs = true

      # Cache Nix profiles, devenv and direnv
      - name: Cache Nix profiles, devenv and direnv
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.NIX_STORE_NAR }}
            ~/.nix-profile
            ~/.local/state/nix/profiles
            ~/.cache/nix
            ${{ github.workspace }}/tooling/direnv/.devenv
            ${{ github.workspace }}/tooling/direnv/.direnv
          key:
            ${{ runner.os }}-nar-${{ hashFiles('tooling/direnv/devenv.yaml', 'tooling/direnv/devenv.nix',
            'tooling/direnv/devenv.lock') }}
          restore-keys: |
            ${{ runner.os }}-nar-

      - name: Restore Nix store from NAR
        run: ./github-ci.sh restore-store

      - uses: cachix/cachix-action@v13
        with:
          name: devenv

      - name: Install devenv
        run: ./github-ci.sh install-devenv

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # --- devenv shell -------------------------------------------------------

      - name: Build devenv shell
        run: ./github-ci.sh build-shell

      # --- Nx -----------------------------------------------------------------

      # Sets the base and head SHAs required for the nx affected commands
      - uses: nrwl/nx-set-shas@v4

      - name: Cache Nx
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: For commit affected packages, run build and test tasks
        run: ./github-ci.sh nx-affected

      - name: Clean up unused Nix store paths
        run: ./github-ci.sh nix-gc

      - name: Export Nix store to NAR file
        run: ./github-ci.sh export-store
